---
title: "PopPK models"
author: "Yi Zhang"
draft: false
bookCollapseSection: true
weight: 14
---

* Population models and PREDPP
Before we continue to the popPK models, let us review how NONMEM
treats variability in the data.

We saw that when the data are population, In NONMEM the
inter-individual  variability  refers  to the unexplained difference
between individuals' parameter values and the  typical values  in  the
population.   It  is  described in NM-TRAN using ETA(n) variables.
PRED describes the effect of  these  variables to  NONMEM via the
partial derivatives in the G array.  The variance of these variables
is given in the OMEGA matrix.

Random intra-individual variability refers to unexplained (residual)
error  in a model (the difference between observed and predicted
values).  It is  described  in  NM-TRAN  using  EPS(n)  or ERR(n)
variables. PRED describes the effect of these variables to NONMEM via
the partial derivatives in the H array.  The  variance of these
variables is given in the SIGMA matrix.


We did not cover when the data are single-subject, but here we point
the following. In this case, random inter-individual variability
refers unexplained (residual) error in a model (the difference between
observed  and  predicted values).  This, despite the fact that data
may come from a single subject, is because each observation is placed
into  a  separate individual  record, and because only level-one
random effects are needed to describe it.  It is described in NM-TRAN
using  ERR(n) or  ETA(n)  variables.   PRED describes the effect of
these vari- ables to NONMEM via the partial derivatives in the G
array.   The variance of these variables is given in the OMEGA matrix.

However,  when  the  data  are in fact from a single subject, and when
there is no need to use NONMEM terminology, then users often associate
the ETA(n) and OMEGA with intra-individual variability, which
corresponds to their experimental point of view.
