---
title: "Mixture model"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: false
---
{{< katex >}}{{< /katex >}}

* Mixture models
:PROPERTIES:
:CUSTOM_ID: mixture
:END:
Sometimes we can postulate that the data constitute a
random sample from a population comprised of multiple
subpopulations, each with a distinct set of PK parameter typical values,
and there are no covariates data recorded indicating to which subpopulation
a subject belongs. For such as scenario, mixture models
can be used to estimate \(P(m)\), the probability that a
subject belongs to subpopulation \(m\). In other words,
\(P(m)\) reflects the proportion of subpopulation \(m\) in the entire
population. That is why it is known as /mixing proportions/. In general, assume \(M\)
subpopulations, we have
$$
\sum_{m=1}^M P(m) = 1
$$
Namely, \(P\) is a \(M\)-simplex. The [[file:/docs/user-guide/fundamentals/likelihood/][individual likelihood]] is then
replaced by the mixture likelihood:
$$
L_i=\sum_{m=1}^M p(y_i|\Sigma_i, \theta^{(m)}, \Omega)P(m).
$$
That is, the likelihood for subject \(i\) is now \(P\)-weighted
average of invidual likelihood. The average is over all subpopulations, with \(\theta^{(m)}\)
as \(\theta\) for subpopulation \(m\).

For example, assume the weight is not measured in [[file:/docs/user-guide/predpp/population_model/][the previous PopPK
problem]], we can postulate that
the sample is from a population comprised of two subpopulations,
denoted by superscript \((1)\) and \((2)\):
$$
\text{CL}^{(1)}=\theta_1e^{\eta_1}, \quad \text{Vd}^{(1)}=\theta_3e^{\eta_2},
\quad \text{CL}^{(2)}=\theta_2\theta_1e^{\eta_3}, \quad \text{Vd}^{(2)}=\theta_4\theta_3e^{\eta_4}.
$$
Namely, we have
$$
\theta^{(1)} = (\theta_1, \theta_3),\quad \theta^{(2)} = (\theta_1\theta_2, \theta_3\theta_4),
$$

This model be encoded using the [[file:/docs/reference-manual/control-records/mix/][~$MIX~ record]]:
#+begin_src perl
  $PROB PHENOBARB POPULATION DATA MIXTURE MODEL
  $DATA DATA2 (6F7.0)
  $INPUT ID TIME AMT WT APGR CP=DV
  $SUBROUTINES ADVAN1 TRANS2
  $MIX
  NSPOP=2
  P(1)=THETA(5)
  P(2)=1.-THETA(5)
  $PK
  CALLFL=1
  EST=MIXEST
  CL1=THETA(1)*EXP(ETA(1))
  V1=THETA(3)*EXP(ETA(2))
  CL2=THETA(2)*THETA(1)*EXP(ETA(3))
  V2=THETA(4)*THETA(3)*EXP(ETA(4))
  IF (MIXNUM.EQ.1) THEN
    CL=CL1
    V=V1
  ELSE
    CL=CL2
    V=V2
  ENDIF
  S1=V
  $ERROR
  Y=F*EXP(EPS(1))
  $THETA (0,.0047) (0,2.0) (0,.99) (0,2.0) (0,.5,1)
  $OMEGA BLOCK(2) .05 .01 .03
  $OMEGA BLOCK(2) SAME
  $SIGMA .02
  $ESTM MAXEVAL=500 PRINT=5 INTERACTION METHOD=1
#+end_src
~NSPOP=2~ in the ~$MIX~ block indicates there are two subpopulations (\(K=2\)).
Reserved variable ~P(m), m=1,2~ is for \(P(m)\), modeled by a ~THETA~
element. The reserved variable ~MIXNUM~ contains the subpopulation
index and is used to select ~CL~ and ~V~. By fitting the above model we
estimate both sets of typical values and the mixing fraction \(P\).

A slightly more succinct way to write mixture models is to use
indicator variables. Take the following control
stream for example ([[https://github.com/nmusers/docs/tree/master/examples/example5][examples/example5]], see also [[https://github.com/nmusers/docs/tree/master/examples/example3][examples/example3]] and [[https://github.com/nmusers/docs/tree/master/examples/example4][examples/example4]]).

#+INCLUDE: "../../examples/example5/example5.ctl" src perl

In this model,

# In order for NONMEM to compute the mixture likelihood, the
# model must specify which set of THETAs is for which subpopulation.

# Reserved variable ~MIXNUM~. Thus in the above model we use ~MIXNUM~ to
# define an indicator variable ~Q~ and use it to define the typical
# value of constant of elimination corresponding to this subject.?
