---
title: "Change $DES at given time"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
weight: 20
---

* Model changes in DES
In the [[file:/docs/user-guide/fundamentals/pkode/#dose][section of ODE and dosing]], we saw that a finite infusion dose
changes the ODE system by adding the infusion rate on the RHS. NONMEM
provides a general way to extend this concept of system changes at
given time, through random variable MTIME.

Consider the Enterohepatic Recycling (EHC) model below
(examples/mtimehill).
#+begin_src perl
$PROB  EHC using MTIME for the flag

$INPUT ID DOSE=AMT TIME CP=DV WT SS=DROP II ADDL EVID
$DATA mtimess.dat

$SUBROUTINES  ADVAN6 TOL=6
$MODEL COMP=(DEPOT,INITIALOFF,DEFDOSE) COMP=(CENTRAL,DEFOBS,NOOFF)
COMP=(PERIPH) COMP=(GALL )

$PK
;# Save the value of II from the dose record.
   if (ii>0) inter=ii

   KA=THETA(1)*EXP(ETA(1))
   KE=THETA(2)*EXP(ETA(2))
   CL=THETA(3)*WT*EXP(ETA(3))
   S2=CL/KE/WT
   K41=THETA(4)*EXP(ETA(4))
   K23=THETA(5)*EXP(ETA(5))
   K32=THETA(6)*EXP(ETA(6))
   K1G=THETA(7)*EXP(ETA(7))

   if (newind<=1) then
     MTIME(1)=THETA(8)
     MTIME(2)=MTIME(1)+THETA(9)
   else
     MTIME(1)=MTIME(1)
     MTIME(2)=MTIME(2)
   endif

  ;# Update mtime variables after mtime(2) is reached.
  ;# New values are for the next dosing interval (TIME+II)
  IF (MNOW == 2) THEN
    MTIME(1) = MTIME(1)+inter
    MTIME(2) = MTIME(2)+inter
    MTDIFF=1
  ENDIF

$DES
   FLAG=MPAST(1)-MPAST(2)
   DADT(1)=-KA*A(1)+K41*A(4)*FLAG
   DADT(2)= KA*A(1)-KE*A(2)-K23*A(2)+K32*A(3)-K1G*A(2)
   DADT(3)= K23*A(2)-K32*A(3)
   DADT(4)= K1G*A(2)-K41*A(4)*FLAG

$ERROR
A1=A(1) ;# for display in table
A2=A(2)
A3=A(3)
A4=A(4)
   Y=F+EPS(1)

$THETA 1 1 1
$THETA 10  ;# rate of gall bladder emptying is large vs. other k's
$THETA 1 1 1
$THETA 3 5 ;# start emptying at T+theta(8) ; lasts till T+theta(9)
$OMEGA 1 1 1 1 1 1 1
$SIGMA  .4

$TABLE TIME A1 A2 A3 A4 NOAPPEND FILE=mtimess.tab NOPRINT
#+end_src
The model has drug transfer from compartment 4 to 1 that only appears
during a certain period of time (to reflect EHC). To
estimate the beginning and end of this period, we model them as MTIME(1)
and MTIME(2), respectively. Then values of the internal indicator variable
MNEXT, MPAST, and MNOW is shown in the follow scheme.
#+begin_src r
           MTIME(1)       MTIME(2)
  ............|..............|...........
  01111111111110000000000000000000000000 MNEXT(1)
  00000000000001111111111111110000000000 MNEXT(2)
  00000000000001111111111111111111111111 MPAST(1)
  00000000000000000000000000001111111111 MPAST(2)
  01111111111112222222222222220000000000 MNOW
#+end_src

In other words, MNEXT(i) and MPAST(i) flag the "before" and "after" of
MTIME(i), and MNOW stores the counter of MNEXT. Therefore, we define
FLAG on line 40 such that FLAG=1 during time interval (MTIME(1),
MTIME(2)], indicating the transfer between the two compartments.

Note that MTIME variables are ignored during Steady-State calculation.
This is because steady states are intended for
a single repeated dose with no changes in the status of the system.
Hence the ~$INPUT... SS=DROP~ option.
