---
title: "PKPD model"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
weight: 17
---

{{< katex >}}{{< /katex >}}

* PKPD model
PKPD model can be performed either sequentially or simultaneously. Let
us first consider simultaneous model in which PD is based on PK
plasma concentration through an effect compartment.

** PK/PD simultaneous modeled
Consider data item DV be either
concentration in the central compartment (CMT=1), or the drug effect
dependent on concentration in the effect compartment (CMT=2). The drug
effect is modeled using the Emax model. We use ADVAN3 (LSODA ODE
solver) to solve the coupled PK/PD equations numerically.
#+begin_src perl
  $PROB RUN# 702 ADVAN6
  $INPUT C ID AMT TIME DV CMT
  $DATA 006.csv IGNORE=C
  $SUBROUTINE ADVAN13 TRANS=1 TOL=10 ATOL=10
  $MODEL NCOMP=3
    COMP=(GUT)
    COMP=(CENTRAL)
    COMP=(EFFECT)
  $PK
   KA=THETA(1)*EXP(ETA(1))
   KE=THETA(2)*EXP(ETA(2))
   V2=THETA(3)*EXP(ETA(3))
   S2=V2

   KE0=THETA(4)
   EMAX=THETA(5)
   EC50=THETA(6)*EXP(ETA(4))

  $DES
   DADT(1)=-KA*A(1)
   DADT(2)=KA*A(1)-KE*A(2)
   DADT(3)=KE0*(A(2)/V2-A(3))

  $ERROR
  ;TYPE=0 FOR CP (CMT=2), TYPE=1 FOR E (CMT=3)
  CP=A(2)/S2
  CE=A(3)
  TYPE=1
  IF(CMT.EQ.2) TYPE=0
  YC=CP*(1.0+ERR(1)) ;PK residual error model
  EE=EMAX*CE/(EC50+CE)
  YE=EE+ERR(2)     ;PD residual error model
  Y= (1-TYPE)*YC + TYPE*YE
  IPRE=CP
  IF(TYPE.EQ.1) IPRE=EE

  $THETA
  (0,2)       ;[KA]
  (0,0.1)     ;[KE]
  (0,32)      ;[V2]
  (0,0.5)     ;[KE0]
  (0,1.2)     ;[EMAX]
  (0,6.7)     ;[EC50]

  $OMEGA
  0.03 ;[P]
  0.03 ;[P]
  0.03 ;[P]
  0.03 ;[P]

  $SIGMA
  0.01 ;[P]
  0.1  ;[A]

  $ESTIMATION METHOD=1 INTER MAXEVAL=5000 PRINT=5 MSF=702.MSF SIGL=12
  $COV MATRIX=R UNCONDITIONAL PRINT=E
  $TABLE ID TIME YC YE CP CE IPRE TYPE CMT CWRES FILE=702.tab NOPRINT
#+end_src

** PK/PD sequentially modeled
Assume a previous PK model run provides individual elimination rate constant and volume of
distribution prediction as data item ~KEIN~ and ~V2IN~, then we can use them in
the Emax PD model sequentially.
#+begin_src perl
;# ...
$PK
 KA=KIND
 KE=KEIN
 V2=V2IN
 S2=V2
;# LINEAR EFFECT MODEL

 INTR=THETA(1)
 SLOP=THETA(2)*EXP(ETA(1))
 KE0 =THETA(3)

$DES
 DADT(1)=-KA*A(1)
 DADT(2)=KA*A(1)-KE*A(2)
 DADT(3)=KE0*(A(2)/V2-A(3))

$ERROR
 CE=A(3)
 E=INTR+SLOP*CE

Y=E+ERR(1)

CP=A(2)/S2
IPRE=E
$THETA
(0,0.1)     ;# [INTR]
(0.5)       ;# [SLOP]
(0,0.5)     ;# [KE0]

$OMEGA
0.01 ;[P]

$SIGMA
 .01;[A]
;# ...
#+end_src
