---
title: "PK parameter model"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
weight: 14
---
{{< katex >}}{{< /katex >}}

# examples from Guide VI, III. L
* PK parameter model
Consider the following extension of the population model from
introduction. Each of 59 neonates was given some loading dose of the
drug, had a plasma drug level measured about 2 hours later, was given
maintenance doses about every 12 hours thereafter, had possibly one
trough level measured during maintenance dosing, and certainly one
level measured some time after the last maintenance dose. Due to the
long half-life of the drug, for the purposes of analysis all doses can
be regarded as intravenous bolus doses. The weight and APGAR score of
each individual are available as concomitant information. The APGAR
score (1-10) is a measure of a neonate’s health at birth.

The one compartment linear model is implemented using ADVAN1. TRANS2,
thus Cl and Vd are used for PK parameters and are described using an
exponential model, with typical values proportional to weight. For Vd,
the proportionality constant takes two possibly values depending on
the APGAR score with threshold APGAR=2.

#+begin_src perl
  $PROB PHENOBARB POPULATION DATA
  $DATA DATA1 (6F7.0)
  $INPUT ID TIME AMT WT APGR CP=DV
  $SUBROUTINES ADVAN1 TRANS2
  $PK
  ;# CLEARANCE AND VOLUME PROPORTIONAL TO WEIGHT
  ;# PROPORTIONALITY CONSTANT FOR VOLUME DEPENDS ON APGAR
  CALLFL=1
  CL=THETA(1)*WT*EXP(ETA(1))
  TVVD=THETA(2)*WT
  IF (APGR.LE.2) TVVD=THETA(3)*TVVD
  V=TVVD*EXP(ETA(2))
  S1=V
  $ERROR
  Y=F*EXP(EPS(1))
  $THETA (0,.0047) (0,.99) (0,1.0)
  $OMEGA .05 .03
  $SIGMA .02
  $ESTIM MAXEVAL=500 PRINT=5
  $COVAR
  $TABLE ID TIME AMT WT APGR
#+end_src
Note that the reserved variable assignment ~CALLFL=1~ denotes that
the PK routine is called only once for each individual record, at the
first event record of the individual. This is sufficient as the weight
is constant for each individual, and more efficient than the default
setting that evaluates ~$PK~ for every data record. This is an
example of /calling protocol/. A more verbose alternative is to
specify
#+begin_src perl
 $PK (ONCE PER INDIVIDUAL RECORD)
;#...
#+end_src

See [[file:/docs/user-guide/predpp/mixture/][mixture model]] for a modeling approach when assuming the weight is not
measured.
