#+title: NONMEM documentation

* Background

The documentation in this repo is based on previous NONMEM Guides
releases. The resources are mainly drawn from Guide IV, V, VI, VIII,
and Intro 7. For more details see references cited in the documents.

NONMEM documentation consists of
- Quick start: basic programming components of NONMEM.
- User guide: statistical background and mathematical formulatin,
  example models, and programming techniques.
- Reference manual: control records, reserved keywords, and options.
- Customization and API: user-supplied functions, performance tuning,
  and API.

* For local development
- install Hugo v0.142.0+ (extended version)
#+begin_src bash
  brew install hugo
#+end_src

- install theme (hugo-book)
#+begin_src bash
  git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book
#+end_src

- install typst (optinal, for pdf export only)
  See https://github.com/typst/typst

- install ox-hugo, ox-typst
  See [[https://ox-hugo.scripter.co/#installation]] and https://github.com/jmpunkt/ox-typst

- start hugo server (optional, for draft testing)
#+begin_src bash
  hugo server --buildDrafts --navigateToChanged
#+end_src

- Add/Edit documents in =content-org= directory

- Export
  + to html: use ox-hugo
  + to pdf: use ox-typst
