#+title: NONMEM documentation

* Background

The documentation in this repo is based on previous NONMEM Guides
releases. The resources are mainly drawn from Guide IV, V, VI, VIII,
and Intro 7. For more details see references cited in the documents.

NONMEM documentation consists of
- Quick start: basic programming components of NONMEM.
- User guide: statistical background and mathematical formulation,
  and example models.
- Reference manual: control records, reserved keywords, and options.
- Cookbook: modeling and programming techniques.

* For local development and contribution
All entries are in [[https://orgmode.org/][org-mode]] format, stored in =content= directory.

- install Hugo v0.142.0+ (extended version)
#+begin_src bash
  # MacOS
  brew install hugo

  # Ubuntu
  sudo snap install hugo

  # Windows
  # Download prebuilt binaries
#+end_src

- install theme (hugo-book)
#+begin_src bash
  git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book
#+end_src

- install typst and ox-typst (optinal, for org-export to pdf only)
  See https://github.com/typst/typst
  See https://github.com/jmpunkt/ox-typst

- start hugo server (optional, for draft testing)
#+begin_src bash
  hugo server --buildDrafts --navigateToChanged
#+end_src

- Add/Edit documents in =content= directory

- Export
  + to html: do nothing, as Hugo can parse .org files.
  + to pdf: use ox-typst.
