#+title: NONMEM documentation

* Background

The documentation in this repo is based on NONMEM Guides that are traditionally included in NONMEM releases. The resources are mainly drawn from Guide IV, V, VI, VIII,
and Intro 7. For more details see references cited in the documents.

NONMEM documentation consists of
- Quick start: basic programming components of NONMEM.
- User guide: statistical background and mathematical formulation,
  model building, and many examples.
- Reference manual: reserved keywords for control records, options,
  and data items. Advanced users can also find information of
  customization and API there.

The goal of the project is a single-entry resource for NONMEM
users. Since the documention is open sourced, it also helps us to
gather feedback for improvement.

* For local development
All entries are in [[https://orgmode.org/][org-mode]] in the =content= directory.

To build and test locally, one will need emacs (v25.0.0+), as well as:
- install Hugo v0.142.0+ (extended version)
#+begin_src bash
  # MacOS
  brew install hugo

  # Ubuntu
  sudo snap install hugo

  # Windows
  # Download prebuilt binaries
#+end_src

- install theme (hugo-book)
#+begin_src bash
  git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book
#+end_src

- install typst and ox-typst (optinal, for org-export to pdf only)
  See https://github.com/typst/typst
  See https://github.com/jmpunkt/ox-typst

Then to build the static pages or pdf, one can
- start hugo server (optional, for draft testing)
#+begin_src bash
  hugo server --buildDrafts --navigateToChanged
#+end_src

- Add/Edit documents in =content= directory

- Export (in emacs' org model)
  + to html: do nothing, as Hugo can parse .org files.
  + to pdf: use ox-typst.

- View locally generated doc
  Use browser to visit http://localhost:1313/

- Publish to "docs" directory
  #+begin_src bash
    hugo build -d docs
  #+end_src
* Contribution and bug report
Contribution to doc entries are very welcome. Before submitting PR
please follow the above steps to make sure the page(s) can be built
locally.

Users are also welcome to submit issues or seek clarification
here: https://github.com/nmusers/docs/issues.
