Mon 03/20/2023 
06:53 PM
$PROBLEM EDS50 Model Visual Acuity
$INPUT C ID TIME DOSEQ MDV DV  REPL_
$DATA robust5_sim.dat ignore=@

$PRED
MU_1=LOG(THETA(1))
MU_2=LOG(THETA(2))
MU_3=LOG(THETA(3))
MU_4=LOG(THETA(4))
MU_5=LOG(THETA(5))
MU_6=LOG(THETA(6))

IF(MDV==1) THEN
DOSE=DOSEQ
ELSE
DOSE=DOSE
ENDIF

VA0=EXP(MU_1+ETA(1))
KK=EXP(MU_2+ETA(2))
BETA=EXP(MU_3+ETA(3))

EMAXS=EXP(MU_4+ETA(4))
ED50S=EXP(MU_5+ETA(5))
GAMM=EXP(MU_6+ETA(6))

DG=DOSE**GAMM
EE=EMAXS*DG/((ED50S**GAMM)+DG)

IPRED=VA0+(1.0-EXP(-KK*TIME))*(EE-BETA*VA0)
Y=IPRED + EPS(1)

$THETA
55.0     ;[VA0]
0.005    ;[KK]
0.2      ; [BETA]
30.0     ;[EMAXS]
150.0    ;[ED50S]
(2.0 FIXED) ;[GAMM]

$OMEGA 0.07 0.5 1.0 0.17 0.49 (0.0 FIXED)
$SIGMA 28.0

$SIML (122345) SUBP=1 ONLYSIM

$TABLE C ID TIME DOSE MDV DV NOAPPEND NOPRINT ONEHEADER FILE=ed50s_fit.dat
  
NM-TRAN MESSAGES 
  
 WARNINGS AND ERRORS (IF ANY) FOR PROBLEM    1
             
 (WARNING  2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.
             
 (WARNING  98) A RANDOM QUANTITY IS RAISED TO A POWER. IF THE RESULT AFFECTS
 THE VALUE OF THE OBJECTIVE FUNCTION AND THE "ONLYSIM" OPTION IS NOT USED,
 THE USER SHOULD ENSURE THAT THE RANDOM QUANTITY IS NEVER 0 WHEN THE POWER
 IS < 1.
             
 (WARNING  100) A RANDOM QUANTITY IS USED AS A POWER. IF THE RESULT AFFECTS
 THE VALUE OF THE OBJECTIVE FUNCTION AND THE "ONLYSIM" OPTION IS NOT USED,
 THE USER SHOULD ENSURE THAT THE QUANTITY RAISED TO THE POWER IS NOT 0.

 (MU_WARNING 24) ABBREVIATED CODE IS TOO COMPLEX. UNABLE TO CHECK USE OF MU_ VARIABLES.
  
Note: Analytical 2nd Derivatives are constructed in FSUBS but are never used.
      You may insert $ABBR DERIV2=NO after the first $PROB to save FSUBS construction and compilation time
  
  
License Registered to: NONMEM license (with RADAR5NM) for ICON Pharmacometrics Team
Expiration Date:    31 DEC 2030
Current Date:       20 MAR 2023
Days until program expires :2836
1NONLINEAR MIXED EFFECTS MODEL PROGRAM (NONMEM) VERSION 7.5.2
 ORIGINALLY DEVELOPED BY STUART BEAL, LEWIS SHEINER, AND ALISON BOECKMANN
 CURRENT DEVELOPERS ARE ROBERT BAUER, ICON DEVELOPMENT SOLUTIONS,
 AND ALISON BOECKMANN. IMPLEMENTATION, EFFICIENCY, AND STANDARDIZATION
 PERFORMED BY NOUS INFOSYSTEMS.

 PROBLEM NO.:         1
 EDS50 Model Visual Acuity
0DATA CHECKOUT RUN:              NO
 DATA SET LOCATED ON UNIT NO.:    2
 THIS UNIT TO BE REWOUND:        NO
 CREATE/ADD TO FDATA.csv:        YES
 NO. OF DATA ITEMS IN DATA SET:   7
 ID DATA ITEM IS DATA ITEM NO.:   2
 DEP VARIABLE IS DATA ITEM NO.:   6
 MDV DATA ITEM IS DATA ITEM NO.:  5
0LABELS FOR DATA ITEMS:
 C ID TIME DOSEQ MDV DV REPL_
0(NONBLANK) LABELS FOR PRED-DEFINED ITEMS:
 DOSE
0FORMAT FOR DATA:
 (7E8.0)

 TOT. NO. OF DATA RECS:      1200
 TOT. NO. OF OBS RECS:      900
 TOT. NO. OF INDIVIDUALS:      300
0LENGTH OF THETA:   6
0DEFAULT THETA BOUNDARY TEST OMITTED:    NO
0OMEGA HAS BLOCK FORM:
  1
  0  2
  0  0  3
  0  0  0  4
  0  0  0  0  5
  0  0  0  0  0  6
0DEFAULT OMEGA BOUNDARY TEST OMITTED:    NO
0SIGMA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   1
0DEFAULT SIGMA BOUNDARY TEST OMITTED:    NO
0INITIAL ESTIMATE OF THETA:
 LOWER BOUND    INITIAL EST    UPPER BOUND
 -0.1000E+07     0.5500E+02     0.1000E+07
 -0.1000E+07     0.5000E-02     0.1000E+07
 -0.1000E+07     0.2000E+00     0.1000E+07
 -0.1000E+07     0.3000E+02     0.1000E+07
 -0.1000E+07     0.1500E+03     0.1000E+07
  0.2000E+01     0.2000E+01     0.2000E+01
0INITIAL ESTIMATE OF OMEGA:
 BLOCK SET NO.   BLOCK                                                                    FIXED
        1                                                                                   NO
                  0.7000E-01
        2                                                                                   NO
                  0.5000E+00
        3                                                                                   NO
                  0.1000E+01
        4                                                                                   NO
                  0.1700E+00
        5                                                                                   NO
                  0.4900E+00
        6                                                                                  YES
                  0.0000E+00
0INITIAL ESTIMATE OF SIGMA:
 0.2800E+02
0SIMULATION STEP OMITTED:    NO
 OBJ FUNC EVALUATED:         NO
 ORIGINAL DATA USED ON EACH NEW SIMULATION:         NO
 SEEDS RESET ON EACH NEW SUPERSET ITERATION:        YES
0SIMULATION RANDOM METHOD SELECTED (RANMETHOD): 4U
SEED   1 RESET TO INITIAL: YES
 SOURCE   1:
   SEED1:        122345   SEED2:             0   PSEUDO-NORMAL
 NUMBER OF SUBPROBLEMS:    1
0TABLES STEP OMITTED:    NO
 NO. OF TABLES:           1
 SEED NUMBER (SEED):    11456
 NPDTYPE:    0
 INTERPTYPE:    0
 RANMETHOD:             3U
 MC SAMPLES (ESAMPLE):    300
 WRES SQUARE ROOT TYPE (WRESCHOL): EIGENVALUE
0-- TABLE   1 --
0RECORDS ONLY:    ALL
04 COLUMNS APPENDED:    NO
 PRINTED:                NO
 HEADERS:               ONE
 FILE TO BE FORWARDED:   NO
 FORMAT:                S1PE11.4
 IDFORMAT:
 LFORMAT:
 RFORMAT:
 FIXED_EFFECT_ETAS:
0USER-CHOSEN ITEMS:
 C ID TIME DOSE MDV DV
1
 PROBLEM NO.:           1      SUBPROBLEM NO.:           1

 SIMULATION STEP PERFORMED
 SOURCE  1:
    SEED1:    1229946698   SEED2:             0
 Elapsed simulation  time in seconds:     0.01
 ESTIMATION STEP OMITTED:                 YES
 Elapsed finaloutput time in seconds:     0.02
 #CPUT: Total CPU Time in Seconds,        0.094
Stop Time: 
Mon 03/20/2023 
06:53 PM
