$PROBLEM WARFARIN PK, not using design priors in data file
$INPUT ID TIME AMT RATE EVID MDV DV TSTRAT TMIN TMAX STRAT STRATF REPX
$DATA warfarin_desprior4.csv ignore=C

$SUBROUTINES ADVAN2 TRANS1

$PK
MU_1=LOG(THETA(1))
MU_2=LOG(THETA(2))
MU_3=LOG(THETA(3))
KA=EXP(MU_1+ETA(1))
K=EXP(MU_2+ETA(2))
V=EXP(MU_3+ETA(3))
S2=V
F1=1.0

$ERROR
IPRED=A(2)/V
Y=IPRED + IPRED*EPS(1)+EPS(2)

$THETA
2.0 ;[KA]
0.25  ;[K]
15.0  ;[V]

$OMEGA 1.0 0.25 0.1
$SIGMA 0.0225 0.25

$DESIGN GROUPSIZE=12.5 FIMTYPE=1 VARCROSS=1 APPROX=FO 
        STRAT=STRAT STRATF=STRATF
$TABLE ID STRAT STRATF TIME TSTRAT TMIN TMAX EVID MDV IPRED NOAPPEND NOPRINT FILE=warfarin_desprior_opt4.tab
