$PROBLEM WARFARIN, EVALUATION
$INPUT ID TIME AMT RATE EVID MDV DV TSTRAT TMIN TMAX
$DATA warfarin_pfim2.csv ignore=@ REPL=32

$SUBROUTINES ADVAN2 TRANS2

$PK
MU_1=LOG(THETA(1))
MU_2=LOG(THETA(2))
MU_3=LOG(THETA(3))
gamma=THETA(4)
CL=EXP(MU_1+ETA(1))
V=EXP(MU_2+ETA(2))
KA=EXP(MU_3+ETA(3))
S2=V
F1=1.0

$ERROR
IPRED=A(2)/V
Y=IPRED + (IPRED**gamma)*EPS(1)

$THETA
0.15 ;[CL]
8.0  ;[V]
1.0  ;[KA]
1.0 ;[gamma]

$OMEGA (0.07) (0.02) (0.6)
$SIGMA 0.01

;$DESIGN GROUPSIZE=32 FIMTYPE=1 VARCROSS=1 APPROX=FO

$SIML (11232456) SUBP=1
$EST METHOD=1 INTERACTION NOHABORT MAXEVAL=0 PRINT=1 NSIG=3
$COV UNCONDITIONAL MATRIX=R
