#+title: Reserved variables

* Reserved variables
** Model event times
Model event times are additional PK parameters defined in the PK
routine or $PK block, related to the model event time feature of PREDPP.  A model event time is not associated with any
compartment, but, like an absorption lag time, defines a  time  to
which the system is advanced.  When the time is reached, indicator
variables are set and a call to PK is made.  At this call (and/or
subsequent  to this  call)  PK or DES or AES or ERROR can use the
indicator variables to change some aspect of the system, e.g., a term
in  a  differential equation,  or  the rate of an infusion.  This
feature may be used with any ADVAN routine.  Model times  are
independent  of  non-event  dose times.   The following are reserved
variables when used in abbreviated code.

*** MTIME
MTIME(i) is the i-th model event time.  The maximum  number  of  model  event
times is given by constant PCT in file SIZES (See sizes).

MTIME(i)  may be less than, equal to, or greater than MTIME(i+1). Any
MTIME(i) may be negative or have the value 0 (in  which  case
MPAST(i)=1  always  and  MNEXT(i)=0  always;  see  below).  If PK
defines MTIME(i) and MTIME(i+2) but not MTIME(i+1), then this has the
same  effect  as  defining  MTIME(i+1)=0.   PK  may redefine MTIME(i).
An ETA may be used in the definition of MTIME(i).

Example:
#+begin_src php
  MTIME(1)=THETA(1)
#+end_src

- Fortran usage and definition
  #+begin_src f90
  ! USAGE:
  USE PKERR_REAL, ONLY :: MTIME

  ! GLOBAL DECLARATION:
  USE SIZES, ONLY: PCT,DPSIZE
  REAL(KIND=DPSIZE) :: MTIME(PCT)
  #+end_src

  Model time parameters MTIME are stored in MTIME if they are defined in
 $PK abbreviated code or if verbatim code  is  present  in  $PK.   This
 makes  them  also  available to the ERROR routine.  However, their eta
 derivatives (if any) are not included.  Hence the ERROR routine should
 not  use model time parameters in such a way as to influence the value
 of Y if those parameters have eta derivatives.

  A user-written PK routine need not define these variables unless  per-
 haps the model time parameter values are used in the ERROR routine.

 (See model time examples).

*** MTDIFF
The value of MTDIFF is 0 when PK is called.  If PK sets MTDIFF to
      a value other than 0, e.g., MTDIFF=1, then PREDPP will understand
      that with that call to PK, the values  of  one  or  more  of  the
      MTIME(i)  have  possibly  been reset.  It is not necessary to set
      MTDIFF at a call to PK with the first record of an individual  or
      with a reset record.
- Fortran usage and definition
  #+begin_src f90
    ! USAGE:
      USE PRMOD_INT, ONLY: MTDIFF

    ! GLOBAL DECLARATION:
      INTEGER(KIND=ISIZE) :: MTDIFF
  #+end_src

 MTDIFF is of interest when model time parameters MTIME are used.

 The  value  of  MTDIFF is 0 when PK is called.  If PK sets MTDIFF to a
 value other than 0, e.g., MTDIFF=1, then PREDPP will  understand  that
 with  that  call to PK, the values of one or more of the MTIME(i) have
 possibly been reset.

 It is not necessary to set MTDIFF at a  call  to  PK  with  the  first
 record  of an individual or with a reset record.  At such calls, it is
 assumed that all MTIME(i) are being set  (if  only  to  their  default
 value of 0).

 Suppose PK has defined a value MTIME(i).  PREDPP calls PK prior to the
 advance to MTIME(i).  PK may change MTIME(i) at this  call.   However,
 the  new  value  of  MTIME(i) is ignored till after the advance.  Only
 then is the new value of MTIME(i) effective.

 MTDIFF=0 (the default) can save considerable run time when  there  are
 many  model  time parameters.  Note that the results are unpredictable
 if the times are in fact changed when MTDIFF=0.

 (See model time examples).

*** MNOW, MPAST, MNEXT
Read-only indicator variables, not to be set by PK.

 - MNOW: MNOW=i if MNEXT(i)=1 for some i.  MNOW=0 otherwise.

 - MNEXT: MNEXT(i)=1 during the advance from the previous time to MTIME(i).
      Otherwise, MNEXT(i)=0.  The previous time may be an event time, a
      non-event time, or a model event time.

 - MPAST: MPAST(i)=0 until the call to PK subsequent to the one  for  which
      MNEXT(i)=1.  At that call MPAST(i)=1. It then retains this value,
      unless MTIME(i) is redefined, in which case MPAST will be  appropriately redefined as another step function.
 - Fortran usage and definition
   #+begin_src f90
   ! USAGE:
     USE ROCM_INT, ONLY: MNOW=>MTNOW,MPAST=>MTPAST,MNEXT=>MTNEXT

   ! GLOBAL DECLARATION:
     USE SIZES, ONLY: PCT
     INTEGER(KIND=ISIZE) :: MTNOW,MTPAST(PCT),MTNEXT(PCT)
   #+end_src

 (See Circadian Example: Examples Using MTIME to Model Periodic Discon-
 tinuities in $DES)

 REFERENCES: Guide VI, section III.F.9
