#+title: Indicator variables

* Indicator variables
An indicator variable is a variable whose value is 0 or 1.   It may be
identified with an input data item, or it may be a variable defined in
the abbreviated code.  It is used to make a choice in a computation.
For  example, assume ICU is a variable which is either 0 or 1.  The
following code can be used:

#+begin_src perl
 IF (ICU.EQ.0) THEN
 CLM=TVCLM+ETA(1)
 ELSE
 CLM=TVCLM+ETA(2)
 ENDIF
#+end_src

Alternatively one can code it using an indicator variable:
#+begin_src perl
 CLM=TVCLM+(1-ICU)*ETA(1)+ICU*ETA(2)
#+end_src
This is preferred when MU variables are computed.

 In Guide V, Chapter 12, appears this example involving observations of
 two  types,  CP  and effect.  The latter is modeled by the Emax model.
 Observations of both types are recorded in the DV data item.   A  data
 item  called  TYPE  with  values  1  and  2  is  used  to  distinguish
 between  them.  This data item may be used to compute the  appropriate
 prediction in the $ERROR block, as follows:

#+begin_src perl
 $ERROR
  EMAX=THETA(5)+ETA(3)
  C50=THETA(6)+ETA(4)
  EFF=EMAX*F/(C50+F)
  Y1=EFF+ERR(1)
  Y2=F+ERR(2)
  IF (TYPE.EQ.2) THEN
  Y=Y2
  ELSE
  Y=Y1
  ENDIF
#+end_src
The IF-ELSE clause above can be coded as
#+begin_src perl
  Q=1
  IF (TYPE.EQ.2) Q=0
  Y=Q*Y1+(1-Q)*Y2
#+end_src

This technique can easily be extended to the case of more indicators:

#+begin_src perl
 $ERROR
  EMAX=THETA(5)+ETA(3)
  C50=THETA(6)+ETA(4)
  EFF=EMAX*F/(C50+F)
  Y1=EFF+ERR(1)
  Y2=F+ERR(2)
  Q1=0
  Q2=0
  IF (TYPE.EQ.1) Q1=1
  IF (TYPE.EQ.2) Q2=1
  Y=Q1*Y1+Q2*Y2
#+end_src
