---
title: "Change $DES at given time"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
---

{{< katex >}}{{< /katex >}}

* Model changes in DES
In the [[file:/docs/user-guide/fundamentals/pkode/#dose][section of ODE and dosing]], we saw that a finite infusion dose
changes the ODE system by adding the infusion rate on the RHS. NONMEM
provides a general way to extend this concept of system changes at
given time, through random variable MTIME.

Consider the Enterohepatic Recycling (EHC) model below
([[https://github.com/nmusers/docs/tree/master/examples/mtimehill]["examples/mtimehill"]]).
#+begin_src perl
$PROB  EHC using MTIME for the flag

$INPUT ID DOSE=AMT TIME CP=DV WT SS=DROP II ADDL EVID
$DATA mtimess.dat

$SUBROUTINES  ADVAN6 TOL=6
$MODEL COMP=(DEPOT,INITIALOFF,DEFDOSE) COMP=(CENTRAL,DEFOBS,NOOFF)
COMP=(PERIPH) COMP=(GALL )

$PK
;# Save the value of II from the dose record.
   if (ii>0) inter=ii

   KA=THETA(1)*EXP(ETA(1))
   KE=THETA(2)*EXP(ETA(2))
   CL=THETA(3)*WT*EXP(ETA(3))
   S2=CL/KE/WT
   K41=THETA(4)*EXP(ETA(4))
   K23=THETA(5)*EXP(ETA(5))
   K32=THETA(6)*EXP(ETA(6))
   K1G=THETA(7)*EXP(ETA(7))

   if (newind<=1) then
     MTIME(1)=THETA(8)
     MTIME(2)=MTIME(1)+THETA(9)
   else
     MTIME(1)=MTIME(1)
     MTIME(2)=MTIME(2)
   endif

  ;# Update mtime variables after mtime(2) is reached.
  ;# New values are for the next dosing interval (TIME+II)
  IF (MNOW == 2) THEN
    MTIME(1) = MTIME(1)+inter
    MTIME(2) = MTIME(2)+inter
    MTDIFF=1
  ENDIF

$DES
   FLAG=MPAST(1)-MPAST(2)
   DADT(1)=-KA*A(1)+K41*A(4)*FLAG
   DADT(2)= KA*A(1)-KE*A(2)-K23*A(2)+K32*A(3)-K1G*A(2)
   DADT(3)= K23*A(2)-K32*A(3)
   DADT(4)= K1G*A(2)-K41*A(4)*FLAG

$ERROR
A1=A(1) ;# for display in table
A2=A(2)
A3=A(3)
A4=A(4)
   Y=F+EPS(1)

$THETA 1 1 1
$THETA 10  ;# rate of gall bladder emptying is large vs. other k's
$THETA 1 1 1
$THETA 3 5 ;# start emptying at T+theta(8) ; lasts till T+theta(9)
$OMEGA 1 1 1 1 1 1 1
$SIGMA  .4

$TABLE TIME A1 A2 A3 A4 NOAPPEND FILE=mtimess.tab NOPRINT
#+end_src
The model has drug transfer from compartment 4 to 1 that only appears
during a certain period of time (to reflect EHC). To
estimate the beginning and end of this period, we model them as MTIME(1)
and MTIME(2), respectively. Then values of the internal indicator variable
MNEXT, MPAST, and MNOW is shown in the follow scheme.
#+begin_src r
           MTIME(1)       MTIME(2)
  ............|..............|...........
  01111111111110000000000000000000000000 MNEXT(1)
  00000000000001111111111111110000000000 MNEXT(2)
  00000000000001111111111111111111111111 MPAST(1)
  00000000000000000000000000001111111111 MPAST(2)
  01111111111112222222222222220000000000 MNOW
#+end_src

In other words, MNEXT(i) and MPAST(i) flag the "before" and "after" of
MTIME(i), and MNOW stores the counter of MNEXT. Therefore, we define
FLAG on line 40 such that FLAG=1 during time interval (MTIME(1),
MTIME(2)], indicating the transfer between the two compartments.

Note that MTIME variables are ignored during Steady-State calculation.
This is because steady states are intended for
a single repeated dose with no changes in the status of the system.
Hence the ~$INPUT... SS=DROP~ option.

** Smooth changes of DES
In the above example, the derivative DADT is discontinuous at MTIME(1)
and MTIME(2), i.e., the changes to the ODEs is instataneous (though
the states /A/ stays continuous). To make DADT continuous, we can
use a smooth function that changes between 0 and 1 as FLAG. Consider
the following alternative implementation of the EHC model ([[https://github.com/nmusers/docs/tree/master/examples/mtimehill]["examples/mtimehill"]]).
#+begin_src perl
$PROB  EHC using Hill (sigmoid emax model) for the flags
$INPUT      ID DOSE=AMT TIME CP=DV WT SS II ADDL EVID
$DATA       hillss.dat

$SUBROUTINES  ADVAN6 TOL=6
$MODEL COMP=(DEPOT,INITIALOFF,DEFDOSE) COMP=(CENTRAL,DEFOBS,NOOFF)
COMP=(PERIPH) COMP=(GALL )

$PK
   KA=THETA(1)*EXP(ETA(1))
   KE=THETA(2)*EXP(ETA(2))
   CL=THETA(3)*WT*EXP(ETA(3))
   S2=CL/KE/WT
   K41=THETA(4)*EXP(ETA(4))
   K23=THETA(5)*EXP(ETA(5))
   K32=THETA(6)*EXP(ETA(6))
   K1G=THETA(7)*EXP(ETA(7))

$DES
;# Save the value of II from the dose record.
   if (ii>0) inter=ii
   mt1=inter*INT(T/inter)+THETA(8)
   mt2=mt1+THETA(9)
   hill1=exp(-THETA(10)*(T-mt1))
   hill2=exp(-THETA(10)*(T-mt2))
   flag1=1./(1+hill1)  ;# changes from 0 to 1 near t=mt1
   flag2=1./(1+hill2)  ;# changes from 0 to 1 near t=mt2
   FLAG=flag1-flag2

   DADT(1)=-KA*A(1)+K41*A(4)*FLAG
   DADT(2)= KA*A(1)-KE*A(2)-K23*A(2)+K32*A(3)-K1G*A(2)
   DADT(3)= K23*A(2)-K32*A(3)
   DADT(4)= K1G*A(2)-K41*A(4)*FLAG

$ERROR
A1=A(1) ;# for display in table
A2=A(2)
A3=A(3)
A4=A(4)
   Y=F+EPS(1)

$THETA 1 1 1
$THETA 10  ;# rate of gall bladder emptying is large vs. other k's
$THETA 1 1 1
$THETA 3 5 ;# start emptying at T+THETA(8) ; lasts till T+THETA(9)
$THETA 50 ;# a very large hill exponent
$OMEGA 1 1 1 1 1 1 1
$SIGMA  .4

$TABLE TIME A1 A2 A3 A4 NOAPPEND FILE=hillss.tab NOPRINT
#+end_src
Here we construct two Hill functions of the independent time variable ~T~
that change their values in the neighborhood of time ~mt1~ and ~mt2~, and use their
differences as the smooth FLAG that rises from 0 to 1 around ~mt1~ and
back to 0 around ~mt2~. ~THETA(10)~, the exponent in the Hill
functions, represents how fast the derivatives change. The greater it
is the closer the system approache the earlier model using MTIME for
instataneous changes.

Note unlike the model using MTIME, stead-state dose is allowed here.
But keep in mind the changes in differential equations do not act
retroactively: the action of FLAG in the future does not affect the
steady-state calculations. Specifically, with data (the first a few
records of the data file for [[https://github.com/nmusers/docs/tree/master/examples/mtimehill]["examples/mtimehill"]])
#+begin_src r
#       ID DOSE=AMT      TIME        CP=DV     WT SS II ADDL EVID
         1    100.00      0.         .       79.6 1  12 100   1
         1       .        4.0         .      79.6 .  . .     2
         1       .        8.0         .      79.6 .  . .     2
         1       .       12.0         .      79.6 .  . .     2
         1       .       16.0         .      79.6 .  . .     2
         1       .       20.0         .      79.6 .  . .     2
         1       .       24.0         .      79.6 .  . .     2
#+end_src
that specifies ~II=12~, the ~$DES~ changes at ~THETA(8)~ and
~THETA(8)+THETA(9)~ /after/ the the start of the begin of intervals (0, 12),
(12, 24), etc,  when the system is steady-state. This is done by using
~INT~ (integer function)
#+begin_src f90
mt1=II*INT(T/II)+THETA(8)
#+end_src

** Periodic discontinuities in $DES
:PROPERTIES:
:CUSTOM_ID: circadian-example
:END:
Changes in ~$DES~ could be periodic. One classical example is circadian
rhythm. Consider the following model that has a change in ~$DES~ every
24 hours ([[https://github.com/nmusers/docs/tree/master/examples/step_circexa]["examples/step_circexa"]]).
#+INCLUDE: "/examples/step_circexa/step_circexa.ctl" src perl

Simlar to the first model, ~FLAG~ is the difference of MPAST
variables. The MTIME(1) and MTIME(2) variables respectively define the times at
which ~FLAG~ is set to 1 and 0, such as ~MTIME(2)-MTIME(1)=DUR~. After
MTIME(2) is reached, both variables are incremented by 24, and the
FLAG update process perpetuates itself every 24 hours. Compartment 1
is a dummy compartment intended to monitor the
FLAG variable: the amount A1 starts at 0 and is incremented by DUR
every day. A related information is the time at which the current
state vector was computed, i.e. the time to which the system was most
recently advanced. It is reported in the reserved variable ~TSTATE~.

Both ~$TABLE~ and WRITE are used in to report the values of the
variables of interest. ~WRITE~ statements are used because ~$TABLE~
functions only for event records, but not for nonevent times such as
Model times.

For an extension of the above example, consider the following biological response

\begin{equation}
R(t) = R_{\text{min}} + a\sin(z(t)), \quad t\in [t_{\text{shift}}+24n,
t_{\text{shift}}+t_{\text{dur}} + 24n].
)
\end{equation}
Here \(R_{\text{min}}\) is the flat baseline, \(n\) the counter, \(z(t)\)
the circadian function of time \(t\) that scales the sinusoidal
response interval to \([0, \pi]\). This model can be used to describe
the response baseline of a drug that influences circadian rhythms related biological
processes, e.g. metabolic effects of corticoids. If the effect of the
drug is not direct, one can express the biological response and the
drug effect in terms of an indirect response model. For example,
assume an agonist that stimulates the formation of the said biological
processes, we can model the response as

$$
\frac{dR}{dt} = k_{\text{in}}(t)(1+s(C)) - k_{\text{out}}R.
$$
where \(k_{\text{out}}\) is the constant elimination rate of the
response, \(k_{\text{in}}\) the time-varying formation rate, and
\(s(C)\) the stimulation that depends on drug concentration \(C\).
The Eq.(1) then describes the response baseline in the absence of drug,
$$
\frac{dR}{dt} = k_{\text{in}}(t),
$$
where \(K_{\text{in}}\) is sinusoidal inside certain intervals and
constant otherwise. Again we use a FLAG variable to model it ([[https://github.com/nmusers/docs/tree/master/examples/idr_circexa]["examples/idr_circexa"]]).

#+INCLUDE: "/examples/idr_circexa/idr_circexa.ctl" src perl

The ~$DES~ block describes the response as the state variable. Line 120
defines a continuous 24h clock time, through the circadian reset of
the ~MTIME(3)~ variable in ~$PK~. Note that here \(z(t)\) is implemented
using the ~INTMTIME~ variable that records ~MTIME(1)~.
