---
title: "Bayesian Priors"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: false
---

* Setting up Prior Information
Prior information is important for MCMC Bayesian analysis, but not
necessary for maximization methods.  Of greatest importance are priors
to the OMEGAs. As a general rule, if your data set consists of fewer
subjects than 100 times the dimension of the Omega matrix to be
estimated, then you should have at least uninformative OMEGA prior
information.  Priors to THETAS are assumed multivariate normal, and
priors to OMEGAS and SIGMAS are assumed inverse Wishart distributed.
Alternatively,  a residual variance in the form of its square root,
may be modeled via THETA (a sigma-like Theta parameters is set up in
example 2). See [[file:/docs/reference-manual/control-records/prior/][$PRIOR]] for prior specifications. Here we discuss the setup
for most Bayesian analysis purposes.

To set up the $PRIOR NWPRI statement such as
#+begin_src perl
$PRIOR NWPRI NTHETA=4, NETA=4, NEPS=1 NTHP=4, NETP=4, NEPP=1
#+end_src
keep in mind the following:
  - NTHETA=number of THETAs to be estimated;
  - NETA=number of Etas (OMEGAs) to be estimated (and is to be described by an NETAxNETA OMEGA matrix);
  - NEPS=number of epsilons (SIGMAs) to be estimated (and is to be described by an NEPSxNEPS SIGMA matrix);
  - NTHP=number of THETAs which have a prior;
  - NETP=number of OMEGAs with prior;
  - NEPP=number of SIGMAs with prior (NM73).  Before NM73, the NEPP
    option was ignored, as supplying priors for SIGMAs was not
    activated,
so that the $THETA records list the parameters, in order, the following:
  - NTHETA of initial THETAs;
  - NTHP of Priors to THETAS;
  - Degrees of freedom to each OMEGA block Prior;
  - Degrees of freedom to each SIGMA block Prior;
the $OMEGA records list the variances, in order, the following:
  - NETAxNETA of initial OMEGAS;
  - NTHPxNTHP of variances of Priors to THETAS;
  - NETPxNETP of priors to OMEGAS, matching the block pattern of the initial OMEGAS;
the $SIGMA records list the variances, in order, the following:
  - NEPSxNEPS of initial SIGMAS
  - NEPPxNEPP of priors to SIGMAS, matching the block pattern of the initial SIGMAS (NM73).

The following snippet shows details of setting up a THETA, OMEGA, and
SIGMA.
#+begin_src perl
$THETA 2.0 2.0 4.0 4.0 ; Initial THETAs
$OMEGA BLOCK(4) ; Initial Parameters for OMEGA
0.4
0.01 0.4
0.01 0.01 0.4
0.01 0.01 0.01 0.4
$SIGMA 0.1

$PRIOR NWPRI NTHETA=4, NETA=4, NEPS=1, NTHP=4, NETP=4, NEPP=1

; Prior information of THETAS (NTHP=4 of them)
$THETA (2.0 FIX) (2.0 FIX) (2.0 FIX) (2.0 FIX)

; Variance to prior information of THETAS (NTHPxNTHP=4x4 of them).
; Because variances are very large, this means that the prior
; information to the THETAS is highly uninformative.  Note that the
; order of $THETA values among the THETA records, and the order
; of $OMEGA values among the OMEGA records, is very important,
; But $THETAs and $OMEGAs can be interspersed.
$OMEGA BLOCK(4)
10000 FIX
0.00 10000
0.00  0.00 10000
0.00  0.00 0.0 10000

; Prior to OMEGA (NETPxNETP=4x4 if them)
$OMEGA BLOCK(4)
0.2 FIX
0.0  0.2
0.0  0.0 0.2
0.0  0.0 0.0 0.2

; Set degrees of freedom of OMEGA Prior (one value per OMEGA block)
; Uninformative Omega prior is designated by having a DF that is equal to
; the dimension size of the Omega block.
$THETA (4 FIX)

; Prior to SIGMA (NEPPxNEPP=1x1 if them)
$SIGMA 0.05 FIX

; Set degrees of freedom of SIGMA Prior (one value per SIGMA block)
; Uninformative SIGMA prior is designated by having a DF that is equal to
; the dimension size of the Sigma block.
$THETA (1 FIX)
#+end_src
By default, the number of prior experiments is 1.  However, perhaps
you have more than one previous study, and you wish to average their
contribution, forming a composite average set of prior parameters to
influence the present analysis.  In this case, add NEXP=n to the
$NWPRI record above, where n is the number of experiments.  Then, add
the prior information of each additional study with additional $THETA,
$OMEGA, and $SIGMA statements.  The order is as following.

  - $THETA records list the parameters, in order, the following:
    NTHETA of initial THETAs
    Exp 1:
    NTHP of Priors to THETAS
    Degrees of freedom to each OMEGA block Prior
    Degrees of freedom to each SIGMA block Prior
    Exp 2:
    NTHP of Priors to THETAS
    Degrees of freedom to each OMEGA block Prior
    Degrees of freedom to each SIGMA block Prior
    ...
  - The $OMEGA records list the variances, in order, the following:
    NETAxNETA of initial OMEGAS
    Exp 1:
    NTHPxNTHP of variances of Priors to THETAS
    NETPxNETP of priors to OMEGAS, matching the block pattern of the initial OMEGAS
    Exp 2:
    NTHPxNTHP of variances of Priors to THETAS
    NETPxNETP of priors to OMEGAS, matching the block pattern of the initial OMEGAS
    ...
  - The $SIGMA records list the variances, in order, the following:
    NEPSxNEPS of initial SIGMAS
    Exp 1:
    NEPPxNEPP of priors to SIGMAS, matching the block pattern of the initial SIGMAS
    Exp 2:
    NEPPxNEPP of priors to SIGMAS, matching the block pattern of the initial SIGMAS
    ...

As of NM73, you can use more informative names as follows:
   - $THETAP for theta priors;
   - $THETAPV for variance to theta priors;
   - $OMEGAP for omega priors;
   - $OMEGAPD for degrees of freedom (or dispersion factor) for omega priors;
   - $SIGMAP for SIGMA priors;
   - $SIGMAPD for degrees of freedom (or dispersion factor) for SIGMA priors.
This allows you to intersperse these records at will in the control
stream files, but it also gives NMTRAN an alternative source for
values to NTHETA, NETA, NTHT, NETP, NEPS, and NEPP that is typically
given in the $PRIOR NWPRIOR record.  However, if these values are also
listed in $PRIOR NWPRI, then these values are chosen over what is
surmised from the informatively labeled theta/omega/sigma records.
Thus, the above control stream file could be structured as follows,
with the various records in any order, and a shortened $PRIOR record
(in the following example uninformative priors are used):
#+begin_src perl
$PRIOR NWPRI

; Prior information of THETAS (NTHP=4 of them)
$THETAP (2.0 FIX) (2.0 FIX) (2.0 FIX) (2.0 FIX)

$THETA 2.0 2.0 4.0 4.0 ; Initial THETAs
$OMEGA BLOCK(4) ; Inital Parameters for OMEGA
0.4
0.01 0.4
0.01 0.01 0.4
0.01 0.01 0.01 0.4

; Set degrees of freedom of SIGMA Prior (one value per SIGMA block)
$SIGMAPD (1 FIX)

;intial parameters to sigma
$SIGMA 0.1



; Set degrees of freedom of OMEGA Prior (one value per OMEGA block)
$OMEGAPD (4 FIX)

; Prior to OMEGA (NETPxNETP=4x4 if them)
$OMEGAP BLOCK(4)
0.2 FIX
0.0  0.2
0.0  0.0 0.2
0.0  0.0 0.0 0.2


; Variance to prior information of THETAS (NTHPxNTHP=4x4 of them).
$THETAPV BLOCK(4)
10000 FIX
0.00 10000
0.00  0.00 10000
0.00  0.00 0.0 10000

; Prior to SIGMA (NEPPxNEPP=1x1 if them)
$SIGMAP 0.05 FIX
#+end_src

Informative prior information may come from a previous study.
Typically, they are used as follows. The theta priors for the present
analysis are obtained from the estimates of THETAs from the previous
study.  For example, in the report file of the previous study:
#+begin_src
FINAL PARAMETER ESTIMATE
 THETA - VECTOR OF FIXED EFFECTS PARAMETERS
         TH 1      TH 2      TH 3      TH 4
         1.64E+00  1.57E+00  7.58E-01  2.35E+00
#+end_src
would be placed in the present study control stream file as:
#+begin_src perl
$THETAP   (1.64 FIXED) (1.57 FIXED) (0.758 FIXED)
          (2.35 FIXED)
#+end_src
The variance-covariance to theta priors of the present analysis are
obtained from the variance-covariance submatrix pertaining to the
theta estimates from the previous study.  For example, the information
in the report file of the previous study:
#+begin_src
COVARIANCE MATRIX OF ESTIMATE
            TH 1      TH 2      TH 3      TH 4
 TH 1
+        2.33E-03
 TH 2
+        4.76E-04  2.86E-03
 TH 3
+        7.87E-04  1.27E-04  5.35E-03
 TH 4
+        7.80E-05  2.36E-04  1.76E-03  2.98E-03
#+end_src
would be placed in the control stream file of the present study as:
#+begin_src perl
$THETAPV BLOCK(4)
        2.33E-03 FIXED
        4.76E-04  2.86E-03
        7.87E-04  1.27E-04  5.35E-03
        7.80E-05  2.36E-04  1.76E-03  2.98E-03
#+end_src
The omega priors of the present analysis are obtained from the
estimates of OMEGAs from the previous study.  For example, from the
report file of the previous study:
#+begin_src
OMEGA - COV MATRIX FOR RANDOM EFFECTS - ETAS
            ETA1      ETA2      ETA3      ETA4
 ETA1
+        1.75E-01
 ETA2
+        8.33E-03  1.51E-01
 ETA3
+        2.98E-02  1.74E-02  2.41E-01
 ETA4
+       -8.05E-03  1.84E-02  5.14E-02  1.62E-01
#+end_src
and we can use it in the control stream of the present study:
#+begin_src perl
$OMEGAP BLOCK(4)
    1.75E-01 FIXED
    8.33E-03  1.51E-01
    2.98E-02  1.74E-02  2.41E-01
   -8.05E-03  1.84E-02  5.14E-02  1.62E-01
#+end_src
Similarly for Sigma priors, the results of the previous study:
#+begin_src
SIGMA - COV MATRIX FOR RANDOM EFFECTS - EPSILONS  ***
            EPS1
 EPS1
+        5.28E-02
#+end_src
is used in the present study as:
#+begin_src perl
$SIGMAP (5.28E-02 FIXED)
#+end_src

** TODO Degrees of freedom
