#+title: Time-varying covariates
{{< katex >}}{{< /katex >}}

* Time-varying covariates
Sometimes the covariates affecting
individual parameters change over the course of the study. For example, if
an individual had heart failure for part of his observation
period but not the rest, the metabolic clearance CL_{met} could change.
Another example is when acute renal failure occurred to
a patient, then the renal clearance CL_{ren} could change.

This time-dependency can be implemented in PREDPP recursively. Recall

$$
y_{ij} = f(x_{ij}, \phi_i) + \epsilon_{ij}.
$$
$$
\phi_{i} = \mu(z_{i}, \theta) + \eta_{i}.
$$
from [[/docs/user-guide/fundamentals/population/][population model]], the covariate values at \(t_{j+1}\) determine
\(\phi\) in time period \((t_j, t_{j+1}]\). That is, when NONMEM /advances/ system states from time \(t_j\) to \(t_{j+1}\), it uses covariates \(z\) (and in general \(x\))
at time \(t_{j+1}\) to compute \(\phi\). Therefore in order to have
\(\phi\) change appropriately with \(z\), on the data record for time
point \(t_{j+1}\) we want to place a value of \(z\) corresponding to
time period \((t_j, t_{j+1}]\). For example, if the $PK block is used to
calculate clearance CL based on covariate eGFR, then CL is peice-wise constant
between state times \(t_{j}\) and \(t_{j+1}\), and based on eGFR observation
at \(t_{j+1}\). This is sometimes refered as "Last Observation Carried
Backward" (LOCB), as opposed to "Last Observation Carried Forward" (LOCF).

One challenge of the above approach is when the covariates in \(z\)
are not measured during the time interval. In that case, one will have
to use certain interpolation method.
