#+title: Modules

* Modules
NONMEM uses FORTRAN  module to share values. They supplement the subroutine arguments.

** NONMEM-PRED modules
:PROPERTIES:
:CUSTOM_ID: nm-pred-mod
:END:
These modules contain values that are (for the most part) communicated
from  PRED  to  NONMEM.   Prior  to  NONMEM 7 these values were COMMON
blocks.  Following is a list of the MODULE, the (old)  COMMON,  and  a
description of the variables.

- NMPRD_INT (NMPRD1)
      PRED return code and user message count (IERPRD,NETEXT)

- NMPRD_CHAR (NMPRD2)
      PRED user message (ETEXT)

- NMPRD_INT (NMPRD3)
      "Copying  pass" flag and SAVE region size for NMPRD4 (COMACT,COM-
      SAV)

- NMPRD4P (NMPRD4)
      PRED-defined items for tables and scatterplots

- NMPRD_REAL (NMPRD5)
      Correlation matrix for epsilon's.

- NMPRD_INT (NMPRD6)
      Return code from routine SIMEPS.

- NMPRD_REAL (NMPRD7)
      Simulated etas for tables and scatterplots.

- NMPRD_REAL (NMPRD8)
      PRED's "recursive" flag

- NMPRD_REAL (NMPRD9)
      Data record at ICALL 0, 1 and 3

- NMPR_INT (NMPR10)
      Control information for PRED repetition feature.

- NMPR_INT (NMPR11)
      Flags to override effect of NEW option on $SIMULATION record.

- NMPR_REAL (NMPR12)
      Conditional limits on observation.

- NMPR_REAL (NMPR13)
      Lower limits defining interval datum, and their derivatives.

- NMPR_REAL (NMPR14)
      Upper limits defining interval datum, and their derivatives.

- NMPR_INT (NMPR15)
      Skip control variable.

- NMPR_REAL (NMPR16)
      Parameter values produced during Simulation Step.

- NMPR_INT (NMPR17)
      Flag indicating character of PRED variable F.

** NONMEM read-only modules
These modules contain read-only values that are communicated from NONMEM to PRED and other user-supplied routines.

- ROCM_REAL (ROCM0)
      Current theta (THETA)

- ROCM_REAL (ROCM1)
      DV, data items in current L1 record

- ROCM_INT (ROCM1C)
      Size  of  current L1 record (prior to NONMEN 7, this was combined
      with ROCM1).

- ROCM_INT (ROCM2)
      Number of L2 records and length of L2 record

- ROCM_REAL (ROCM3)
      Predictions and derivatives with current L1 record

- ROCM_REAL (ROCM4)
      Selected data from an individual record

- ROCM_INT (ROCM4)
      Selected data from an individual record

- ROCM_REAL (ROCM5)
      Predictions and derivatives with current L2 record

- ROCM_REAL (ROCM6)
      Initial/final theta, omega, sigma

- ROCM_REAL (ROCM7)
      Standard errors of estimates of theta, omega, sigma

- ROCM_REAL (ROCM8)
      Final value of the objective function

- ROCM_INT (ROCM9)
      Return codes from Estimation and Covariance Steps

- ROCM_INT (ROCM10)
      Simulation: no. of replications (total and current)

- ROCM_INT (ROCM11)
      Mixture: index of subpopulation (current and most probable)

- ROCM_INT (ROCM12)
      Second and first derivative flags for PRED

- ROCM_INT (ROCM13)
      Simulation: Final pass flag for PRED and CONTR

- NMPRD_INT (ROCM14)
      Problem and subproblem counters.

- NMPRD_INT (ROCM15)
      List of inactive etas.

- ROCM_REAL (ROCM16)
      The number of significant digits in the the vector of final esti-
      mates.

- ROCM_INT (ROCM17)
      New level 2 record flag

- ROCM_REAL (ROCM18)
      Nonparametric   estimates:   height  and  heights  of  cumulative
      marginals

- ROCM_REAL (ROCM22)
      Current value of omega.

- ROCM_REAL (ROCM25)
      Mixing probabilities

- ROCM_REAL (ROCM28)
      Superproblem printing indicator

- NMPRD_INT (ROCM29)
      Population vs. single-subject data flag.

- ROCM_REAL (ROCM31)
      Template record at ICALL=6.

- ROCM_INT (ROCM32)
      Number of the individual record and of the data record.

- ROCM_INT (ROCM34)
      NEWIND at ICALL 0, 1 and 3.

- ROCM_INT (ROCM35)
      Numbers of thetas, etas and epsilons in the problem.

- ROCM_REAL (ROCM36)
      Individual's  posterior  variance-covariance  matrix.   No   help
      entry.

- ROCM_INT (ROCM37)
      Indicator that Estimation Step is omitted and obj. func. is being
      evaluated  for first time.  No help entry.

- ROCM_REAL (ROCM38)
      Conditional limits for observations  in  individual  record.   No
      help entry.

- ROCM_REAL (ROCM39)
      Conditional limits for observation.  No help entry.

- ROCM_REAL (ROCM40)
      Lower  Limits  defining  interval datum, and their derivatives in
      individual record. No help entry.

- ROCM_REAL (ROCM41)
      Upper Limits defining interval datum, and  their  derivatives  in
      individual record. No help entry.

- ROCM_REAL (ROCM42)
      Lower  Limits defining interval datum, and their derivatives.  No
      help entry.

- ROCM_REAL (ROCM43)
      Upper Limits defining interval datum, and their derivatives.   No
      help entry.

- ROCM_REAL (ROCM44)
      Probability that observation is within (outside) limits.

- ROCM_REAL (ROCM45)
      Probability that category occurs.

- ROCM_INT (ROCM46)
      Number  of  individual  records with observations, and indices of
      first and last such record.

- ROCM_REAL (ROCM47)
      Mixture probabilities with individual record containing  template
      record.

- ROCM_INT (ROCM48)
      Length of individual record.

- ROCM_REAL (ROCM49)
      Prediction,  residual, and weighted residual values for all meth-
      ods, as well as normalized probability distribution error.

- ROCM_INT (ROCM50)
      ID data item for the individual contributions  to  the  objective
      function.

- ROCM_REAL (ROCM50)
      Individual contributions to the objective function.

Except  as  noted,  each has its own entry in the Help document.  Some
modules are not fully documented.  The interested user may be able  to
obtain more information by studying the appropriate sections of NONMEM
code and previous examples that may be available from advanced users.

 REFERENCES: Guide IV, section IV.E

 REFERENCES: Guide VI, section III.E.4 , III.I ,  Figures 5, 6


** Module variables
The following names are reserved in all abbreviated code:
   #+begin_src f90
     GETETA
     SIMETA
     SIMEPS
     COMSAV
     NWIND
     ETEXT
     IERPRD
     IERPRDU
     MSEC
     MFIRST
     NETEXT
     ETA1, ETA2, ...ETA9
     ETA10, ETA11, ...ETA99
     Annnnn !! nnnnn is numeric 00000-99999, and nnnn is numeric 0000 -9999
     ! Similarly
     Bnnnnn,Cnnnnn,Dnnnnn,Ennnnn,Fnnnnn,Pnnnnn,Qnnnnn,MCnnnn,MEnnnn,MGnnnn,MTnnnn
   #+end_src
Names of modules and of variables in the modules are also reserved. [fn:6]
Below  is  a list of blocks of abbreviated code and the modules and
variables that may be used.  Second is a list of  modules,  the
variables  in  the  modules,  and  the blocks of abbreviated code in
which these variables may be used.

#+begin_src f90
  ! $AES
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  PKERR_REAL: MTIME
  PRMOD_INT:  ICALL,IDEFD,IDEFA
  PRMOD_INT:  MTDIFF
  PROCM_INT:  ISFINL
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NVNT
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: EVTREC
  PROCM_REAL: THETA
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  MIXP

  ! $DES
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  PKERR_REAL: MTIME
  PRMOD_INT:  ICALL,IDEFD,IDEFA
  PRMOD_INT:  MTDIFF
  PROCM_INT:  ISFINL
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NVNT
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: EVTREC
  PROCM_REAL: THETA
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  MIXP

  ! $ERROR
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_REAL:  CTLO
  NMPR_REAL:  CTUP
  NMPR_REAL:  YLO,YUP
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PKERR_REAL: MTIME
  PRMOD_INT:  MTDIFF
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NEWIND
  PROCM_REAL: A
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  TEMPLT

  ! $INFN
  CMNM1_INT:  NIND_7
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NWIND
  NMPRD_INT:  PRED_IGNORE_DATA,PRED_IGNORE_DATA_TEST
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPRD_REAL: PASSRC
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_INT:   SKIP_
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PRMOD_INT:  I_SS,ISSMOD
  ROCM_INT:   IERE,IERC
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  CNTID
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OBJECT
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR
  ROCM_REAL:  THETAF,OMEGAF,SIGMAF,THETAFR
  ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_
  ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_,
  ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_
  ROCM_REAL:  NPDE_,ECWRES_

  ! $MIX
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  TEMPLT
  ROCM_REAL:  THETA,DATA

  ! $PK
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PKERR_REAL: MTIME
  PRMOD_INT:  I_SS,ISSMOD
  PRMOD_INT:  MTDIFF
  PRMOD_REAL: A_0
  PROCM_INT:  A_0FLG
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NEWIND
  PROCM_REAL: A
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: TSTATE
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y

  ! $PRED
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  I_REC
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_INT:  PRED_IGNORE_DATA,PRED_IGNORE_DATA_TEST
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_INT:   SKIP_
  NMPR_REAL:  CTLO
  NMPR_REAL:  CTUP
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  NMPR_REAL:  YLO,YUP
  ROCM_INT:   IERE,IERC
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OBJECT
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR
  ROCM_REAL:  TEMPLT
  ROCM_REAL:  THETAF,OMEGAF,SIGMAF,THETAFR
  ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_
  ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_,
  ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_
  ROCM_REAL:  NPDE_,ECWRES_
#+end_src

Another view of the above list is through the Fortran modules

#+begin_src f90
!MODULES:   !VARIABLES                                 ! NONMEM CONTROL RECORD BLOCKS
CMNM1_INT:  NIND_7                                     ! $ERROR $PK $PRED $INFN
NMPRD_INT:  COMACT,COMSAV                              ! $DES $AES $ERROR $PK $PRED
NMPRD_INT:  I_REC                                      ! $PRED
NMPRD_INT:  MSEC,MFIRST,IFIRSTEM                       ! $DES $ERROR $PK $PRED
NMPRD_INT:  NEWL2                                      ! $ERROR $PRED $INFN
NMPRD_INT:  NPROB,IPROB                                ! $DES $AES $ERROR $MIX $PK $PRED $INFN
NMPRD_INT:  NTHES_,NETAS_,NEPSS_                       ! $DES $AES $ERROR $MIX $PK $PRED
NMPRD_INT:  NWIND                                      ! $INFN
NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM          ! $DES $AES $ERROR $MIX $PK $PRED $INFN
NMPRD_REAL: CORRL2                                     ! $ERROR $PK $PRED $INFN
NMPRD_REAL: ETA,EPS                                    ! $ERROR $PK $PRED $INFN
NMPRD_REAL: PASSRC                                     ! $INFN
NMPR_INT:   F_FLAG                                     ! $ERROR $PRED $INFN
NMPR_INT:   RPTI,RPTO,RPTON,PRDFL                      ! $DES $AES $ERROR $PK $PRED $INFN
NMPR_INT:   SKIP_                                      ! $PRED $INFN
NMPR_REAL:  CTLO                                       ! $ERROR $PRED $ERROR $PRED
NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR               ! $PK $PRED $INFN
NMPR_REAL:  YLO,YUP                                    ! $ERROR $PRED
NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR               ! $ERROR
PKERR_REAL: MTIME                                      ! $DES $AES $ERROR $PK
PRMOD_INT:  ICALL,IDEFD,IDEFA                          ! $DES $AES
PRMOD_INT:  I_SS,ISSMOD                                ! $PK $INFN
PRMOD_INT:  MTDIFF                                     ! $DES $AES $ERROR $PK
PRMOD_REAL: A_0                                        ! $PK
PROCM_INT:  A_0FLG                                     ! $PK
PROCM_INT:  ISFINL                                     ! $DES $AES
PROCM_INT:  MNOW,MPAST,MNEXT                           ! $DES $AES $ERROR $PK
PROCM_INT:  NEWIND                                     ! $ERROR $PK
PROCM_INT:  NVNT                                       ! $DES $AES
PROCM_REAL: A                                          ! $ERROR $PK
PROCM_REAL: DOSREC                                     ! $DES $AES $PK
PROCM_REAL: DOSTIM                                     ! $DES $AES $PK
PROCM_REAL: EVTREC                                     ! $DES $AES
PROCM_REAL: THETA                                      ! $DES $AES
PROCM_REAL: TSTATE                                     ! $PK
ROCM_INT:   IERE,IERC                                  ! $PRED $INFN
ROCM_INT:   LIREC                                      ! $ERROR $PK $PRED $INFN
ROCM_INT:   MIXNUM,MIXEST                              ! $DES $AES $ERROR $PK $PRED $INFN
ROCM_INT:   NINDR,INDR1,INDR2                          ! $ERROR $MIX $PK $PRED $INFN
ROCM_INT:   NIREC,NDREC                                ! $DES $AES $ERROR $MIX $PK $PRED $INFN
ROCM_INT:   NREP,IREP                                  ! $DES $AES $ERROR $MIX $PK $PRED $INFN
ROCM_REAL:  CDEN_,DEN_                                 ! $ERROR $PK $PRED $INFN
ROCM_REAL:  CNTID                                      ! $ERROR $PK $PRED $INFN
ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_ ! $PRED $INFN
ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_    ! $PRED $INFN
ROCM_REAL:  IIDX                                       ! $ERROR $PK $PRED $INFN
ROCM_REAL:  MIXP                                       ! $DES $AES $ERROR $PK $PRED $INFN
ROCM_REAL:  NPDE_,ECWRES_                              ! $PRED $INFN
ROCM_REAL:  OBJECT                                     ! $PRED $INFN
ROCM_REAL:  OMEGA                                      ! $ERROR $PK $PRED
ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_       ! $PRED $INFN
ROCM_REAL:  PR_CT                                      ! $ERROR $PK $PRED $INFN
ROCM_REAL:  PR_Y                                       ! $ERROR $PK $PRED $INFN
ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR               ! $PRED $INFN
ROCM_REAL:  TEMPLT                                     ! $ERROR $MIX $PRED
ROCM_REAL:  THETA,DATA                                 ! $MIX $PRED $INFN
#+end_src

** NONMEM_RESERVED
Some internal NONMEM variables are not directly available in NM-TRAN
abbreviated code and normally require verbatim code. A way around this
is to put their MODULE definitions in an include file whose name
starts with NONMEM_RESERVED (case-insensitive), then include that file
at the start of any abbreviated-code block that needs them. After
that, NM-TRAN treats those variables as allowed in abbreviated code,
so they can be used without verbatim sections.

A  list  of  [[guides/useful_variables.pdf][variables]] has been compiled. They require judicious use.

The =NONMEM_RESERVED_GENERAL= file in the ..\util directory has a  few
of  the quite useful variables listed.  It needs to be copied to the
present run directory so that NM-TRAN has access to it.  Note that
there may be  user-defined  variable names in the control stream that
inadvertently have the same names as variables in
NONMEM_RESERVED_GENERAL, which  may  cause compiler errors.  If so,
make a smaller version of NONMEM_RESERVED_GENERAL  with  a  name  also
starting  with   "NONMEM_RESERVED"  that contains only those reserved
variables of interest.

For example, =NONMEM_RESERVED_GENERAL= contains
#+begin_src f90
USE NMBAYES_INT, ONLY: ITER_REPORT,BAYES_EXTRA_REQUEST,BAYES_EXTRA
#+end_src
These variables can be used as shown in example 8:
#+begin_src perl
$PK
include nonmem_reserved_general
BAYES_EXTRA_REQUEST=1
 ....
IF(BAYES_EXTRA==1 .AND. ITER_REPORT>=0 .AND. TIME==0.0) THEN
WRITE(50,*) ITER_REPORT,ID,CL,V1,Q,V2
ENDIF
#+end_src
ITER_REPORT contains the present iteration number as reported to the
console  or NONMEM report file.  BAYES_EXTRA and BAYES_EXTRA_REQUEST
are described in example8.ctl.

[fn:6] With NONMEM 7.2 and higher, either upper or lower case may be
used. Variables in modules whose names start ROCM or PROCM may be used
only on the right. Variables  in  modules  whose  names start NMPR or
PRDPK may always be used on the right and may sometimes be used on the
left. Names of modules are reserved and may not be  used  in  any
block  of abbreviated code.
