#+title: Subroutines

* User-defined subroutines
** AES
For use with PREDPP's ADVAN9 and ADVAN15 and ADVAN17.

#+begin_src f90
 USAGE:
 SUBROUTINE AES (INIT,A,P,T,E,IR,DA,DP,DT)
 USE SIZES, ONLY: DPSIZE,ISIZE
 INTEGER (KIND=ISIZE) :: INIT,IR
 REAL(KIND=DPSIZE) :: A,P,E,DA,DP,DT
 DIMENSION :: A(*),P(*),E(*),DA(IR,*),DP(IR,*),DT(*)
#+end_src
The AES subroutine is called by PREDPP to evaluate  algebraic  expressions for ADVAN9, ADVAN15, and ADVAN17.

Input argument:

- P(n) The value of the nth PK parameter.

- T:    Time. T takes values continuously over an integration interval.

Input/output arguments:

- INIT When AES is called with INIT=1, this is an initial condition call
      at the start of an integration interval.  Approximate amounts  in
      each  equilibrium compartment n at time T must be stored in A(n).
      (The amounts in  the  non-equilibrium  compartments  are  already
      stored in the lower-numbered elements of A.)  DA, DP, DT need not
      be computed.

      If AES stores approximate values in A, it must set INIT=0.
      If AES stores exact values in A, it must leave INIT unchanged.

      When AES is called with  INIT=2,  the  values  of  the  algebraic
      expressions  must  be  stored in E and the derivatives in DA, DP,
      and DT.

- A(n) The amount in the nth compartment at time T.

Output argument:

- E(k) The value of the algebraic expression g(k).

- DA(k,j)
      The derivative of g(k) with respect to A(j).

- DP(k,j)
      The derivative of g(k) with respect to P(j).

- DT(k)
      The derivative of g(k) with respect to T.

Also see variables in NONMEM modules, NONMEM-PRED modules, and  PREDPP
 modules.
 (See variables in modules)
 In particular,
 (See DES AES: ICALL,IDEFD,IDEFA)

 REFERENCES: Guide IV, section V.C.8 , V.C.9
 REFERENCES: Guide VI, section VI.E


**  DES
For  use  with ADVAN 6,8,9,13,14,15,16,17,18, called by PREDPP to evaluate right-sides of differential equations.
#+begin_src f90
 USAGE:

 SUBROUTINE DES (A,P,T,DADT,IR,DA,DP,DT)
 USE SIZES, ONLY: DPSIZE,ISIZE
 INTEGER(KIND=ISIZE) :: IR
 REAL(KIND=DPSIZE) :: A,P,DADT,DA,DP,DT
 DIMENSION :: A(*),P(*),DADT(*),DA(IR,*),DP(IR,*),DT(*)
#+end_src
Input argument:

- A(n) The amount in the nth compartment at time T.

- P(n) The value of the nth PK parameter.

- T:    Time. T takes values continuously over an integration interval.

Output argument:

- DADT(n)
      The derivative with respect to T of the nth compartment's amount.
      It is important to note that PREDPP itself adds in the rates  for
      any infusions that may be active.

      It  is  possible to introduce drug into a compartment by explicit
      terms in a differential equation,  rather  than  by  PREDPP  dose
      event records.  Drug introduced in this manner is not included by
      PREDPP in the computation of the  output  compartment.   Specifi-
      cally,  the amount in the output compartment may be thought of as
      being calculated by summing all relevant  doses  from  the  INPUT
      file  (i.e.,  those  that precede the time of the present record,
      accounting for bioavailability), subtracting all amounts  present
      in  compartments other than the output compartment, and then mul-
      tiplying the result by the output fraction parameter.

      For example, suppose differential equations were used for ADVAN2,
      rather than the analytic solution.  They would be:
      DADT(1)=-P(3)*A(1)
      DADT(2)= P(3)*A(1)-P(1)*A(2)

- DA(n,j)
      The  derivative  of  DADT(n) with respect to A(j). Continuing the
      above example,
      DA(1,1)=-P(3)
      DA(2,1)= P(3)
      DA(2,2)=-P(1)

- DP(n,j)
      The derivative of DADT(n) with respect to  P(j).  Continuing  the
      above example,
      DP(1,3)=-A(1)
      DP(2,3)= A(1)
      DP(2,1)=-A(2)

- DT(n)
      The derivative of DADT(n) with respect to T.

The  format  of arrays DA, DP, DT described above is called "full
format".  Alternately, compact format may be used  (See prdde1).   It
is the  default format for these arrays.  A description of compact
format is beyond the scope of this document, but is described in  the
NONMEM 7.4 version of Guide VI, Appendix IV. Compact Arrays in DES.

See variables in NONMEM modules, NONMEM-PRED modules, and PREDPP modules.
 (See variables in modules)
In particular, (See DES AES: ICALL,IDEFD,IDEFA)

 REFERENCES: Guide IV, section V.C.7

 REFERENCES: Guide VI, section VI.C


** ERROR
USAGE: Versions before NONMEM 7.2:

#+begin_src f90
SUBROUTINE ERROR (ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,F,G,HH)
USE SIZES, ONLY: DPSIZE,ISIZE,LVR
INTEGER (KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS
REAL(KIND=DPSIZE) :: THETA,F,G,HH
DIMENSION IDEF(*),THETA(*),EVTREC(IREV,*),INDXS(*),G(LVR,*)
DIMENSION HH(LVR,*)
#+end_src

With NONMEM 7.2 and higher:

#+begin_src f90
SUBROUTINE ERROR (ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,F,G,HH)
USE SIZES,     ONLY: DPSIZE,ISIZE
USE PRDIMS,    ONLY: GERD,HERD
IMPLICIT REAL(KIND=DPSIZE) (A-Z)
REAL(KIND=DPSIZE) :: EVTREC
INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS
DIMENSION :: IDEF(*),THETA(*),EVTREC(IREV,*),INDXS(*)
REAL(KIND=DPSIZE) :: G(GERD,*),HH(HERD,*)
#+end_src
The  ERROR  subroutine  is  called by PREDPP to model intra-individual
error in observed values.  It can also be used to to  convert  predic-
tions  from  PREDPP, i.e., scaled drug amounts, to other types of pre-
dictions (for example, to obtain the prediction of a drug effect as  a
function of concentration, in a pharmacodynamic study).


Input argument:

-  ICALL
   + ICALL=1:  ERROR  has been called for initialization at the
     beginning of a NONMEM problem; one such call per problem.  EVTREC
     contains  the  first event record.  THETA contains the initial
     estimates.  ERROR must return values in IDEF which inform PREDPP
     what tasks it will perform at later calls.  It may also set
     elments of HH to the appropriate derivatives, when  it  has
     requested  that ERROR be called only once per problem.

   + ICALL=2:  ERROR has been called to obtain the modeled value;
     multiple calls occur.  ERROR should compute derivatives of F for
     HH. If  ERROR  changes F, it should also change the derivates of
     F in G.

   + ICALL=4: ERROR has been called during the Simulation Step; multi-
      ple calls occur.  ERROR should compute simulated observations and
      store them in F.

   + ICALL=5: ERROR has been called during the computation of expecta-
      tions;  multiple calls occur.  Such calls occur when the marginal
      (MRG_) data item is defined in the data set and has non-zero val-
      ues  for  some records.  If the MRG_ data item has the value 1 or
      2, expectations are computed  for  that  record,  and  the  value
      returned  by  ERROR  in  F contributes to the expectation that is
      being computed for the PRED data item.  The value  of  an  ERROR-
      defined  item  contributes  to  the  expectation computed for the
      item.

   + ICALL=6: ERROR has been called during the computation of raw data
      averages;  multiple  calls occur.  Such calls occur when the raw-
      data (RAW_) data item is defined in the  data  set  and  has  the
      value 1 for some records (See template).  ERROR may re-compute DV
      when the value of DV in the data record is not the quantity to be
      included  in  the average.  ERROR may return a value of 1 in F if
      no DV item is to be included in the average with  the  particular
      record.

-  THETA
      The NONMEM THETA vector.

-  EVTREC
      The PREDPP event record.

-  INDXS
      The  values specified in the $INDEX record of the NM-TRAN control
      stream.  (This is the NONMEM INDXS array starting at position 12,
      the first position beyond those positions used by PREDPP itself.)

Output argument:

-  IDEF
      ERROR  should store values in IDEF only when ICALL=1.  A value of
      1 in IDEF(1) indicates that ERROR will store the  derivatives  of
      log  y  in HH (which causes PREDPP to multiply each element of HH
      by F).  That is, PREDPP understands that the "error in log y"  is
      modeled.

      The value in IDEF(2) describes when ERROR should be called:
        + -1 call with every event record.
        +  0 call once per observation record.
        +  1 call once per individual record.
        +  2 call once per problem.

      The  value in IDEF(3) describes whether ERROR uses derivatives of
      compartment amounts (i.e. whether compartment amounts  themselves
      are used as random variables in arithmetic statements in ERROR).
        + -1 ERROR may use derivatives of A.
        +  0 ERROR does not use derivatives A.
        +  1 ERROR does use derivatives of A.

      The  default  used  by PREDPP is IDEF(3)=-1.  However, when ERROR
      does not use A, then if IDEF(3) is set to  0,  PREDPP  can  avoid
      some  time-consuming processing.  Indeed, when $ERROR abbreviated
      code is supplied, and there is  no  reference  to  a  compartment
      amount  A(n) (as a random variable in an arithmetic statement) in
      the abbreviated code (or to its derivatives  in  verbatim  code),
      then NM-TRAN sets IDEF(3)=0.

Input/Output argument:

- F   On  input,  the  prediction  based  on the pharmacokinetic model,
      i.e., the value of the scaled drug amount in the observation com-
      partment.   On output, F may be unchanged, or it may be modified,
      e.g., when a PD prediction is needed.  If ERROR  modifies  F  and
      uses  population  eta  variables  to do so, then at ICALL=2 ERROR
      must call GETETA to obtain eta values prior to modifying F.  When
      ICALL=4,  ERROR should calculate the simulated observation (after
      calling  SIMETA  and/or  SIMEPS  to  obtain  simulated  etas  and
      epsilons, as necessary) and place its value in F.  With the Simu-
      lation Step, ERROR may return the simulated observation as the DV
      data item, rather than in the argument F.  With odd-type data the
      simulated observation must be  returned  as  the  DV  data  item.
      (See $estimation).

- G   On  input,  at  ICALL=2 when the data are population, an array of
      partial derivatives of F with respect to etas
      G (i,1) is the partial derivative of F with respect to eta(i).
      G (i,j+1) is the second derivative of F with respect  to  eta(i),
      eta(j) (lower-triangular; j=1, ..., i).
      (Second derivatives are only needed with estimation by the Lapla-
      cian method.)
      On input, G contains zeros when the data are single-subject data.
      At ICALL=2, ERROR must modify G when it has  changed  F  and  has
      thus  changed the derivatives of F with respect to the population
      etas.

- HH  An array of partial derivatives of F with respect to  etas  (when
      the  data are single-subject data) or epsilons (when the data are
      population).  Values should be stored when ICALL=2 and also  when
      ICALL=1 if ERROR sets IDEF(2)=2.
      HH(i,1) is the derivative of F with respect to eta(i) or eps(i).
      HH(i,j+1) is the derivative of H(i,1) with respect to eta(j) (but
      are only needed with conditional estimation when  the  dependence
      on  etas  of the variance of intra-individual random error should
      be preserved in the computation of the  objective  function;  see
      the INTERACTION option (See $ESTIMATION).

Also  see  NONMEM  read-only  modules (of the form ROCMn), NONMEM-PRED
 modules (of the form NMPRDn), and PREDPP  read-only  modules  (of  the
 form PROCMn).

 REFERENCES: Guide IV, section V.C.6
 REFERENCES: Guide V, section 8
 REFERENCES: Guide VI, section IV

** INFN
#+begin_src f90
 USAGE:
 SUBROUTINE INFN (ICALL,THETA,DATREC,INDXS,NEWIND)
 USE SIZES, ONLY: ISIZE,DPSIZE
 USE NMPRD_INT, ONLY: NWIND
 INTEGER(KIND=ISIZE) :: ICALL,INDXS(*),NEWIND
 REAL(KIND=DPSIZE)   :: THETA(*),DATREC(*)
#+end_src
A  run  consists of one or more problems, and each problem consists of
one or more subproblems.  With NONMEM 75, there is an  opportunity  to
drop  data  records  from the NONMEM data set at the start of the run,
using the PRED_IGNORE_DATA feature.  There are opportunities  to  make
some  rudimentary computations at the beginning of a run (run
initialization), at the beginning of a problem (problem
initialization),  at the  end  of  a  subproblem (subproblem
finalization), at the end of a problem (problem finalization), and at
the end of a run (run finaliza- tion).   For  example, at problem
initialization, data transgeneration may take place, or a variable
that  will  be  modified  at  subproblem finalization,  may be
initialized.  At problem finalization, the value of this variable may
be written to a user file.  There is no  opportunity to do subproblem
initialization.

The  INFN  subroutine  is  called by PREDPP to make initialization and
finalization computations.  The version distributed with PREDPP  is  a
"stub"  or  "dummy" routine that does nothing. It may be replaced by a
user-written code.


Input/Output argument:

- ICALL

  + ICALL=-1: INFN may  set  PRED_IGNORE_DATA=1  for  records  to  be
    dropped.  The following is required:
    #+begin_src f90
        USE NMPRD_INT, ONLY: PRED_IGNORE_DATA,PRED_IGNORE_DATA_TEST
    #+end_src
    The  option $DATA ... PRED_IGNORE_DATA  is required to cause
    NONMEM to make a PRED_IGNORE_DATA  pass.

  + ICALL=0: INFN may now make computations for  run  initialization.
    ICALL may be reset by INFN to a number in the range 1-8999.  This
    number will appear on NONMEM output, allowing the user  to
    identify the INFN routine being used.

  + ICALL=1:  INFN  may now make computations for problem
    initialization.

  + ICALL=3: INFN may now make computations for problem finalization.
    If there are subproblems, first do  subproblem  finalization,  if
    required.   Then  test  for  IREP=NREP (the number of the current
    subproblem equals the total number of subproblems), and if  true,
    do problem finalization.  Values of IREP and NREP may be found in
    NONMEM modules (See Simulation: NREP,IREP).

INPUT ARGUMENTS:

- DATREC
       DATREC CONTAINS THE FIRST DATA RECORD  OF  THE  CURRENT  PROBLEM.
       (AT  ICALL=0,  THE  CURRENT PROBLEM IS THE FIRST PROBLEM.)  USING
       PASS (SEE BELOW), THE CONTENTS OF DATREC ARE  REPLACED  BY  OTHER
       DATA  RECORDS  FOR  THE CURRENT PROBLEM, ALLOWING ALL THESE OTHER
       RECORDS TO BE READ AND EVEN MODIFIED.

- THETA
       The NONMEM THETA vector.
       At ICALL=0, THETA contains the initial estimates  for  the  first
       problem.
       At  ICALL=1, THETA contains the initial estimates for the current
       problem.
       At ICALL=3, THETA contains the final estimates  for  the  current
       problem.

-   INDXS
       The  values specified in the $INDEX record of the NM-TRAN control
       stream.  (This is the NONMEM INDXS array starting at position 12,
       the first position beyond those positions used by PREDPP itself.)

-   NWIND
       NWIND has value 0 when INFN is called.  It changes value during a
       pass through the data using PASS (see below).
       NWIND=0: First record of the data set.
       NWIND=1: First record of a subsequent individual record.
       NWIND=2: Subsequent data record of an individual record.

EXAMPLES OF USAGE:

- Initialization: constants in the PK routine can be set if they are
  stored  in  a module or common block declared both in INFN and PK.


- Transgeneration: the  data can be accessed and even modified via use
  of the NONMEM utility routine PASS in routine INFN  (See pass).   As
  the  data records  are  passed one-by-one to INFN, each record is
  stored in turn in DATREC. Data can be transgenerated and additional
  data items can be  produced  at  both initialization and
  finalization.  Data items that appear in a table or scatterplot with
  a given subproblem or problem  are  produced or left unchanged at
  the subproblem or problem finalization. At finalization estimates of
  the eta's can be  obtained  via  the NONMEM  utility  routine
  GETETA.   When used in conjunction with PASS, the values returned
  for the eta's with each call to  GETETA are appropriate for the
  individual whose data record is currently in DATREC.


- Interpolation: as an  example  of  transgeneration,  interpolated
  values  of  a covariate  can  be computed for event records in which
  values are missing,  e.g.  for  other-type  event  records  that
  have  been included  so  that  predictions  can  be obtained at the
  times in these records. This could also be done in PK or ERROR,  but
  then this  would be done with every call to these routines; if done
  in INFN, the computation is done once only.

  (See Infn interpolation example).

  REFERENCES: Guide VI, section VI.A , Figure 37
** MODEL
#+begin_src f90
 USAGE:
 SUBROUTINE MODEL(IDNO,NCM,NPAR,IR,IATT,LINK)
 USE PRMOD_CHAR, ONLY: NAME
 USE SIZES,     ONLY: DPSIZE,ISIZE
 INTEGER(KIND=ISIZE) :: IDNO,NCM,NPAR,IR,IATT,LINK
 DIMENSION :: IATT(IR,*),LINK(IR,*)
#+end_src
GLOBAL DECLARATION:

Versions before NONMEM 7.4:

#+begin_src f90
 CHARACTER(LEN=8) :: NAME(PC)
#+end_src

Versions after NONMEM 7.4:

#+begin_src f90
 USE SIZES,     ONLY: SD
 CHARACTER(LEN=SD) :: NAME(PC)
#+end_src
The  MODEL  subroutine is called by PREDPP only once at the start of a run when a general ADVAN (ADVAN 5, 6, 7, 8, 9, 13, 14, 15, 16, 17, 18) is  used.   It  allows  the  user to specify aspects of the particular model he wishes to use.  When NM-TRAN is used, the $MODEL record  supplies this information.

Input argument: None.

Output argument:

-  IDNO
      An  identification  number  for  the  MODEL  routine.   The value
      assigned by MODEL to IDNO is printed on the first PREDPP  problem
      summary page.

-  NCM
      The total number of compartments in the model, excluding the out-
      put compartment.  Contains 0 when MODEL is called.  NCM  must  be
      no greater than PC-1.

-  NPAR
      The  number  of basic PK parameters used in the PK routine.  Con-
      tains 0 when MODEL is called.  NPAR must be no greater than  con-
      stant  PG  in  file  SIZES.   With  the general non-linear models
      (ADVAN6, ADVAN8,  ADVAN9,  ADVAN13,  ADVAN14,  ADVAN15,  ADVAN16,
      ADVAN17, ADVAN18), NPAR may remain 0.

-  IATT
      Values  of compartment attributes. The values of IATT(I,*) refers
      to the ith compartment.
       + IATT(I,1)=0  initially off
       + IATT(I,1)=1  initially on
       + IATT(I,2)=0  may not be turned on and off
       + IATT(I,2)=1  may be turned on and off
       + IATT(I,3)=0  may not receive doses
       + IATT(I,3)=1  may receive doses
       + IATT(I,4)=0  not the default observation compartment
       + IATT(I,4)=1  the default observation compartment
       + IATT(I,5)=0  not the default dose compartment
       + IATT(I,5)=1  the default dose compartment

      The remainder is used only with ADVAN9, ADVAN15, and ADVAN17:

       + IATT(I,8)=0  not an equilibrium compartment
       + IATT(I,8)=1  an equilibrium compartment
       + IATT(I,9)=0  should not be included in the total drug amount in the system interior
       + IATT(I,9)=1  should be included in the total drug amount in the system interior

-  NAME
      Labels for the compartments (to be printed on the PREDPP  summary
      page under "FUNCTION").
      NAME(I)  is  the  label  for compartment i.  With versions before
      NONMEM 7.4, NAME was limited to 8  characters.   With  NONMEM  74
      NAME may be up to SD characters long.  SD is defined in SIZES and
      is set to 30 with NONMEM 7.4.

-  LINK: Only used with a general linear model (ADVAN5 and ADVAN7).
    + LINK(I, J)=0: no drug may distribute from compartment i  to  compartment j.
    + LINK(I,  J)=K: drug distributes from compartment i to
      compartment j.  The rate constant quantifying this first  order
      distribution is computed by PK and stored in the kth row of GG.
      When MODEL is called, all elements of LINK are 0.

 (See sizes).

 An initial steady state may be requested by routine MODEL;
 (See Initial Steady State: I_SS,ISSMOD)
 (See i_ss, initial_condition).

 REFERENCES: Guide IV, section V.C.4
 REFERENCES: Guide VI, section VI.B , Figures 28, 29, 43
 REFERENCES: Guide VI, Appendix II

** PK
:PROPERTIES:
:CUSTOM_ID: PK
:END:
USAGE:
before NONMEM 7.2:
#+begin_src f90
  SUBROUTINE PK(ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,IRGG,GG,NETAS)
   USE SIZES,     ONLY: DPSIZE,ISIZE,LVR
   REAL(KIND=DPSIZE) :: EVTREC
   INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS,IRGG,NETAS
   DIMENSION :: IDEF(7,*),THETA(*),EVTREC(IREV,*),INDXS(*)
   DIMENSION :: GG(IRGG,LVR+1,*)
#+end_src

With NONMEM 7.2 and higer:
#+begin_src f90
   SUBROUTINE PK(ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,IRGG,GG,NETAS)
   USE SIZES,     ONLY: DPSIZE,ISIZE
   USE PRDIMS,    ONLY: GPKD
   IMPLICIT REAL(KIND=DPSIZE) (A-Z)
   REAL(KIND=DPSIZE) :: EVTREC
   INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS,IRGG,NETAS
   DIMENSION :: IDEF(7,*),THETA(*),EVTREC(IREV,*),INDXS(*)
   DIMENSION :: GG(IRGG,GPKD+1,*)
#+end_src

The  PK  subroutine is called by PREDPP to obtain values for basic and
additional pharmacokinetic parameters.  Basic PK parameters are
typically the rate constants ("micro-constants") for use in kinetic
formula.  PK can compute instead parameters such as clearance and
volume, and  a translator ("TRANS") subroutine can be used to convert
these to rate constants.  Additional PK parameters  include
compartment  scale parameters,  which  PREDPP uses to convert
compartment amounts to concentrations, and dose-related  parameters
such  as  modeled  infusion rates.

Input argument:
- ICALL: see ICALL.

- THETA: the NONMEM THETA vector.

- EVTREC: the PREDPP event record.

- INDXS: the  values specified in the $INDEX record of the NM-TRAN
  control stream.  (This is the NONMEM Index array starting at
  position 12, the first position beyond those positions used by
  PREDPP itself).

- NETAS: the number of population etas in the problem.

Output argument:

- IDEF: stores values only when ICALL=1. Values may be stored in the following elements:
  + IDEF(1,1)=-9  (required)
  + IDEF(1,2) is the call limiting element (compare $PK's CALLFL).
  Values are:
    + -2:  call  with every event record and at additional and lagged dose times.
    + -1: call with every event record (default)
    +  0: call with first event record and new TIME values
    +  1: call once per individual record

  Compartment initialization may be performed by routine PK.

  An initial steady state may be requested by routine PK;
      (See Initial Steady State: I_SS,ISSMOD)
      (See i_ss, initial_condition).
      The value in IDEF(1,3) describes whether PK performs  compartment
      initialization,  i.e.,  whether or not PK initializes elements of
      the initial state vector A_0(n).  Values are:
        -1: PK may initialize A_0.
         0: PK does not initialize A_0.
         1: PK does initialize A_0.
      The default used by PREDPP is IDEF(1,3)=-1.  However,  when  com-
      partment  initialization is not implemented, then if IDEF(1,3) is
      set to  0,  PREDPP  can  avoid  some  time-consuming  processing.
      Indeed,  when  $PK  abbreviated or verbatim code is supplied, and
      there is  no  reference  to  compartment  initialization  amounts
      A_0(n)  in  either the abbreviated or verbatim code, then NM-TRAN
      sets IDEF(1,3)=0.

      Compartment amounts may be used by routine PK;
      (See State Vector: A).
      The value in IDEF(1,4) describes whether PK uses  derivatives  of
      compartment amounts (e.g. compartment amounts themselves are used
      as random variables in arithmetic statements in PK).  Values are:
        -1: PK may use derivatives of compartment amounts.
         0: PK does not use derivatives of compartment amounts.
         1: PK uses derivatives of compartment amounts.
      The default used by PREDPP is IDEF(1,4)=-1.  However, when deriv-
      atives  of compartment amounts are not used, then if IDEF(1,4) is
      set to  0,  PREDPP  can  avoid  some  time-consuming  processing.
      Indeed,  when  $PK  abbreviated or verbatim code is supplied, and
      there is no reference to A(n) (as a random variable in an  arith-
      metic  statement)  in  the abbreviated code (or to derivatives of
      A(n) in the verbatim code), then NM-TRAN sets IDEF(1,4)=0.

      Remaining elements contain row numbers in GG:
      IDEF(2,1): row number of F0 (output fraction)
      IDEF(2,2): row number of XSCALE (Time Scale)
      IDEF(2,3): row number of lowest-numbered MTIME
      IDEF(2,4): row number of highest-numbered MTIME
      IDEF(3,n): row number of Sn (Scale for comp. n) (thru n+1 output)
      IDEF(4,n): row number of Fn (bioavailability fraction for comp. n)
      IDEF(5,n): row number of Rn (modeled rate for comp. n)
      IDEF(6,n): row number of Dn (modeled duration for comp. n)
      IDEF(7,n): row number of ALAGn (absorption lag for comp. n)

- GG  The array of PK parameters and their eta derivatives.  The  maxi-
      mum  number  of rows in GG is given by IRGG, which is the same as
      constant PG found in file SIZES (See sizes).
      At ICALL = 2:
      GG(k,1,1) contains the value of the kth parameter.
      GG(k,i+1,1) contains its derivative with respect to the ith eta.
      GG(k,i+1,j+1) contains its second derivative with respect to  the
      ith eta and the jth eta (lower-triangular; j=1, ..., i).  (Second
      derivatives are only needed  with  estimation  by  the  Laplacian
      method.)
      At ICALL = 4:
      GG(k,1,1)  contains  the  individual-specific  value  of  the kth
      parameter.  Other columns of GG need not be computed.

 Also see variables in NONMEM modules, NONMEM-PRED modules, and  PREDPP
 modules.
 (See variables in modules)

- REFERENCES: Guide IV, section V.C.5
- REFERENCES: Guide V, section 7
- REFERENCES: Guide VI, section III
** PRED
USAGE:

Versions before NONMEM 7.2:

#+begin_src f90
 SUBROUTINE PRED (ICALL,NEWIND,THETA,DATREC,INDXS,F,G,H)
 USE SIZES,     ONLY: DPSIZE,ISIZE,LVR
 REAL(KIND=DPSIZE) :: DATREC
 INTEGER(KIND=ISIZE) :: ICALL,NEWIND,INDXS
 DIMENSION :: THETA(*),DATREC(*),INDXS(*),G(LVR,*),H(LVR,*)

#+end_src
With NONMEM 7.2 and higher:

#+begin_src f90
 SUBROUTINE PRED (ICALL,NEWIND,THETA,DATREC,INDXS,F,G,H)
 USE SIZES, ONLY: DPSIZE,ISIZE
 USE PRDIMS,ONLY: GPRD,HPRD,GERD,HERD,GPKD
 IMPLICIT REAL(KIND=DPSIZE) (A-Z)
 REAL(KIND=DPSIZE) :: DATREC
 INTEGER(KIND=ISIZE) :: ICALL,NEWIND,INDXS
 REAL(KIND=DPSIZE) :: G(GPRD,*),H(HPRD,*)
 DIMENSION :: THETA(*),DATREC(*),INDXS(*)
#+end_src
The  PRED  subroutine  is  called  by NONMEM to obtain modeled values.
PREDPP is a special PRED subroutine that is distributed with NONMEM,
for common Population PK models.

Input argument:

- ICALL
  + ICALL=-1: the routine has been called for the  PRED_IGNORE_DATA
    feature  of  NONMEM  7.5.   One call per data record, at the start
    of the run.  These calls  occur  only  if  abbreviated  code  uses
    variables PRED_IGNORE_DATA or PRED_IGNORE_DATA _TEST, or if the
    PRED_IGNORE_DATA option of $DATA is used.  Otherwise, there are no
    calls to  PRED  with ICALL=-1.


  + ICALL=0:  PRED  has  been  called  for  initialization purposes at
    the beginning of the NONMEM run; one such call per run.   DATREC
    contains the  first  data  record.  THETA contains the initial
    estimates.  PRED need not compute F, G, or H.


  + ICALL=1: PRED has been  called  for  initialization  purposes  at
    the beginning  of a NONMEM problem; one such call per problem.
    Otherwise, identical to ICALL=0.


  + ICALL=2: For the data record contained in DATREC, PRED has been
    called for  the  purpose  of computing F, the value of the
    prediction, and/or the values of other PRED-defined items,
    appropriate  for  the  record. PRED  should  compute  F, and also
    G and H as appropriate.  THETA contains the values to be used to
    compute F.   With  conditional  estimation, to obtain ETA values,
    PRED should call GETETA.


   + ICALL=3:  PRED has been called for finalization purposes at the
     end of a NONMEM problem; one such call per (sub)problem.  DATEC
     contains  the first  data  record.   THETA contains the final
     estimates.  Otherwise, identical to ICALL=0.


   + ICALL=4: For the data record contained in DATREC, PRED has been
     called during the Simulation Step for the purpose of computing a
     value of the dependent variable and, possibly,  values  of
     independent  variables, appropriate  for  the record.  PRED
     should compute F (the value of the dependent variable).  THETA
     contains the initial estimates, which  are the  values  to  be
     used  to compute F.  PRED should call SIMETA (and SIMEPS) to
     obtain simulated values of ETA (and EPS).


    + ICALL=5: For the data record contained in DATREC, PRED has been
      called for the purpose of computing the expectation of the PRED
      item and possibly, the expectations of other PRED-defined items,
      appropriate  for the  record.  Such a call occurs when the
      marginal data item (MRG_) is defined in the data set and has a
      non-zero value for the  data  record in  question.   If the MRG_
      data item on the record has the value 1 or 2, the value returned
      by PRED in F contributes to the  expectation  of the  PRED
      item.  Similarly, the values returned in other PRED-defined
      items contribute to expectations of these items.  THETA
      contains  the final  estimates.  The expectations in question
      are over possible values of ETA, and to obtain ETA values, PRED
      should call GETETA.
    + ICALL=6:  PRED has been called for the purpose of  computing
      the  raw data average of the DV data items and, possibly, the
      raw data averages of PRED-defined items.  Such a call occurs
      when the raw-data data item (RAW_)  is defined in the data set
      and has a non-zero value for a template data record (See
      template).  The value of the DV  data  item  in the  data
      record contained in DATREC will be included in the raw data
      average of the DV data items.  However, when the raw data
      average corresponding  to the label DV in a table or scatterplot
      is to be different from the raw data average of the DV  items
      themselves,  PRED  may recompute  the value of DV.  PRED may
      return a value of 1 in F to omit the DV item in the data record
      from the average.

- NEWIND
   + NEWIND=0: First record of the data set.  THETA value  may  differ from value at last call with this record.
   + NEWIND=1: First record of the data set, THETA value does not
     differ from value at last call with this record, and PRED is
     nonrecursive (see I_REC), or, First record of a subsequent
     individual record.
   + NEWIND=2: Subsequent data record of an individual record.

- THETA: the NONMEM THETA vector.

- DATREC
      The current data record.

- INDXS
      The  values specified in the $INDEX record of the NM-TRAN control
      stream.

Output argument:

- F   When ICALL=2, the prediction associated  with  the  data  record.
      With  odd-type  data,  the  likelihood  of the observation in the
      record, but if there is no observation, F is ignored.

      When ICALL=4, the value of the simulated  observation  associated
      with  the  data record.  Alternatively, F can be ignored, and the
      DV item in the data record can be directly set to  the  value  of
      the  simulated  observation.   With  odd-type data, F is ignored;
      PRED should directly set the DV item to the value  of  the  simu-
      lated observation.

- G   An array of derivatives of F with respect to etas.  Values should
      be set when ICALL=2.
      G(i,1) is the partial derivative of F with respect to eta(i).
      When the data are population, G(i,j+1) is the second partial  de-
      rivative  of  F with respect to eta(i), eta(j) (lower-triangular;
      j=1,..., i).
      Second derivatives are needed only when the Laplacian  method  is
      used to estimate parameters.

- H   An  array  of  partial derivatives of F with respect to epsilons.
      When the data are population, values should be set when ICALL=2.
      H(i,1) is the derivative of F with respect to eps(i).
      H(i,j+1) is the partial derivative  of  H(i,1)  with  respect  to
      eta(j)
      These  mixed second derivatives are needed only when the INTERAC-
      TION option  is used to estimate parameters.  (See $ESTIMATION).

 Also see variables in NONMEM modules, NONMEM-PRED modules, and  PREDPP
 modules.
 (See variables in modules)

 REFERENCES: Guide I, section C.2

 REFERENCES: Guide IV, section III.B.8 , IV

 REFERENCES: Guide V, section 12.3

** TRANS
#+begin_src f90
 USAGE:
 SUBROUTINE TRANS (ITRANS,IRGG,GG,NETAS)
 USE SIZES, ONLY: ISIZE,DPSIZE,LVR
 INTEGER(KIND=ISIZE) :: IRGG,NPETAS,ITRANS
 REAL(KIND=DPSIZE)   :: GG(IRGG,LVR+1,LVR+1)
#+end_src
The  TRANS  subroutine translates (or transforms) the values for a set
of basic PK parameters modeled in PK to a set of values for the inter
nal parameters required by the ADVAN.  The PREDPP Library has a number
of TRANS subroutines, representing  different  possible
parameterizations  in PK, from which the user may choose. If a
suitable translator is not found in the Library, the user may write
his own.

Input/Output argument:

- ITRANS
  + ITRANS=1: TRANS has been called for initialization at the
    beginning of a NONMEM problem; one such call per problem.  ITRANS
    must be reset by TRANS to a number in the range 1-8999.   This
    number appears on NONMEM output, allowing the user to identify the
    TRANS routine being used.

  + ITRANS=2: On input the GG array has stored in it the values
    computed  by  PK  (except  that were any PK parameter modeled in
    its logarithm form in PK, PREDPP would have already exponentiated
    its typical/subject-specific value and multiplied its eta
    derivatives by its exponentiated typical/subject-specific value).
    On  output the  GG  array  should have stored in it the values
    that would be computed by PK were the internal parameters of the
    ADVAN  modeled directly in PK (and none in their logarithmic
    form).

  + ITRANS=4: TRANS has been called during the Simulation Step.  Only
    the first column of  the  GG  array  need  be  computed  as  with
    ITRANS=2.  Other columns need not be computed.


  + GG:  the array of PK parameters and their eta derivatives. The
    array is described elsewhere; (See PK).


Input argument:

- NETAS: the number of population ETAs in the problem.

Certain variables are available in modules.  Their use is optional.

- Variables in read/write modules: IERPRD NETEXT ETEXT (See PRED Exit
  Code). (See PRED Error Message).
- Variables in read-only commons: NOETAS, SECOND (See Partial
  Derivative Indicators). When  SECOND  is  true,  PREDPP requires
  second-partial derivatives of etas.

REFERENCES: Guide VI, section III.M


** TOL
USAGE:

Versions before NONMEM 7.4:

#+begin_src f90
SUBROUTINE TOL(NRD)
USE SIZES,     ONLY: ISIZE
INTEGER(KIND=ISIZE) :: NRD
DIMENSION :: NRD(*)
#+end_src
With NONMEM 7.4:

#+begin_src f90
 SUBROUTINE TOL(NRD,ANRD,NRDC,ANRDC)
 USE SIZES,     ONLY: ISIZE
 INTEGER(KIND=ISIZE) :: NRD(0:*), ANRD(0:*), NRDC(0:*), ANRDC(0:*)
#+end_src
Optional declarations with NONMEM 7.4:

#+begin_src f90
 USE NMPRD_INT, ONLY: IPROB
 USE NM_BAYES_INT, ONLY: NM_STEP,BASE_STEP,EST_STEP,COV_STEP, &
  TABLE_STEP,SIML_STEP,INE_STEP, NONP_STEP
#+end_src

The TOL subroutine is called by PREDPP when ADVAN 6, 8, 9, 10, 13, 14,
15, 16, 17, or 18 is used.  It is also called when SS6 or SS9 is used.
With  NONMEM  7.4,  there  are multiple calls during the run, for each
NONMEM step.  With earlier version, TOL is called  only  once  at  the
start of a run.

Output argument:

- NRD(I): The number of digits that are required to be accurate in the
  computation of the drug amount in compartment I, i.e., the  relative
  tolerance.   ADVAN  9,  13, 16, 17, and 18 have the capability of
  using different values of NRD for different compartments (ADVAN 14
  and 15  only  allow  different  absolute tolerances for each
  compartment).  For compartments not specified, the tolerance of the
  last compartment specified will be used.

  However, all the other ADVAN routines requiring TOL take the
  relative tolerance to be the same for all compartments; NRD(I), I >
  1,  is ignored, and only NRD(1) is used.  With NONMEM 7.4, NRD(0) is
  the relative tolerance for the Steady State computations.   If
  NRD(0) is not specified, NRD(1) is used.

  The  value  of  NRD(1)  can  also be specified using $SUBROUTINES
  option TOL. The value of NRD(0) can  also  be  specified  using
  $SUBROUTINES option SSTOL.


- ANRD(I) (NM74): the  absolute  tolerance in the computation of the
  drug amount in compartment  I.   The  default  is  12  (that  is,
  accuracy   is 10**(-12)).   Used  by ADVAN 9, 13, 14, 15, 16, 17,
  and 18, which have the capability of using different values of ANRD
  for different compartments.   For  compartments  not  specified,
  the tolerance of the last compartment specified will be used.


  ANRD(0) is the absolute tolerance for the Steady  State
  computations.  If ANRD(0) is not specified, ANRD(1) is used. The
  value  of  ANRD(1)  can also be specified using $SUBROUTINES option
  ATOL. The value of ANRD(0) can also  be  specified  using
  $SUBROUTINES option SSATOL.


- NRDC(I) (NM74): same  as  NRD(I),  but used for the FOCE/LAPLACE
  covariance step. Used with ADVAN 9, 13, 14, and 15, 16, 17, and 18.
  If  not  set, NRDC  defaults  to  the value of NRD.  NRDC(0) is used
  for Steady State computations during the FOCE/LAPLACE covariance
  step.

  The value of NRDC(1) can also  be  specified  using  $SUBROUTINES
  option TOLC. The  value  of  NRDC(0)  can also be specified using
  $SUBROUTINES option SSTOLC.


- ANRDC(I) (NM74): Same as ANRD(I), but used for the FOCE/LAPLACE
  covariance  step. Used  with  ADVAN 9, 13, 14, and 15, 16, 17,
  and 18.  If not set, ANRDC defaults to the value of ANRD.  ANRDC(0)
  is used for Steady State computations during the FOCE/LAPLACE
  covariance step.

  The  value  of  ANRDC(1) can also be specified using $SUBROUTINES
  option ATOLC. The value of ANRDC(0) can also be  specified  using
  $SUBROUTINES option SSATOLC.


When  NM-TRAN  is used, this information may be supplied by either the
TOL option of the $SUBROUTINES record or the $TOL record.

One may supply a TOL routine that assigns values of  NRD  and ANRD
specifically for the initial (base) setting and each NONMEM step
(estimation, covariance, simulation, table/scatter  step,  simulation,
initial  parameters  estimate,  nonparametric).  For example, create a
toluser.f90 file,

#+begin_src f90
  SUBROUTINE TOL(NRD,ANRD,NRDC,ANRDC)
    USE NMPRD_INT, ONLY: IPROB
    USE NM_BAYES_INT, ONLY: NM_STEP,BASE_STEP,EST_STEP,COV_STEP, &
         TABLE_STEP,SIML_STEP,INE_STEP, NONP_STEP
    IMPLICIT NONE
    INTEGER :: NRD(0:*), ANRD(0:*), NRDC(0:*), ANRDC(0:*)
    IF(NM_STEP==EST_STEP) THEN
       NRD(1)=6
       ANRD(1)=10
    ELSE IF (NM_STEP==COV_STEP) THEN
       NRD(1)=7
       ANRD(1)=8
    ELSE IF (NM_STEP==TABLE_STEP) THEN
       NRD(1)=8
       ANRD(1)=7
    ELSE
       NRD(1)=9
       ANRD(1)=12
    ENDIF
    IF(IPROB>1) THEN
       NRD(1)=NRD(1)+1
       ANRD(1)=ANRD(1)+1
    ENDIF
    RETURN
  END SUBROUTINE TOL
#+end_src
and incorporate it using $SUBR
#+begin_src php
 $SUBROUTINES ADVAN13 TRANS1 TOL=toluser.f90
#+end_src

REFERENCES: Guide IV, section V.C.4

REFERENCES: Guide VI, section VI.D , Figure 41

REFERENCES: Guide VI, Appendix II

** Verbatim code
USAGE:
#+begin_src php
"      verbatim line
#+end_src

Verbatim  code is Fortran code within a block of abbreviated code that
is to be copied by NM-TRAN to the generated Fortran subroutine.  It is
not  itself regarded as abbreviated code.  Such code is marked by
having the character " as  the  first  non-blank  character.   The  "
is dropped  and  the  characters to the right are copied as-is to
columns 1-72 of the generated subroutine.  Lines of verbatim code can
include any  Fortran  statements: comment, declaration (e.g., INTEGER,
COMMON, USE), I/O, CALL, assignment, continuation, DO,  GOTO,  etc.).
Lower- case  characters  can  be used freely, if the FORTRAN compiler
permits them.

NM-TRAN makes some modifications to verbatim code:

- Placement: the verbatim code is adjusted as necessary to conform to
  FORTRAN column  conventions.  Alphabetic text that follows the
  initial ", or that follows a statement number, is  moved  to  column
  7,  as required by FORTRAN.

- Comment lines: If  the  character  that  immediately follows the
  initial " is !, this conforms to the FORTRAN 90 syntax for  comment
  lines.   The line is copied unchanged.  If the character that
  immediately follows the initial " is C or c or " or *, this conforms
  to the FORTRAN  77 syntax for comment lines.  The line is copied
  unchanged, but C or c or " or * is replaced by !.

- Continuation lines: Fortran 77 continuation lines (non-blank in
  position 6)  are  not permitted  with  NONMEM  7.   Instead,  the
  line to be continued should end with character &.  Example:
  #+begin_src f90
     "      X=A &
     "      +D/E
  #+end_src

- Replacement Rule: in $PK, $ERROR, $DES, $AES, $INFN, and $PRED, in a
  line of abbreviated  code  labels  of items in the data record are
  replaced by direct references to the data record  itself  (either
  DATREC  or EVTREC,  as  appropriate).   Thus,  for  example, if such
  a label occurs as the left-hand side of  an  assignment  statement,
  then without this rule, when the statement is executed, the value of
  a local variable having the label is  modified,  whereas  with  the
  rule, an item in the data record is modified.


The  character  @,  immediately  before  a  label,  can  be used as an
"escape" to prevent the label from being replaced.  If the character @
immediately  follows the initial ", none of the labels occuring in the
line are replaced.

Labels occurring in common statements or as subroutine  arguments  are never replaced.

Tab  characters (and other characters that are smaller than blank in
the computer's collating sequence, such as carriage return ^M) are
permitted  in  verbatim  code.  With NONMEM 7, the last non-blank
character on the line is replaced by a space  if  it  is  a low-value
character.  This permits DOS-type line endings ^M.

By  default, all verbatim code goes in the main section of code and is
called MAIN verbatim code.  (The main section follows declarations and
initial  executable  code  inserted by NM-TRAN.)  Within the main
section, verbatim and abbreviated code may be freely mixed.  Each line
of verbatim  code is positioned in the generated code after all code
generated from the preceding line of  abbreviated  code.   The  user
may explicitly specify a different location as follows.

- FIRST verbatim code
      Verbatim  lines  which  must  be positioned immediately after the
      declarations which are part of the normal subroutine header,  and
      prior  to  the FIRST executable statement of the subroutine, must
      precede the first line of abbreviated code and  must  start  with
      the line "FIRST.

- MAIN verbatim code
      FIRST  verbatim  code is normally terminated by the first line of
      abbreviated code.  If there is both FIRST and MAIN verbatim code,
      and/or  the main section is to start with verbatim code, the line
      "MAIN may be used to separate the FIRST and MAIN verbatim code.

- LAST verbatim code
      Verbatim lines which are to immediately precede the RETURN state-
      ment  from  the generated subroutine must follow the last line of
      abbreviated code and must be preceded by the line "LAST.

      Example:
      #+begin_src php
       $ERROR
       Y=F*(1+ERR(1))
       "LAST
       " PRINT *,HH(1,1)
      #+end_src

      This displays values after they have been  assigned,  immediately
      prior to the return.

If  any  lines  of verbatim code are present in a block of abbreviated
code, NM-TRAN generates USE statements  appropriate  to  the  kind  of
abbreviated code and allows variables undefined in abbreviated code to
be used as right-hand quantities in abbreviated code.

REFERENCES: Guide IV, section IV.I
