---
title: "Data and model"
author: "Yi Zhang"
draft: false
bookCollapseSection: true
weight: 14
---

* Data and model
In this part we go through NONMEM's data and model specification, as
well as interpret sample outputs, using NM-TRAN (NONMEM
TRANslator) syntax, a (standalone) NONMEM component for input parsing.
Almost all modern NONMEM models are specified using NM-TRAN.

NM-TRAN takes its input from two files:
- NM-TRAN control stream,
- NM-TRAN data set.
and creates three things: a /NONMEM data set/, a /NONMEM control
stream/ [fn:1], and necessary subroutines. For example, it uses the data file input and creates NONMEM data file FDATA
[fn:2]. The table below lists some files that NM-TRNA generates.

| FILE    | Content                        | Usage            |
|---------+--------------------------------+------------------|
| FDATA   | NONMEM data set                | NONMEM input     |
| FCON    | NONMEM control stream          | NONMEM input     |
| FSUBS   | generated and user subroutines | build executible |
| FSTREAM | NONMEM file stream             | NONMEM input     |
| FREPORT | report file                    | Informational    |

See [[file:/docs/reference-manual/files/][Reference manual]] for additional files and details.

Usinig the files created by NM-TRAN, NONMEM fits the model and
generates a number of output files.

If an Model Specification File (MSF) is output, and intermediate output with iteration summaries
is requested (i.e., $ESTIM options MSFI and PRINT are used), then
NONMEM also writes the parameter estimates of these summaries to
the console and to file INTER, which now exists after the run
terminates.  INTER now include lines giving the parameter  estimates
in their natural unscaled space  (NPARAMETR) as well as the UCP
values (PARAMETER).

NM-TRAN also supports NONMEM's pre-built population PK models (PREDPP) by generating its
subroutines. It also handles additional model inputs such mixture
models (MIX) and Bayesian inference (PRIOR and BAYES). We will cover
PREDPP in the next part.

[fn:1] Before NM-TRAN was developed NONMEM requires input files in a
less intuitive fashion. These files consist "NONMEM control stream". Nowadays almost all NONMEM models are based on input
files using NM-TRAN. Therefore in this document unless specified we
use "NM-TRAN control stream" and "NONMEM control stream"
interchangeably, to mean input files based on NM-TRAN syntax. See next
section and [[file:/docs/reference-manual/files/#nm_control_stream][Reference manual]] for details of the old NONMEM control input files.

[fn:2] With NONMEM 7.5, an additional file, FDATA.csv is produced that
outputs the contents of its input data file (typically FDATA) in a
comma delimited file format, so you can check how NONMEM interprets
the input data. The records in FDATA.csv may differ from those in
FDATA in the following cases. If REPL/REPL_ is used, the replicated
form of the data will appear in FDATA.csv.
