#+title: 2. Data
{{< katex >}}{{< /katex >}}

* Data and event records
Data are specified for NONMEM using /event records/ [fn:1].
They represent temporal events such as dose events,
observation events, and others such as the beginning
of a urine collection and a measured change in kidney function.
Data records (rows in the data file)
correspond to different events, and must be in the order of time.

Data records also represent individuals, by grouping an individual's records in contiguous
records with a same /ID/. We refer to such a group an /individual record/.
Data records in an individual record must be ordered in time.

In the case of single subject data set, the records do not necessarily correspond on a one-to-one basis to either
animal or human subjects: an individual record is simply any group of
contiguous data records containing only one observation record and
having the same ID data item. (Although, the presence of a
multivariate observation means the individual record containing it has
several observation records, each containing one element of the
observation). In this case the time ordering of data records refers to
the time ordering of data records /across all/ records.

A typical NONMEM data set is like this (the first 9 /records/):
#+begin_src dat
 ID      TIME    C1      C2  ...  CN      DV     MDV
  1       1.     .5      10        5              1
  1       3.              9       10              1
  1       6.              6              4.1      0
  1       7.              7       10              1
  1      10.              7              5.3      0
  2       2.     .9       8        8              1
  2       2.5             6                       1
  2       6.              7                       1
  2       7.              8              6.4      0
#+end_src

This data set there are nince data records corresponding
to two individual records: five events for individual with ID=1,
and four for individual with ID=2.  Three of these events are observation
events, with DV (stands for "dependent value") provided.
Label ID and DV are reserved /data items/, the same for TIME and MDV,
for event time,  and missing dependent value, respectively.
Label C1, C2, ..., CN are concomitant variable data items for
additional event specification (such as EVID, see below) as well as covariates. Null (blank) entries are read in as zeros. They can also be explicitly put in as "." (dot) and "0".

Now we discuss reserved data items.

** Event identification: =EVID=
Every event record must have =EVID=.
This data item identifies the type of event.
- =EVID=0=: observation event. in the event the DV data item is an
  observation, and the MDV=0.  When =EVID!=0= DV data item can be any
  value or blank, and the MDV=1.
- =EVID=1=: dose event. There are three types of doses: bolus dose,
  infusion of finite duration and continuous constant rate infusion
  (effectively of infinite duration and leading to steady-state, thus
  also called steady -state infusion). Repetitions of doses of the
  first two types can also lead to steady-state (see SS data item).  A
  dose event corresponds to either the time a bolus dose is given, or
  the time an infusion is initiated, or the time a steady-state
  infusion terminates. With a dose event certain other data items
  which define the event further may also appear in the event record.
- =EVID=2=: neither an observation nor dose event. The event is
  referred to as of /other-type/. Examples include the time a urine
  collection begins/ends and the time a change in a covariable (such
  as glomelular filtration rate) is noted.
- =EVID=3=: reset event. With a reset event the kinetic system is
  reinitialized.  time is reset to the TIME data item, the amounts in
  each compartment are reset to zero, and the on/off status of each
  compartment is reset to its initial status.
- =EVID=4=: reset-dose event. It combines a dose event and a reset
  event: The system is first reset, and then a dose is given according
  to the information given in those fields giving dose information.

** The Time: =TIME=
Every event record must have =TIME= [fn:2].
The data item gives the time of the event.

Unless in reset and reset-dose events where time is reset, event records must be ordered (within an individual record) in time. Namely,
\(t_A\le t_B\) when event record A is followed by event record B.

=TIME= is unitless. It may contain clock time, hh:mm, and =DATE= data
item may also be present. They are converted to relative time internally.
In addition, one can use the TRANSLATE=(TIME/f/d) option of $DATA record
to request that TIME values be divided by f (typically, f is 24 to
convert hours to days, with d significant digits.

In NONMEM v7.4+, time data items may have any value, including negative values
(earlier versions mandate non-negative values) [fn:3].

** Dose Amount: =AMT=
In a dose event =AMT= gives the amount of a bolus
dose or of an infusion of finite duration. In those cases it must be
positive.  However, if other data items in a dose event
record (see below) indicate that the event record marks the termination of a
steady-state infusion, then if given =AMT= must be 0.
If all doses are steady-state infusions, =AMT= can be omitted.

In observation, other-type, and reset event records if given =AMT= must be 0 .
In a reset-dose event record the =AMT= data item should satisfy the requirements
of the =AMT= data item in a dose event record.

** Dose Rate: =RATE=
In a dose record the RATE data item can have values
- =RATE>0=: an infusion rate.
- =RATE=0=: instantaneous bolus dose.
- =RATE=-1=: the dose is either a zero-order bolus dose (see section
  III.F.3) with rate modeled in PK (see section III.F.4) or a
  rate-modeled steady-state infusion (see section III.F.5).
- =RATE=-2=: a zero-order bolus dose and that its duration is modeled
  in PK (see section III.F.3).  In this case a positive =AMT=  must be
  specified.

=RATE= must be 0 in observation, other-type, and reset
event records.
In a reset-dose event record the RATE data item should satisfy the requirements
of the RATE data item in a dose event record.

=RATE= can be omitted if all doses are bolus.


** Steady State: =SS=
It is helpful to review the background of steady-state kinetics [fn:4].

*** ackground
Steady state is an idealized state in a kinetic system. In a model we
can achieve steady states with one of the following approaches.
**** Dose cycles
Administering a sequence of doses in a regular cyclic fashion over a
  sufficiently long time. Each cycle of these /dose cycles/ share same
  doses, though they may consist of a mixture of bolus doses and
  infusions of finite duration. For example, a dose cycle may consist
  of an instantaneous bolus dose of 10mg, immediately followed by a 30
  minute infusion of 10mg. This cycle is then repeated every 4 hours.
  In other words, /the period of the cycle/ \(T\), is 4 hours in this
  example.

Let the dose times of the first cycle be \(t_1\le t_2\le
  \dots \le t_n\). The above approach is to administor the same doses at
  \(t_1+T, t_2+T, \dots, t_n+T\), then at \(t_1+2T, t_2+2T, \dots,
  t_n+2T\), etc. The system is at steady state if for any \(t\) in
  interval \([t_1, t_1+T)\)  the drug amounts in the compartments \(A(t)\)
  equal to \(A(t+T)\), the amounts at \(t+T\).

**** Steady-state infusions
If a large enough number of dose cycles have occurred,
the user might consider that an (approximate) steady-state
has been reached by the time when the last cycle begins.
This last dose cycle is called the
/steady-state cycle/.
The doses in this cycle are called
/steady-state doses/.

Therefore we can use a number of simultaneous
  steady-state infusions to achive steady state. Consider two such infusions schemes. The first one terminates at time
  \(t_1\le t_2\le \dots \le t_n\), and \(A(t)\) is the drug amount in
  the system at time \(t\). The second one terminates at
  \(t_1+\Delta\le t_2+\Delta\le \dots \le t_n+\Delta\), with \(B(t)\)
  the drug amount at time \(t\). Then the
  system is at steady state if there exists a \(\Delta\) such that
  \(A(t)=B(t+\Delta)\), for any \(t\)  in \((t_1, t_n)\).

One can use a regular cyclic dosage pattern in
conjunction with simultaneous steady-state infusions.

**** Steady-state dose records
Intead of specifying a repeated number of dose event records, we use
a special record for the last dose cycle (for steady-state infusions
only records for the terminations are required, as shown above). These records
are called
/steady-state dose records/.
They describe the administration of a sequence of same doses at a
regular interval such that the system ends with steady state.
This sequence of doses are called the /implied doses/, and we can imagine
they have been administored since forever. In other words,
the /implied dose times/ started at \(t=-\infty\).

**** Steady state for linear systems
**** =SS= data item

** Interdose interval: =II=
- If some steady-state dose event record has a positive =AMT= data item, then the =II= must be specified.
- If some non-steady-state dose event record has a positive =ADDL= data item, =II= must be specified.

=II= can be 0 or positive. For repeated doses =II= specifies the period.

=II= must be 0 in steady-state infusion. observation, other-type, and reset event
records.
In a reset-dose event record =II= should satisfy the requirements of =II= in a dose event record.

Similar to =TIME=, =II= is unitless. It may contain clock time, hh:mm, and =DATE= data
item may also be present. They are converted to relative time internally.
In addition, one can use the TRANSLATE=(TIME/f/d) option of $DATA record
to request that =II= values be divided by f (typically, f is 24 to
convert hours to days, with d significant digits.

** Compartment: =CMT=
The /observation compartment/ of a record contains the prediction for
an observation. It can be either a scaled drug amount
(see section III.F.1) or a modification of this quantity (see section IV.B.2).
Every dose event is associated with a /dose compartment/
(see section III.F.2).  A kinetic model has default designation for
these compartments, called
/default observation compartment/ and
/default dose compartment/, respectively.
Some kinetic models have the defaults built into the model definition,
some can be user-specified (see $MODEL record, and section VI.B).
Hereon unless otherwise specified by observation/dose compartment we
we their defaults.

*** On/Off of compartments
Some compartments can be switched on or off at event record times.
When off, a compartment contains no drug; when on, drug distributes
according to the kinetic model. For example, an output compartment may
be turned on at the start of urine collection, or a depot compartment
turned off once negligible drug remains to avoid unnecessary
computation.

Each compartment has an initial on/off status at the start of an
individual record and retains that status until explicitly changed. In
single-subject datasets, “individual record” refers to the entire
dataset (see Section IV.A). Only specific compartments in a kinetic
model can be switched, and both switchable compartments and their
initial statuses are defined—either built into the model or set by the
user in subroutine MODEL (see Section VI.B).

A dose event turns on the dose compartment at dosing time if not
already active. During an observation event, the observation
compartment must be either the default one (always on) or a
compartment currently on.

If drug would normally move from compartment A to B, turning off B
implies turning off A. In that case the drug amount either enters the
output compartment (if on) or is lost from the system.

*** =CMT= data item
The optional =CMT= data item specifies the relevant compartment for a record:
- for an observation record, it specifies the observation compartment;
- for a dose record, it specifies the dose compartment;
- it turns a compartment on/off at the event time: a positive
  compartment number means ON, negative means OFF.

For observation/dose(reset-dose) compartment for an observation/dose record.
Not given or =CMT=0= implies the use of default compartments.

If all one wants to accomplish at a certain time is to turn a
compartment on (e.g. the output compartment, in order to begin a urine
collection), then one should construct an /other-type/ event record
that simply turns the compartment on, by
giving the compartment number in =CMT=.

To turn a compartment off at a given time, one should construct
an other-type event record that gives the negative value of the compartment
number. This also applies to an observation record, provided the observation compartment is
the output compartment or an /output-type/ compartment. In this case the compartment
must be on at the event time, but it is turned off "immediately
thereafter".  Thus one can record the observation of a urine concentration
in an event record and conveniently turn off the urine collection
using the same record [fn:5]. An output-type  compartment is initally
off, may be turned on and off, and may not receive a dose. It must be
turned on with an other-type event record in order start accumulating
drug.

With a reset or reset-dose event record the on/off status of each
compartment is reset to its initial status, and then if the
compartment data item is nonzero, the designated compartment is turned
on or off according to whether the data item is positive or negative (it must
be plus with a reset-dose event record).

** Prediction Compartment: =PCMT=
NONMEM computes a prediction for each
data record, regardless if it contains an observation: one can use other-type event records
at times of interest, and output the predition in tables.
- Data records with =CONT=1= are ignored thus the prediction is 0.
- For the last data record of an observation event record, the
  prediction is always either the scaled drug amount in the
  observation compartment (see section III.F.1), or a modification of
  this quantity (see section IV.B.2).
- For the last data record of a non-observation record, the prediction is
the prediction that would result for an observation of the default observation
compartment (see section H), unless otherwise specified using =PCMT=.

The optional =PCMT= data item specifies the compartment number for the prediction for the last
data record of the event record.  Thus predictions for
different compartments can be displayed.
Not given or =PCMT=0= in a non-observation event record implies
the prediction for the last data record of the event record
is the prediction that would result for an observation of
the default observation compartment.

By convention, the number of the output
compartment may also be given by the PCMT data item as the number 1000
(this is true regardless of the type of the event record).
With small models (number of compartments <= 99), this number may also be given as 100.

** =CALL=
The PK and ERROR subroutines need not be called with every event record
(see sections III.H and IV.C).  When /call-limiting protocals/, calling-protocols limiting calls to PK or
ERROR, are used, =CALL= data item can be used to overwrite and force a
call to PK and/or ERROR.
This can be used, for example, to selectively do PK calculations when
some individuals' PK parameters are covariates dependent while the
rest of the population's are not.

The optional =CALL= data item can assume the following values.
If it appears it has the values 0, 1, 2, 3, or 10.
- =CALL=0=: in an event record, then calls to PK and ERROR with the record occur according to the calling-protocols implemented with PK and ERROR.
- =CALL=1=: a call to PK is determined according to the calling-protocol implemented with PK, and a call to ERROR occurs.
- =CALL=2=: a call to ERROR is determined according to the calling-protocol implemented with ERROR, and a call to PK occurs.
- =CALL=3=: calls to both ERROR and PK occur.
- =CALL=10=: with ADVAN9, ADVAN15, and ADVAN17, a call to ADVAN occurs
  whether  or  not the TIME data item is defined, and whether or not
  AES has used IDEFA(2) to limit calls to the ADVAN routine (See
  Chapter VI, Section E.B). May be combined with values 1, 2, and 3.
  e.g., CALL = 11 forces calls to  both  ADVAN  and  ERROR with the
  event record.

** Additional doses: =ADDL=
Instead of specifying a series of records for identical doses, user
can use =ADDL= on a single dose event record. The dose specified on the dose event record is called the
/initiating dose/, so that
- =ADDL=0= means only the initiating dose in the record is administored;
- =ADDL=n= for a positive =n= means =n= doses, /additional/ to the
  initiating dose, are administored. In that case one must use
  =II= to specify the constant interdose interval

If the initiating dose is lagged, the additional doses are also lagged
(see section III.F.6).
The term
.US additional dose time
refers either to the time an
additional dose is given, if the dose is not lagged, or to the lagged time
at which the dose actually enters the system, if the dose is lagged.
Such a time is a nonevent dose time (see section III.B.2).
At each additional dose time a dose like the initiating dose
automatically enters the system.
Until such a time as all the additional doses have entered, or until the last
event time in an individual record is attained, whichever comes first, the
dose record initiating the dose series is said to be
.US active
\&.
Afterwards, the record is said to be
.US inactive
\&.
(The additional dose data item can also be used when all the data are from a
single subject, and then the term 'last event time in an individual record'
should be understood to mean the last event time in the data set.
This is a consequence of the single-subject assumption; see section IV.A.)\0
There can be at most 10 active dose event records at a time.

Note that
- The administration of an additional dose will not be expressed explicitly in a NONMEM table or scatterplot;
- The ADDL data item must be 0 when the initiating dose is a steady-state
infusion.
However, the ADDL data item can be nonzero when the initiating dose is
any other type of steady-state dose.  In this case, after the steady-state dose,
an additional number of (transient) doses just like the steady-state dose are
given.  (Recall that the steady-state dose is just the last of many
doses identical to it and \fIleading\fP to a steady-state.)\0
On the other hand, any steady-state dose event record with SS data item
equal to 1 will deactivate
any previous dose event record which happens to be active.
Also, a reset and a reset-dose event record will deactivate any previous
dose event record which happens to be active.
Also, if a compartment is turned off with an other-type event record
(see section H), this deactivates any previous dose event record with a
dose to this compartment which happens to be active.
- If given, =ADDL= must be 0 in observation, other-type, and reset event records.

See also reserved variables  \fBADDL_ACTUAL,ADDL_TIMEDIFF,ADDL_TIME\fP
in Chapter III.

[fn:1] Strictly speaking, the event records feature is part of PREDPP,
and NM-TRAN allows a more general format (discussed in Part 4).
Essentially all modern NONMEM applications use event records for data specification.
[fn:2] An example is when ADVAN9, ADVAN15, or ADVAN17 is used to solve
algebraic equations solved.  In  this case =TIME= is optional.
[fn:3] NM-TRAN has always allowed negative clock times when day-time
translation is performed, and converted them to non-negative relative
times.
[fn:4] The steady-state kinetics described here is general, but the
approach of =SS= data item in this section is not applicable to delay
differential equations and some other systems, e.g., those with
changes in kinetics outside the dosing interval. See
@@html:<a href="/docs/user-guide/techniques/steady_state/">empirical approach for state state</a>@@ for those situations.
[fn:5] Alternatively one can specify a dedicated subsequent other-type event record with the same
time data item.
