#+title: $AES
{{< katex >}}{{< /katex >}}

* $AES
:PROPERTIES:
:CUSTOM_ID: aes_record
:END:

Marks the beginning of abbreviated code for the AES routine

#+begin_src perl
 $AES
 abbreviated code
#+end_src

** Discussion
The ~$AES~ record is used to compute algebraic expressions which can be
regarded as specifying equilibrium kinetics. It is used with PREDPP's
[[file:/docs/reference-manual/control-records/subroutines/#advan9-15-17][ADVAN9, ADVAN15 and ADVAN17]].

(See [[file:/docs/reference-manual/control-records/aesinit/][$AESINIT]]).

The complete AES routine can be divided into two parts: code which computes the amounts in the equilibrium compartments at the beginning of the integration interval (these amounts depend on the amounts
in the nonequilibrium compartments) and code which computes values for the right sides of the algebraic
equations. An abbreviated code for AES is actually divided into two abbreviated codes which correspond to the two parts of the complete AES routine. This record gives an abbreviated code for the second part of the AES routine. The ~$AESINITIAL~ record gives an abbreviated code for
the first part. The ~$AES~ record, along with all its continuation
records, is called a ~$AES~ block.

This record is optional. If it appears, it must be with the first problem specification, and only this problem
specfication. If there are no equilibrium compartments, but ADVAN9 or ADVAN15 is used, the record
need not appear. It may not appear when the MODEL routine is user-supplied. Implicit basic PK param-
eters may be used in the ~$AES~ block (see below) only when the ~$PK~ block precedes the ~$AES~ block.

The mandatory left-hand quantities are values of expressions which when set to 0, constitute the system
of algebraic equations describing the equilibrium kinetics. They are symbolized by E(n). The number
n must be an equilibrium compartment number. However, there need not be any particular relationship
between the indices and the equilibrium compartments. At least one such quantity must be computed.

Symbolic differentiation is used to obtain code used in the generated subroutine to compute the elements
of the DA, DP, and DT arrays.

See [[file:/docs/reference-manual/abbr/][abbreviated code]] for general rules.
Specific rules follow.

** Assignment: left-hand quantities
- E(ncm1+i), E(ncm1+2), ...  (Required. Expressions which, when set to
  0, constitute the system of  algebraic  expressions  describing  the
  equilibrium  kinetics. ncm1 is the number of nonequilibrium
  compartments.)  The indices "(...)" may be omitted, in which  case
  NM-TRAN will  supply  them  according  to the order in which the
  expressions appear.  Indices are required when the expressions are
  defined  conditionally (i.e., using an IF statement).
- AES-defined (i.e., PRED-defined) items.

** Assignment: right-hand quantities
- A(1),  A(2), ...   (Current compartment amounts; may be random variables.)

- P(1), P(2), ...   (Post-translation basic PK parameters; may be random variables.)

- PK-defined items (Implicit basic PK parameters; may be random variables.)

- T (Time; may be random variable. T takes values continuously over an integration interval.)

- AES-defined  variables that appeared earlier as left-hand quantities
  in ~$AES~, and  similarly  from  the  ~$AESINITIAL~  record.   (Caution:
  AESINITIAL-defined variables that depend on compartment amounts will
  depend on the initial values of these compartment amounts,  not  the
  current values.)

- Data item labels specified on the ~$INPUT~ statement.

- THETA(n).

- Global Variables in Modules: certain variables in Fortran modules can be used.

The following are of particular interest.
  + DOSTIM: DOSTIM  is  the  time of a lagged dose or additional dose
    to which the system is being advanced.  Abbreviated code in ~$AES~
    may  test DOSTIM.  It may use DOSTIM on the right, unless DOSTIM
    is a random variable.  However, it may be used on the right in a
    ~$PK~ block  to define a random variable which may in turn be used
    on the right in the ~$AES~ block.
  + DOSREC: DOSREC is the dose record corresponding to the  dose
    entering  at DOSTIM.   Abbreviated  code  in ~$AES~ may test items
    in DOSREC in a logical condition, and DOSREC may always be used on
    the right.

  + ISFINL: During simulation or a copying pass, and during the
    advance  to  a particular  time  (event  or  non-event time),
    ISFINL=1 at a final call to AES at that time.  Otherwise,
    ISFINL=0.

Reserved Variable Names: IR DA DP DT ETA(n) EPS(n) ERR(n)

** Record order

- Follows ~$SUBROUTINES~ ~$INPUT~ ~$MODEL~ ~$PK~

- Follows ~$AESINITIAL~

(See [[file:/docs/reference-manual/api/subroutines/#AES-routine][AES]])
