#+title: $AESINIT
{{< katex >}}{{< /katex >}}

* $AESINIT
Marks the beginning of abbreviated code for the AES routine.
#+begin_src perl
 $AESINITIAL
 abbreviated code
#+end_src

** Discussion
The  ~$AESINITIAL~ record is used to compute the amounts in the
equilibrium compartments at the beginning of an integration interval.
It  is used  with  PREDPP's [[file:/docs/reference-manual/control-records/subroutines/#advan9-15-17][ADVAN9, ADVAN15 and ADVAN17]].

May also be coded ~$AES0~.

The complete AES routine can be divided into two parts: code which computes the amounts in the equilibrium compartments at the beginning of an integration interval (these amounts depend on the amounts in the nonequilibrium compartments) and code which computes values for the right sides of the algebraic equations. An abbreviated code for AES is actually divided into two abbreviated codes which correspond to the two parts of the complete AES routine. This record gives an abbreviated code for the first part of the AES routine. [[file:/docs/reference-manual/control-records/aes][The $AES record]] gives an abbreviated code for the second part. The ~$AESINITIAL~ record, along with all its continuation records, is called a ~$AESINITIAL~ block.

This record is optional. If it appears, it must be with the first
problem specification, and only this problem specfication. If there
are no equilibrium compartments, but ADVAN9 or ADVAN15 is used, the
record need not appear. It may not appear when the MODEL routine is
user-supplied. Implicit basic PK parameters may be used in the
~$AESINITIAL~ block (see below) only when the ~$PK~ block precedes the
~$AESINITIAL~ block.

In order to compute the amounts in the equilibrium compartments at the beginning of an integration
interval, the algebraic system must be solved. However, only an approximate solution is needed. If
requested, this will be used only as an initial solution, and ADVAN9
will numerically obtain a more precise solution.

See [[file:/docs/reference-manual/abbr/][abbreviated code]] for general rules. Specific rules follow.

** Assignment: left-hand quantities
- A(ncm1+1), A(ncm1+2), ...  (Required. The amounts in  the
  equilibrium compartments at the beginning of the integration
  interval. ncm1 is the number of nonequilibrium compartments.)
- INIT (Initialization flag.)
  + INIT=0: The A(n) are approximate.
  + INIT=1: The A(n) are exact (the default).

- AESINITIAL-defined (i.e., PRED-defined) items.

** Assignment: right-hand quantities

- A(1), A(2), ...   (Current compartment amounts; may be  random  variables.)

- P(1),  P(2), ...   (Post-translation basic PK parameters; may be random variables.)

- PK-defined items (Implicit basic PK parameters; may be  random  variables.)

- T  (Time  at the beginning of the integration interval; may be random variables.)

- AESINITIAL-defined items that appeared earlier as  left-hand  quantities.

- Data item labels specified on the ~$INPUT~ statement.

- THETA(n).

- Global Variables in Modules: certain variables in Fortran modules can be used.

Forbidden Variable Names: IR DA DP DT E(n) ETA(n) EPS(n) ERR(n)

** Storage and calling options
- ~COMRES=-1~. See [[file:/docs/reference-manual/control-records/abbrev/#headline-4][COMRES]].

- Calling protocol:
  + CALLFL=-1: Call ADVAN and AES with every event record (default).
  + CALLFL=1: Call ADVAN and AES once per individual record. (CALLFL may be used only when the TIME data item is not defined.)
We recommend enclose the options in parentheses. Use semicolon to separate multiple options.
  #+begin_src perl
  $AESINIT (ONCE PER IR)     ;#  same as CALLFL=1
  $AESINIT (EVERY EVENT)     ;#  same as CALLFL=-1 (default)
  #+end_src
  See [[file:/docs/reference-manual/abbr/#calling_protocol][caling protocols]]  for details.

** Record order
 - Follows ~$SUBROUTINES~ ~$INPUT~ ~$MODEL~ ~$PK~

 - Precedes ~$AES~
