#+title: $MSFI
{{< katex >}}{{< /katex >}}

* $MSFI

Specifies the name of an input [[file:/docs/reference-manual/files/#msf][Model Specification File]].

#+begin_src perl
 $MSFI   filename [NORESCALE|RESCALE] [NPOPETAS[=n]]
         [ONLYREAD]  [NOMSFTEST|MSFTEST]
         [VERSION=n]
         [NEW]

;# Example
 $MSFI   MSF13
#+end_src

** Options

*** filename
Name  of the Model Specification File.  Must be the first option.
The filename may not contain embedded spaces.  It is recommended that the
filename be (single or double) quoted. The maximum length is 71 characters.

*** NORESCALE | RESCALE
~NORESCALE~ (default): the search is continued using the
settings in the previous run. This option is overwritten when
the ~$ESTIMATION~ uses different options from those
in the previous run.

~RESCALE~: the search is to be restarted with initial estimates taken
to be the final estimates from the previous run, with UCP reset to 0.1.
This option may be used only if the search with the previous run
terminated  successfully and all the ~$ESTIMATION~ options other than
MAXEVAL are the same as in the  previous  run.

*** NPOPETAS[=n]
Specifies the number of population ETA variables.  This option is
required  when  the ~$ERROR~  block  describes a model that changes
the value of F, and there is no ~$PK~ block.  It is also required when
variables  ~A(n)~ are  used  in  the  ~$PK~  abbreviated code.
Use ~NPOPETAS=0~ for single-subject data.

May also use alias ~POPETAS~.

*** ONLYREAD
This option should be used if and only if the MSF is being used to
convey prior information  to a succeeding problem  in the control
stream (see [[file:/docs/reference-manual/control-records/prior][$PRIOR and TNPRI]]).  No task records may appear in a
problem specification containing a ~$MSFI~ record with this option.

When  ~$MSFI~  is  used in a problem specification, ~$THETA~, ~$OMEGA~
and ~$SIGMA~ records should not be used.  It is  permissible, though
uncommon,  for  the  data  file to differ from the original data file.

*** MSFTEST | NOMSFTEST
~MSFTEST~ (default): test an MSF file for errors.

~NOMSFTEST~: turn off MSF checking, as sometimes the MSFI error check is too strict. This  occurs mostly in classical NONMEM methods.

*** VERSION[=n]
Read in MSF files from  previous  versions.  With  NONMEM  7.5.0, choices are:
#+begin_src perl
  $MSFI filename.msf VERSION=7.4.0
  $MSFI filename.msf VERSION=7.3.0
  $MSFI filename.msf VERSION=7.2.0
  $MSFI filename.msf VERSION=7.1.2
  $MSFI filename.msf VERSION=7.1.0
  $MSFI filename.msf VERSION=6.2
  $MSFI filename.msf VERSION=6.1
#+end_src
The MSF file format for NONMEM v7.5.0+ does not require a VERSION
specification. They are to be used by NONMEM v7.5.0+.

*** NEW
The option is to allow new analysis to continue, or to
an analysis on a new data set, based on the final
parameters of a successful run (that generates the MSF file).
