#+title: $OMEGA
{{< katex >}}{{< /katex >}}

* $OMEGA
Supplies initial estimates for the NONMEM OMEGA Matrix.
#+begin_src perl
$OMEGA  [DIAGONAL(n) | BLOCK(n) | BLOCK(n) SAME(m) | BLOCK SAME(m)]
         [[value1]  [value2]  [value3] ...
         [(value,value...) xn]
         [BLOCK(n) VALUES(diag,odiag)]
         [label=value] ...
         [BLOCK(n) [NAMES (label1,...,labeln)] [VALUES (diag,odiag)]
         [FIXED] [UNINT]
         [VARIANCE|STANDARD] [COVARIANCE|CORRELATON] [CHOLESKY]
         [SCALE(scalevalue)]

; Example
$OMEGA BLOCK(3)  6. .005 .3 .0002 .006 .4
#+end_src

** DISCUSSION
This record gives initial estimates and constraints for elements of
one or several blocks of the OMEGA matrix, i.e., the matrix of
variances and  covariances  of  the  ETA  variables  in the
statistical model.  This record should appear only if the statistical
model  contains  ETA  variables. Multiple  $OMEGA  records  may  be
used  to define multiple blocks of OMEGA.  The order of the appearance
of all  blocks  over  all  records corresponds to the order of the
blocks in OMEGA.

If the initial estimates are omitted for any element(s) of OMEGA, then
NONMEM will try to obtain the initial estimates.

See also the SPECIAL CASE below for the analysis type POPULATION  WITH
UNCONSTRAINED ETAS.

** OPTIONS

 There are seven forms:

*** DIAGONAL(n)
This  gives  the  initial estimates of the diagonal elements of a diagonal block of OMEGA,  e.g.,
#+begin_src perl
$OMEGA [DIAGONAL(n)] [ v11 v22 v33 ... vnn ]

;# Example:

;# Initial estimate of variance of eta(1) = .04
;# Initial estimate of variance of eta(2) = .12
  $OMEGA .04 .12
#+end_src
Each initial estimate may optionally be coded  with  one  of  the forms:
#+begin_src perl
  init options      (init options)        (options init)
#+end_src
NONMEM v7.3+ supports ~(value,value...)xn~ for repeated
entries of $OMEGA may be entered easily.   Any  initial  value  or
group  of  initial values may be enclosed in parentheses and followed
by ~xn~ to indicate ~n~ replications of the values.

The  following  options  apply  only to a single initial estimate
(i.e., a single 1x1 block) and must follow the  initial  estimate
unless within parentheses.

  - FIXED: the variance is to be constrained to be fixed to the given
    initial estimate.  (When FIXED appears anywhere,  then  the  block
    is described by NONMEM as consisting of separate blocks, each of
    dimension one.)


  - UNINT (NM75):  used  during  the Optimal  Design  Step to identify
    an eta as uninteresting.  UNINT may be used anywhere that FIXED
    may be used.

  - VARIANCE: the initial estimate is a variance of the
    ETA.  This is the default.

  - STANDARD: the initial estimate is the standard deviation of the
    ETA.  May also be coded SD. An initial estimate may be 0 only if
    the  variance  or  standard deviation is fixed to this estimate.

*** BLOCK(n)
#+begin_src perl
$OMEGA BLOCK(n) [ v11 v21 v22 v31 v32 v33 ... vn1 vn2 ... vnn ]

;# example
$OMEGA BLOCK(2) .04 .002 .12
#+end_src
This  gives the initial estimates of all the elements of a nondiagonal ("full") block of OMEGA.
The example gives initial estimates var(ETA(1)) = .04, cov(ETA(2), ETA(1)) = .002, and var(ETA(2)) = .12.

Any initial value or group of initial values may be  enclosed  in
      parentheses  and  followed  by "xn", which means to replicate the
      values within parentheses n times ("repeated value").

The following options apply to the entire block  and  may  appear
      anywhere among the list of initial estimates:

  - FIXED:  indicates that the entire block is constrained to be fixed
    to its initial estimate.

  - UNINT (NM75):  used  during  the Optimal  Design  Step to identify
    an eta as uninteresting.  UNINT may be used anywhere that FIXED
    may be used.

  - VARIANCE: indicates that all initial estimates given for  diagonal
      elements  are  understood to be initial estimates of variances of
      etas.  This is the default.

  - STANDARD: indicates that all initial estimates given for  diagonal
      elements are understood to be initial estimates of standard deviations of etas.  May also be coded SD.

  - COVARIANCE: indicates that all initial  estmates  given  for
    offdiagonal  elements  are  understood  to  be  initial estimates
    of covariances of etas.  This is the default.

  - CORRELATON: indicates that all initial  estmates  given  for
    offdiagonal  elements are understood to be initial estimates of
    correlations of etas.

  - CHOLESKY: indicates that the block is specified  in  its  Cholesky form.

Options VARIANCE or STANDARD may be combined with COVARIANCE or CORRELATON.

Note that NONMEM converts all initial estimates to  variance  and
      covariances.   The  values  desplayed in the NONMEM report and in
      the raw and additional output  files  are  always  variances  and
      covariances.

Examples:
The following describe the same block (within rounding errors):
#+begin_src perl
  $OMEGA BLOCK(2) ;# or $OMEGA VARIANCE COVARIANCE BLOCK(2)
  0.64
  -0.24 0.58

  $OMEGA STANDARD BLOCK(2)
  0.8
  -0.24 0.762

  $OMEGA STANDARD CORRELATION BLOCK(2)
  0.8
  -0.394 0.762

  $OMEGA VARIANCE CORRELATION BLOCK(2)
  0.64
  -0.394 0.58

  $OMEGA CHOLESKY BLOCK(2)
  0.8
  -0.3 0.7
#+end_src
The (entire) initial estimate of the block must be positive definite.
The only exception is when the entire initial estimate  of the  block
is 0, in which case it must be fixed to this estimate. Initial
estimates of some of the elements of the block may be  0, while
initial  estimates  of some other elements may be nonzero, but only in
the case where the block is constrained to be of band symmetric  form.
That is, given the diagonal and a group of contiguous subdiagonals
symmetrically ocurring across the  diagonal, the  elements off both
the diagonal and the subdiagonals are constrained to be zero.  To
specify the initial estimates of such  a block,  the  initial
estimates  of those elements that are to be constrained to 0 should be
given as 0, while  all  other  initial estimates  should  be  given as
nonzero.  E.g., with these structures for $OMEGA BLOCK(3), the 0's are
preserved:

#+begin_src perl
  x
  0x
  00x

  x
  xx
  0xx
#+end_src
With NONMEM 7.3 if the initial estimate of a block is  not  positive
definite  because of rounding errors, a value will be added to the
diagonal elements to make it positive definite. A  message in  the
NONMEM  report  file  will  indicate that this was done. E.g.,
#+begin_src
 DIAGONAL SHIFT OF 1.1000E-03 WAS IMPOSED TO ENSURE POSITIVE DEFINITENESS
#+end_src

*** BLOCK(n) SAME(m)
#+begin_src perl
$OMEGA BLOCK(n) SAME(m)
#+end_src
This  describes a block whose initial estimates, as well as final
      estimates, are constrained to be equal to those of the  preceding
      block. Values may not be given. "(n)" may be omitted.

With  NONMEM  7.3 (m) is permitted.  If (m) is present, then this
      record is equivalent to m identical records without (m).  E.g.,
      $OMEGA BLOCK(2) SAME(3)
      is equivalent to
      #+begin_src perl
      $OMEGA BLOCK(2) SAME
      $OMEGA BLOCK(2) SAME
      $OMEGA BLOCK(2) SAME
      #+end_src

*** BLOCK(n) VALUES(diag,odiag)
:PROPERTIES:
:CUSTOM_ID: block-values
:END:
#+begin_src perl
  $OMEGA BLOCK(n) VALUES(diag,odiag)
#+end_src
This supplies initial values for a block such  that  the  initial
estimates of the diagonal elements are all the same, specified by
"diag", and the initial estimates of  the  off-diagonal  elements are
all the same, specified by "odiag".  If present, VALUES must follow
BLOCK.  Other options  (such  as  FIXED,  CHOLESKY,
VARIANCE,STANDARD,COVARIANCE,CORRELATON,  UNINT) may follow VALUES or
be placed between BLOCK and VALUES. E.g.,

#+begin_src perl
  $OMEGA BLOCK(6) VALUES(0.1,0.01)
  is the same as
  $OMEGA BLOCK(6)
  0.1
  0.01 0.1
  (0.01)x2 0.1
  (0.01)x3 0.1
  (0.01)x4 0.1
  (0.01)x5 0.1
#+end_src
For fixed block (such as for omega priors):
#+begin_src perl
  $OMEGA BLOCK(6) FIX VALUES(0.15,0.0)
#+end_src

*** label=value (NM75)
#+begin_src perl
  $OMEGA label=value (NM75)
#+end_src
The symbolic label substitution feature is new with  NONMEM  7.5. This
is a compact method of defining an ETA (an element of OMEGA)
specifying its initial estimate, and specifying a label  for  the
subscript  for this element of OMEGA.  The label may be used as a
subscript for ETA in abbreviated code,  and  will  also  identify this
element  of  OMEGA  in  the  NONMEM  output.  If new $OMEGA records
change the ordering, the abbreviated code does  not  have to  be
changed.  For example, suppose the first element of OMEGA that is
defined happens to be
#+begin_src perl
  $OMEGA ECL=.4
#+end_src
The NONMEM report will describe the relationship, e.g.,
#+begin_src perl
  LABELS FOR ETAS
  ETA(1)=ETA(ECL)
#+end_src
and ETA(CL) rather than ETA1 will appear in  the  NONMEM  report.
      The  abbreviated  code can use this symbolic subscript instead of
      the numeric subscript.  Then, these take effect on both ETA's and
      MU_'s.

For  example, suppose the following code is present for the first
elements of THETA and ETA.  Note that $OMEGA and  $THETA  records must
be placed ahead of any records that use the symbolic label.
#+begin_src perl
$THETA CL=(0.0,7.0)
$OMEGA ECL= 0.3
$PK
MU_ECL=THETA(CL)
CL=EXP(MU_ECL+ETA(ECL))
#+end_src
This is equivalent to
#+begin_src perl
$THETA (0.0,7.0)
$OMEGA .3
$PK
MU_1+THETA(1)
CL=EXP(MU_1+ETA(1))
#+end_src

Another example defines symbolic labels for a block of OMEGA:
      #+begin_src perl
      $OMEGA BLOCK(4)
      ECL=  0.3
      EV1=  0.01 0.35
      EQ=   0.01 0.01 0.54
      EV2=  0.01 0.01 0.01 0.67
      #+end_src
      Or, for diagonals,

      #+begin_src perl
      $OMEGA
      ECL= 0.3
      EV1= 0.35
      EQ=  0.54
      EV2= 0.67
      #+end_src

*** BLOCK(n) NAMES (NM75)
#+begin_src perl
  $OMEGA BLOCK(n) NAMES  (label1,...,labeln)  VALUES  (odiag,diag)
#+end_src
Symbolic label substitution may be specified for
      an entire block using the NAMES option.  This is a compact way of
      defining one or more etas with labels  and,  when  combined  with
      VALUES, with initial values. For example

      #+begin_src perl
      $OMEGA BLOCK(4) NAMES(ECL,EV1,EQ,EV2) VALUES(0.03,0.01)
      #+end_src

      This is equivalent to

      #+begin_src perl
      $OMEGA BLOCK(4)
      ECL=  0.03
      EV1=  0.01 0.03
      EQ=   0.01 0.01 0.03
      EV2=  0.01 0.01 0.01 0.03
      #+end_src

      If both are present, VALUES() must come after NAMES().

A special case for NONMEM 7.3: if  all diagonal elements of OMEGA are
"1.0E+06 FIXED", then NONMEM describes the data as
#+begin_src
ANALYSIS TYPE: POPULATION WITH UNCONSTRAINED ETAS
#+end_src
Structurally NONMEM sees the analysis as population,  but  mathematically, the population density portion of the total likelihood
      is not included.  This allows a population data set  to  be  analyzed  as  if  the  data from each individual were single-subject
      data.  Furthermore, some theta parameters could be shared  across
      subjects  ("pooled fit parameters"), whereas etas are free to fit
      each individual without any population constraint.   Parallelization is possible.

***   SCALE(scalevalue) (NM76)
#+begin_src perl
$OMEGA  SCALE(scalevalue)
#+end_src
One may have your OMEGA or SIGMA values multiplied
      by a SCALE value.  The SCALE value takes into affect on any OMEGA
      or SIGMA values that come after it in the record:

      #+begin_src perl
	$OMEGA 0.5 0.7 SCALE(2.0) 0.8 0.9 SCALE(1.5) 0.1 0.2
      #+end_src

      is equivalent to

      #+begin_src perl
	$OMEGA 0.5 0.7 1.6 1.8 0.15 0.3
      #+end_src

Another example:
#+begin_src perl
  $OMEGAP SCALE(0.7) BLOCK(4) FIX VALUES(0.5,0.01)
#+end_src
is equivalent to:
#+begin_src perl
  $OMEGAP BLOCK(4) FIX VALUES(0.35,0.07)
#+end_src
Another example:
#+begin_src perl
  $OMEGAP SCALE(0.7) BLOCK(4) FIX
  0.5
  0.01 0.5
  SCALE(2.5)
  0.02 0.02 0.003
#+end_src
is equivalent to
#+begin_src perl
  $OMEGAP SCALE(0.7) BLOCK(4) FIX
  0.5
  0.01 0.5
  0.05 0.05 0.0075
#+end_src
The  SCALE is most useful when it is desired to scale an informed
      prior OMEGA from a previous analysis that  differs  from  NONMEMs
      normal  treatment.   For example, you may wish to scale the omega
      prior by (df-p-1)/df, where df=degrees of freedom,  and  p=dimension  of  omega  block.  Rather than always re-calculate by hand, you can change the scale on the fly.
