---
title: "Control records"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: true
weight: 11
---

* Control records
A NONMEM control record begins with a record reserved word that starts
with "$". Unless specified, each control record section in this
chapter begins with a code block for the control record's usage and an example.

** Overview of a NONMEM run
Each NONMEM problem's run consists of a sequence of steps.
1. NONMEM  loads information from a model specification file, if $MSFI
   is present NONMEM makes a single call to  PRED  (with  ICALL=0),
   at  the beginning  of  the  run, to allow PRED to undertake run
   initialization (INITL).

2. NONMEM makes a single call to PRED (with ICALL=1), at the beginning
   of every  problem,  to  allow  PRED  to  undertake problem
   initialization (INITL).

3. SIMULATION STEP: NONMEM inputs initial fixed effects parameters
   from  file  specified  by  $CHAIN, if record is present NONMEM
   performs simulation (with ICALL=4) (if $SIMULATION present).

4. INITIAL ESTIMATE STEP (with ICALL=2): NONMEM obtains initial
   estimates for theta, omega, sigma (if  the control stream does not
   provide all initial estimates).

5. ESTIMATION STEP (with ICALL=2): NONMEM inputs initial etas from
   file specified by $ETAS/$PHIS, if record is present NONMEM searches
   for parameter values that mini- mize the objective function (if
   $ESTIMATION present).  With  NON- MEM 7, multiple Estimation Steps
   can be implemented in  a  single problem.   A  sequence  of  two
   or  more  Estimation Steps  will result in the sequential execution
   of each.

6. COVARIANCE STEP (with ICALL=2) NONMEM obtains a variance-covariance
   matrix of the estimator  and related  information  such  as
   standard  errors  (if $COVARIANCE present).

7. FINALIZATION STEP (with ICALL=2,5,6) NONMEM obtains the following as needed:
  - Classification into subpopulations (if a  MIXTURE  model  is used)(FNLMOD).
  - Posthoc estimates of ETA.
  - Nonparametric  step  (NONPAR,  with ICALL=2): NONMEM obtains
    either marginal cumulatives or  conditional  (nonparametric)
  - Estimates of ETAs for $NONPARAMETRIC.
  - PRED-defined values from NMPRD4 (NP4F) (for tables and scatterplots).

8. NONMEM computes WRES and other diagnostics if they are to be
   displayed in tables or scatters. (PRRES)

9. NONMEM makes a single call to PRED (with ICALL=3), at the end of
   every problem (and subproblem), to allow PRED to undertake problem
   finalization.

10. TABLE STEP: NONMEM constructs tables (if $TABLE present). Same for $SCATTERPLOT.
