$PROBLEM PHENOBARB WITH WEIGHT IN MODELS FOR CL AND V
$INPUT   ID TIME AMT WT APGR DV
$DATA    INDATA
$SUBROUTINE ADVAN1
$PK
   TVCL=THETA(1)+THETA(3)*WT
   CL=TVCL+ETA(1)
   TVVD=THETA(2)+THETA(4)*WT
   V=TVVD+ETA(2)
                       ; THE FOLLOWING ARE REQUIRED BY PREDPP
   K=CL/V
   S1=V
$ERROR
   Y=F+ERR(1)
$THETA  (0,.0027) (0,.70) .0018  .5
$OMEGA  .000007, .3
$SIGMA   8
$ESTIMATION PRINT=10
$COVARIANCE UNCONDITIONAL
$TABLE ID TIME AMT WT APGR DV
