---
title: "Reference manual"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: false
weight: 11
---

* Reference manual
This is the official online reference manual for NONMEM. It contains
details of control records and their options, syntax of abbreviated
code, data labels, and outputs. For advanced users it also provides
instructions for customization, and details of NONMEM's API.

** Copyright and trademark
Copyright by the Regents of the University of California 1994, 2009.

Copyright by ICON plc 2011, 2012, 2013,2015,2017,2020,2024.

All rights reserved.

The NONMEM name and logo are registered trademarks of the Regents of the University of California.

** Notations
In this document we use the following notations to describe functions,
arguments, and options.
- Any or all arguments in =[ ]= are optional, e.g. =[foo bar]=, and
  equivalently =[foo] [bar]=,  means =foo= and =bar= are both optional.
- Options delimited by =|= cannot be used together, e.g. =option=a|b=
  means one must choose to specify =option=a= or =option=b=.
- =...= indicates reaptable arguments, e.g. =filename ...= means one can
  supply multiple files, and =[label|value]...= means =label1 value2 value3 label4= is allowed.
- A keyword with "(NONMEM version)" appended indicates the
  record/option as introduced in that version. For example "$DEFAULT
  (NM74)" means the record was introduced in NONMEM v7.4.
- Starting in v7.2 NONMEM  is no longer case-sensitive to reserved
  keywords, reserved variables, or user-defined variables.
