---
title: "Abbreviated code"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: false
weight: 12
---

* Abbreviated code
:PROPERTIES:
:CUSTOM_ID: abbreviated-code
:END:

Abbreviated  code  follows a subset of Fortran language syntax within an NM-TRAN control
stream that is used to specify a model.  The $PRED, $PK, $ERROR, $DES,
$AES, $AESINITIAL, $TOL, $MIX, and $INFN records each initiates a
block of abbreviated code.  Such a block ends with either  the
appearance  of another  record (beginning with a "$"), or end of the
control stream. The code blocks in NONMEM 7.2+ versions are case-insensitive.

** Comments
Semicolon character ";" marks the beginning of comments so that the
 rest of the line is ignored.

** Line continuation
Continuation lines are permitted using the character & at the end of the line.

** Variables
User-defined variables are names used in code blocks that are not
reserved words. They used to be restricted to 8 characters in length
and could not include the char- acter in  previous  versions  of
NONMEM.  With NONMEM 7 a user-defined  variable  name  consists  of
1-20 letters (A-Z), numerals (0-9), and the character '_', beginning
with a letter.  (The length 20 is specified by [[file:/docs/reference-manual/api/modules/#sizes-fsizes-prsizes][constant SD in SIZES]])

User-define variables are used as the left-hand quantities in
assignment (see below).

All variables  are  all of double precision floating point type.

** Assignment
An assignment statement  =A=B=  uses  right-hand  quantities  in  an
expression =B= in order to define a user-defined variable =A=.

Permissible right-hand quantities =B= are expressions consisting of :
  - previously  defined  quantities,  including  declared variables
    that have also been used on the left side of an assignment statement. (See [[file:/docs/reference-manual/control-records/abbrev][$ABBREVIATED]]);
  - constants [fn:4], e.g. 1, 1.1, 3E+1, 3E1, 3E01, 3E-1 3E-01, 3D+1, 3D1, 3D01, 3D-1, 3D-01;
  - THETA,  OMEGA  and  SIGMA elements, e.g. THETA(1), OMEGA(2,2).
    When the two subscripts for an OMEGA or SIGMA element are the
    same,  only one subscript is needed, e.g. OMEGA(2);
  - data items defined in the $INPUT record variables;
  - ETA(n), EPS(n), ERR(n), assummed with mean 0 and
    covariances matrix specifed accordingly by OMEGA and
    SIGMA. Except in certain blocks of abbreviated code  (i.e.
    a  simulation block,   an   initialization   block,  a
    finalization  block,  or  a pred_ignore_data block), the variables
    are considered to be (the base) random
    variables, and quantities defined in terms of these variables
    (directly or indirectly) are  themselves random
    variables.  NM-TRAN sets up computations for derivatives of random
    variables with  respect  to  the  base  random variables.
  - operators =+= (add), =-= (substract,) =*= (multiply), =/=
    (divide), =**= (exponentiate);
  - parentheses (), may  be  nested.
  - Fortran functions:  LOG (natural log), LOG10, EXP, SQRT, SIN, COS,
   ABS, TAN, ASIN, ACOS, ATAN, INT, MIN, MAX, MOD;
  - NONMEM function: PHI;
  - NONMEM function: GAMLN for the logarithm of the gamma function. It
    can be used to evaluate factorials:
    #+begin_src f90
      exp(gamln(x+1.0)) ;! equals to X! = X(X-1)(X-2)...
    #+end_src
  - NONMEM function: RANDMT and RANDMTU that return a random variables
    (See Introduction to NONMEM 7 for details).

If a Fortran function has  random  variable  arguments,  NONMEM
computes the cooresponding partial derivatives.  The partial
derivative of ABS(X) with respect to eta is mathematically undefined
at X=0.  We are arbitrarily defining it to be dX/deta. If the
prediction depends on X, X must always be either positive or
negative. If  the  argument of GAMLN is a random variable, it must
always be positive.  Function PHI may have a random argument but no
partial derivates are computed.

Similarly, INT,  MOD,  MIN,  and  MAX  functions  return  discontinuous
values, and no partial derivatives are computed.  If they  are  used
outside  of  a simulation block and the function value affects the
value of the objective function, then an error in the NONMEM
Estimation Step will probably occur.  If they are needed in the
computations of DADT (differential equations; with ADVAN 6, 8, 9,
13, 14,  15,  16, 17, 18), then the funcions should be used
instead in the PK routine, and model event time (MTIME)
parameters be used to set flags for DES.

See below "functions" and "subscripted variables".

(See Model Time examples)

(See Cirdadian example)

Left-hand quantities =A= can be:

- VECTRA(n), VECTRB(n), VECTRC(n): they become elements of
  pre-defined  vectors  VECTRA,  VECTRB, VECTRC.   If  VECTRA, VECTRB,
  VECTRC is defined without a subscript, it is understood to be a
  simple variable.  A subscript  must  be  an integer constant, or a
  character string that is replaced by an integer constant using the
  $ABBR REPLACE feature.  Whereas  once  it  is defined,  a vector
  element may be used as a right-hand quantity -- in the same way as
  any previously defined variable -- the vector itself may be used
  only as an argument to an abbreviated function. (See VECTORS and
  ABBREVIATED FUNCTIONS, below.)
- Certain special variables: RPTO, RPTON and PRDFL - with the
  repetition feature (See Repetition Variables); SKIP_ (but only in a
  finalization block)  -  with  superproblems  or subproblems (See [[file:/docs/reference-manual/api/variables/#skip][SKIP]]).
- =COM()= elements. (=COM= is a storage array  in module NMPRD4.
   Even if assigned with a random variables,
   NONMEM does not compute derivatives of =COM()= elements
   with respect to the base random variables).
- User-defined variables.


Variables,  constants,  and  functions  are  all of double precision floating point type.

Except  in  certain  blocks  of  abbreviated code (i.e. a simulation block, an initialization block, or a finalization block), a label in an  $INPUT record may not appear on the left in an assignment statement.

Note that not every reserved variable can served as "B" in assignment
statement A=B. For a statement A=B with a reserved variable A
that cannot later be used as a right-hand quantity, NONMEM call it
/pseudo-statement/. The pseudo-statement for a given reserved variable
can only appear at most once in an abbreviated code.
for a particular routine. It must appear before other statements of abbreviated code ocurring in that routine.
For an abbreviated code for PRED, there is only one allowable type of
pseudo-statement, for variable COMRES, and the only permitted value for the integer constant is -1. So, the statement must look like
#+begin_src f90
COMRES=-1
#+end_src
This statement indicates no variables defined in the abbreviated code are listed in NMPRD4.

** Loop (DO-WHILE)
~DO-WHILE~ may be used  in  all  blocks  of  abbreviated
code:
#+begin_src perl
 $ABBR DECLARE DOWHILE ILOOP $PK
 ILOOP=1
 DOWHILE (condition)
  .. statements ..
 ILOOP=ILOOP+1
 ENDDO
#+end_src
Previously, they were permitted only in initialization-finalization,
simulation, data  average,  and  expectation blocks.  See the separate
descriptions of these blocks.  With NONMEM 7.3, DOWHILE may also be
used  in  data-analytic blocks (i.e., in code that is executed at
ICALL=2).

When  it  is  used  in  data-anlytic code, DOWHILE must be used with a
looping variable.  Such a variable meets three criteria:

- It is declared as such, e.g. $ABBR DECLARE DOWHILE ILOOP
- It is given a value in the statement immediately before DOWHILE
- It is given a value in the statement immediately before ENDDO.

Usually, the looping variable will be tested  in  the  condition,  but this is not necessary.

- DOWHILE blocks may be nested.

- DOWHILE  blocks  may  not  include IF/THEN/ENDIF blocks.  Only
  single-statement IF statements are permitted.  E.g., IF (condition)
  statement

- Subscripted variables may be used within the block.  These  are  variables  that  have  been  declared arrays using the $ABBR statement, or subscripted reserved variables such as THETA.  Subscripts may be integer  expressions  using declared integer variables and integer values. E.g.
  #+begin_src perl
    $ABBR DECLARE X(10)
    $ABBR DECLARE DOWHILE ILOOP
     ...
    $PK
    ILOOP=1
    DOWHILE (condition)
    X(ILOOP)=THETA(ILOOP+1)
    ILOOP=ILOOP+1
    ENDDO
  #+end_src

- A DOWHILE loop may compute  recursive  random  variables.   These
  are variables  that  are modified recursively in a dowhile block and
  which have eta derivatives. For example,

  #+begin_src perl
    TERM=THETA(1)*EXP(ETA(1))
    SUM=0
    ILOOP=1
    DO WHILE(ILOOP<=IMAX)
    SUM=SUM+TERM
    ILOOP=ILOOP+1
    ENDDO
  #+end_src

- The DOWHILE recursive variable must be  initialized  to  a
  non-random variable  outside  the loop and must appear on both sides
  of the equal sign only once within the DOWHILE loop: V= ... V ...

- The syntax is limited, for example the following are not permitted:
  #+begin_src perl
    ILOOP=1
    DO WHILE(ILOOP<=IMAX)
    IF (ILOOP == 1) SUM=0  ; initialization within the loop
    SUM=SUM+TERM
    ILOOP=ILOOP+1
    ENDDO

    ILOOP=1
    DO WHILE(ILOOP<=IMAX)
    IF (ILOOP == 1) THEN
    SUM=0                  ; initialization within the loop
    ELSE                   ; else statement
    SUM=SUM+TERM
    ENDIF
    ILOOP=ILOOP+1
    ENDDO
  #+end_src

- The looping variable ILOOP may also be set and tested and incremented with different integers than shown.

Several examples are present in the examples directory:

  - Auto-correlation (~examples/ar1mod.ctl~)
  - Auto-correlation with Simulation (~exmaples/ar1newsim.ctl~).
  - Dose Superposition (~examples/sumdosetn.ctl~)
  - Summing elements of THETA (~examples/superid3_6.ctl~)

The non-FORTRAN syntax DO WHILE(DATA) is permitted  in  $PRED  initialization  and
finalization blocks, and in the $INFN record. (See [[file:/docs/user-guide/advanced/abbr_block/#initialization-finalization-block][Initialization-Finalization block]]).

** Conditional
Conditional statements have one of two forms:

#+begin_src f90
    IF (condition) assignment statement
#+end_src
or
#+begin_src f90
    IF (condition) THEN
       abbreviated code ...
    ELSEIF (condition) THEN
       abbreviated code ...
    ELSE
       abbreviated code ...
    ENDIF
#+end_src

See below for a restriction on ELSEIF.

Conditions may include the operators .EQ., .NE., .LE.,  .GE.,  .LT.,
.GT.,  .AND., and .OR..  The arthmetic operators may be coded as ==,
/=, <=, >=, <, and >, respectively.  They  may  include  expressions
that  can  be  used  as right-hand quantities with assignment
statements.  They may not include parentheses except in such
expressions.
#+begin_src f90
  ;! Valid:
  IF (Q.EQ.(R+C)/D) ...

  ;!Invalid
  IF (Q.EQ.R.AND.(C.GT.D.OR.E.EQ.F)) ...
#+end_src

With $PRED, $PK, and $ERROR records, a condition may test the  ICALL
argument.   However,  if  the test is IF (ICALL.EQ.2), then ELSE may
not be used.  Special rules apply.  For  more  detail,  see  SPECIAL
STATEMENTS (below), and help entries for these records.

A condition may also test certain variables defined in modules (See [[file:/docs/reference-manual/api/variables/][variables in NONMEM modules]], [[file:/docs/reference-manual/api/modules/][NONMEM modules]]).

Abbreviated code in a particular THEN or ELSE clause may not contain
multiple definitions of the same random variable.  The code below is
invalid:

#+begin_src f90
  IF (condition) THEN
  X=...an expression involving a random variable
  X= ....
  ENDIF
#+end_src

Random variables cannot be defined within nested conditionals, i.e.,
within a conditional structure beginning with an IF  and  containing
another  IF.   The  use  of  ELSEIF ... THEN implies a nested conditional.

A special rule applies when random variables are defined via
conditional  statements.  If a random variable is multiply defined
within a series of IF ... THEN structures, but all  conditions  are
false, then  the  value  of the random variable is set to zero.  If an
ELSE appears, then not all conditions are false. Consider two cases in
which the following statements  are  the  only ones defining TVK and
K, respectively:
#+begin_src f90
  IF (WT.GT.0) TVK=THETA(1)*WT
#+end_src
If  the  condition is false, the non-random variable TVK retains the value set with the previous data record.
#+begin_src f90
  IF (WT.GT.0) K=THETA(1)*WT*EXP(ETA(1))
#+end_src
If the condition is false, the value of the random variable K is set
to zero. NM-TRAN prints a warning message when it detects such code.

In  $PK, $ERROR, and $PRED records, recursion code may be used in an explicit manner, as in this example:

#+begin_src f90
  IF (WT.GT.0) THEN
    K=THETA(1)*WT*EXP(ETA(1))
  ELSE
    K=K
  ENDIF
#+end_src
If the condition is false, =K= retains its value set with the previous
data record. Recursion  code  can  be  used in $PRED, $PK, and $ERROR
records for other purposes as well.  The following two fragments of
code  illustrate how one can use abbreviated code to implement
recursive kinetics in $PRED.  The first example works with a single
bolus dose  and the second example works with single or multiple bolus
doses.  Similar code can be used in $PK and $ERROR.
#+begin_src f90
  K=THETA(1)*EXP(ETA(1))
  IF (TIME.EQ.0) THEN
    OLDA=AMT
    T=TIME
  ENDIF
  A=OLDA*EXP(-K*(TIME-T))
  OLDA=A
  T=TIME

  K=THETA(1)*EXP(ETA(1))
  IF (TIME.EQ.0) THEN
    A=AMT
    T=TIME
  ELSE
    A=A*EXP(-K*(TIME-T))+AMT
  ENDIF
  T=TIME
#+end_src
The above forms of recursion work for recursion from one data record
   to  the next ("inter-record" recursion).  It is also possible to use
   recursion in a do-while loop ("intra-record", or  "do-while"  recursion).

Example of a DO-WHILE recursive loop using a random variable:

#+begin_src f90
  TERM=THETA(1)*EXP(ETA(1))
  SUM=0
  DO WHILE(condition)
  SUM=SUM+TERM
  ...
  ENDDO
#+end_src
A product loop such as
#+begin_src f90
  PROD=PROD*TERM
#+end_src
is  also  possible, as are other ways the dowhile recursive variable
   can be used, so long as the variable appears on both  sides  of  the
   equal sign within the DOWHILE loop: V= ... V ...

** Vectors
The $ABBR FUNCTION and $ABBR  VECTOR  feature  allows  the  user  to
declare the names of user-defined functions and  the names and sizes
of user-defined argument vectors.  Restrictions such as  the  number
of  user functions, the number of elements in a vector, and the number of times a given function may appear  in  abbreviated  code  are
more flexible and may be modified by the user.

Reserved variable names VECTRA, VECTRB, VECTRC, etc. may be used for
pre-defined  vectors.   Elements  can  be defined in any order.
Vectors that are defined outside of $DES (or $AES) may not  be used in
the  $DES (or $AES) code. Namely, a vector may not be an implicit
basic PK parameter.

** Functions
:PROPERTIES:
:CUSTOM_ID: abbreviated-function
:END:
User-defined function's names must be of form =FUNCx=, with =x=
being =A=, =B=, ... etc. [fn:3]
 #+begin_src f90
   FUNCTION FUNCA(X,X1,X2)
   DOUBLE PRECISION X,X1,X2,FUNCA
   DIMENSION X(9),X1(9),X2(9,9)    ! dimension must be 9.
   ...
 #+end_src

In abbreviated code, the function is referenced with a single
argument, either a (scalar) expression  or a vector.  Certain reserved
names such as VECTRA, VECTRB, etc.  may be used in the function
definition, but they are not passed to the function as arguments. The
function returns =FUNCx= and has three arguments:

  - =X=:  input argument (can be a vector).
  - =X1=:  =X1(n)= is  the  first-partial  derivative  of  the  function  with
      respect to the nth element of =X=, =X(n)=.
      If  the  value  of =X(n)= is not value of a random variable, =X1(n)= need not be set.
      If the argument X is a (scalar) expression, only X1(1) is needed.
  - =X2=: =X2(n,m)= is the second-partial derivative  of  the  function  with
      respect to the nth and mth elements of the argument.
      If the value of either =X(n)= or =X(m)= will not be a value of a
    random variable, =X2(n,m)= need not be set.  Nor need any value of
    =X2= be set if a test of MSEC=1 is false (see [[file:/docs/reference-manual/api/variables/#partial-derivative-indicators][Partial Derivative Indicators]]). If the argument is a (scalar) expression,  only
    =X2(1,1)=  may  be needed.   If the argument is a vector and if
    the value of =X2(n,m)= is needed, then the value of =X2(m,n)=  is
    needed  as  well,  even though these two values will be identical.

 The  Fortran  code  for  the functions should be placed in one or more
 files.  Suppose there is one such file and its name  is funcfile.   It
 should be listed on the $SUBROUTINES record.  It may contain more than
 one FUNCTION.  E.g.,
 #+begin_src perl
 $SUBROUTINES ... OTHER=funcfile
 #+end_src

If the abbreviated code uses one of these reserved function names, but
 the  user  does  not  supply the code via $SUBR OTHER, the NONMEM
 executable will be created with an  error  message  in  the
 report file such as:
 #+begin_src
 FUNCA WAS CALLED, BUT NO CODE WAS SUPPLIED.
 #+end_src

(See Abbreviated function example).

In NONMEM v7.4+, the  $ABBR  FUNCTION  allows the user to declare the
name of the function, the name of the vector of input arguments (which
is of no use to the  function), and the length of the vector of input
arguments, which is passed to the function as argument NDIM.  Constant
NVECX  in  SIZES gives the maximum value size of the vector of input
arguments.

#+begin_src perl
 $ABBR FUNCTION function_name(input_vector_name,dimension,usage)
#+end_src

(See [[file:/docs/reference-manual/control-records/abbrev/][$ABBREVIATED]]).

The function should be coded as follows:

#+begin_src f90
 FUNCTION function_name(X,X1,X2,NDIM)
 USE SIZES, ONLY: DPSIZE,ISIZE
 INTEGER(KIND=ISIZE) :: NDIM
 REAL(KIND=DPSIZE), INTENT(IN)     :: X
 REAL(KIND=DPSIZE), INTENT(IN OUT) :: X1,X2
 REAL(KIND=DPSIZE):: function_name
 DIMENSION X(NDIM),X1(NDIM),X2(NDIM,NDIM)
#+end_src

Function_name  must  be  exactly as specified via $ABBR FUNCTION.  The
value coded as "dimension" is passed to the function  as  NDIM.   (The
value coded as "usage" is optional and does not appear in code for the
function.)

The value of the function is to be stored  in  function_name.
Otherwise, the function is coded exactly as described above, with X1
and X2 as output arguments. The input_vector_name is never used in
the  Fortran code for the function.

If FUNCA, FUNCB, FUNCC, etc.  is defined without a subscript, it  is
understood  to  be a simple variable, and then it may appear as such
as a right-hand quantity.  If FUNCx appears for the first time as  a
right-hand  quantity, it is understood to be the reserved name of an
abbreviated function, and then it must include  a  single  argument,
e.g.   FUNCA(VECTRA)) or FUNCA(THETA(1)).  Complete FORTRAN code for
an abbreviated function is supplied by  the  user  (see [[file:/docs/reference-manual/abbr/#abbreviated-function][abbreviated function]]).


** Pseudo assignment

   Pseudo-assignment  statements  are optional and provide certain special instructions.  If present, they must appear (in any  order)  at
   the beginning of a record, before the rest of the essential abbreviated code comprising that record.  They may be enclosed in parentheses, but two or more pseudo-assignment statements enclosed by parentheses must be separated by a semicolon ";".  The following  pseudostatement may be used in all records except $MIX.

   COMRES=-1  :  All  quantities  defined in abbreviated code are to be
   stored locally; they are not to be stored  in  the  (global)  MODULE
   NMPRD4.
   (Variables  in  MODULE  NMPRD4 can be used for communication between
   various user-routines, and can be displayed in tables  and  scatterplots.)

   See  the  entries for specific records for information about pseudo-assignment statements special to those records.

** Reserved variables
Entries for $PRED, $PK,  $ERROR,  $DES,
$AES, $AESINITIAL, and $TOL describe the reserved variable names for
these abbreviated codes.

A variable name that is reserved in an abbreviated code may  not  be
used as the name of a variable defined in this code, or in any other
abbreviated code unless the pseudo-assignment statement COMRES=-1 is
used (in some code).  If a reserved variable name is inappropriately
used, NM-TRAN will generate an error message.

See a list of reserved variables [[/docs/reference-manual/api/modules/#module-variables-list][here]], and their details in [[file:/docs/reference-manual/api/variables/][variables]].

** Subscripts
Subscripts may be used with user-defined variables that are declared
   to  be  arrays using the $ABBR DECLARE record, and also with certain
   reserved variables:

#+begin_src f90
  THETA,THETAFR,SETHET,THSIMP,SETHETR,THSIMPR
  OMEGA,OMEGAF,SEOMEG,OMSIMP
  SIGMA,SIGMAF,SESIGM,SGSIMP
  CNTID,IIDX
  CDEN_
  A, A_0                       ! when used in a WRITE or PRINT statement
  ETA, EPS, ERR                ! when used in a WRITE OR PRINT statement
#+end_src

Where a subscript is permitted or necessary, it may  be  an  integer
   expression.   An  integer  expression  is  an  integer  constant,  a
   declared integer variable that has appeared on the left  (i.e.,  has
   been  given  a  value),  a  constant defined in SIZES, an expression
   involving integer constants and  integer  variables  and  arithmetic
   operators +, -, *, /, **.  It may also be a character string that is
   replaced by an integer expression using the $ABBR  REPLACE  feature.
   The  number of subscripts must be equal to the number of dimensions.
   If there are two subscripts, either or  both  may  be  constants  or
   expressions.   If  a  subscripted  variable  may be used on the left
   side, then the subscript may also be an integer expression.  E.g.,

#+begin_src perl
   $ABBR DECLARE INTEGER IND
    ...
   $PK
    IND=1
    X=THETA(IND+1)
#+end_src

   With reserved random variables such as
   ETA(n) EPS(n) ERR(n) A(n) A_0(n)
   integer expressions may be used only if they are listed in in  WRITE
   or  PRINT statements.  Otherwise n must be an integer constant, or a
   character string that is replaced by an integer constant  using  the
   $ABBR REPLACE feature.

** Probability density functions
A  series of built in probability density functions are available with
NONMEM 7.4.2.  For a given probability density there is also a
cumulative  distribution function (densitycdf), and random number
generating function (density_rng).

They are described in INTRODUCTION TO NONMEM 7.4.2 Section I.26.

The density and densityCDF functions have arguments that are
compatible with the FUNC system, in which function provides
derivatives (XD), and second derivatives (XDD) (see I.65.Expanded
Syntax  and  Capacity for  User-Defined  Functions  (FUNCA)  (NM74)).
Thus, even random (eta associated) variables may serve as arguments to
the parameters of  the density   functions.  The  source  code  of
these  densities  are  in ..\source\DISTRIB.f90, DISTRIBCDF.f90, and
DISTRIBRNG.f90.  Note  that multi-variate densities do not have a
corresponding CDF routine.

Examples of their use are in the ..\examples\densities directory.

#+begin_src f90
 BERNOULLI
 BERNOULLILOGIT
 BINOMIAL
 BINOMIALLOGIT
 BETABINOMIAL
 HYPERGEOMETRIC
 CATEGORICAL
 CATEGORICALLOGIT
 ORDEREDLOGISTIC
 NEGBINOMIAL
 NEGBINOMIAL2
 NEGBINOMIAL2LOG
 POISSON
 POISSONLOG
 MULTINOMIAL
 NORMAL
 EXPMODNORMAL
 SKEWNORMAL
 STUDENTT
 DOUBLEEXPONENTIAL
 LOGISTIC
 GUMBEL
 LOGNORMAL
 CHISQUARE
 INVCHISQUARE
 SCALEDINVCHISQUARE
 EXPONENTIAL
 GAMMA
 INVGAMMA
 WEIBULL
 FRECHET
 RAYLEIGH
 PARETO
 PARETO2
 BETA
 DIRICHLET
 VON MISES
#+end_src

** Calling protocol: CALLFL
:PROPERTIES:
:CUSTOM_ID: calling_protocol
:END:

#+begin_src perl
 CALLFL=n
#+end_src
- In $PK abbreviated code: control when PREDPP calls the PK routine.

- In $ERROR abbreviated code: control when PREDPP calls the ERROR routine.

- In $AESINITIAL abbreviated code: when the TIME data item is not
  used, it controls when PREDPP calls the ADVAN9, ADVAN15,  or
  ADVAN17  routine.

The use of CALLFL in each of the three abbreviated codes is
independent of its use in the others.  The pseudo-assignment statement
may be enclosed in parentheses. The pseudo-assignment statement may take
these forms:

- CALLFL=-2: call  the  PK subroutine with every event record, with
  additional and lagged doses, and at modeled event times.  It does  not
  affect ERROR, ADVAN9, ADVAN15, or ADVAN17 routines.

  The following messages will appear in the NONMEM output report:
  #+begin_src
  PK SUBROUTINE CALLED WITH EVERY EVENT RECORD
  PK SUBROUTINE CALLED AT NONEVENT (ADDITIONAL AND LAGGED) DOSE TIMES
  or
  PK SUBROUTINE CALLED AT NONEVENT (ADDITIONAL AND LAGGED) DOSE TIMES
  AND AT MODEL TIMES
  #+end_src

- CALLFL=-1 (default): call the subroutine with every event record.

  Correspondingly messages will appear in the NONMEM output:
  #+begin_src
  PK SUBROUTINE CALLED WITH EVERY EVENT RECORD
  PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL OR LAGGED) DOSE TIMES

  ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD

  ADVAN9 CALLED WITH EVERY EVENT RECORD
  ADVAN15 CALLED WITH EVERY EVENT RECORD
  ADVAN17 CALLED WITH EVERY EVENT RECORD
  #+end_src

- CALLFL=0
  + For the PK subroutine: If the data are population data, call the
    subroutine with the first event record of each individual record;
    if the data  are  single-subject  data,  call  the subroutine with
    the first event record of the data set.  In addition, call the
    subroutine  with with  every event record where the event time
    differs from the previous event time.

    The following messages will appear in the NONMEM output report:
    #+begin_src
    PK SUBROUTINE CALLED ONLY WITH NEW INDIVIDUAL OR NEW TIME
    PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL DOSE OR LAGGED) DOSE TIMES.
    #+end_src

  + For the ERROR subroutine: When the Simulation Step  is  being
    implemented, call the subroutine with every event record.
    Otherwise, call the subroutine only with observation event
    records.

    The following messages will appear in the NONMEM output report:
    #+begin_src
    DURING SIMULATION, ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD
    OTHERWISE, ERROR SUBROUTINE CALLED ONLY WITH OBSERVATION EVENTS
    #+end_src

  + not applicable to the ADVAN9, ADVAN15, or ADVAN17 routine.

  With CALLFL=0, The CALL data item may be used to request  calls  with additional event records.

- CALLFL=1:
  + For  the  PK and ADVAN9, ADVAN15, or ADVAN17 subroutines: If the
    data are population data, call the subroutine with the first event
    record of  each individual record; if the data are single-subject
    data, call the subroutine with the first event record of the data
    set.

    The following messages appear in the NONMEM output report:
    #+begin_src
    PK SUBROUTINE CALLED ONCE PER INDIVIDUAL RECORD
    PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL DOSE OR LAGGED) DOSE TIMES

    ADVAN9 CALLED ONCE PER INDIVIDUAL RECORD.
    ADVAN15 CALLED ONCE PER INDIVIDUAL RECORD.
    ADVAN17 CALLED ONCE PER INDIVIDUAL RECORD.
    #+end_src

  + For the ERROR subroutine: When the Simulation Step  is  being
    implemented,  call  the subroutine with every event record.
    Otherwise, if the data are population data, call  the  subroutine
    with  the  first event  record  of each individual record; if the
    data are single-subject data, call the subroutine with the first
    event  record  of  the data set.

    The following messages appear in the NONMEM output report:
    #+begin_src
    DURING SIMULATION, ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD
    OTHERWISE, ERROR SUBROUTINE CALLED ONCE PER INDIVIDUAL RECORD
    #+end_src
  With  CALLFL=1,  The  CALL data item may be used to request calls with additional event records.

In a block of abbreviated code, the CALLFL=n pseudo-assignment
statement  must precede all the other abbreviated code (except for
verbatim code or other pseudo-assignment  statements). The
pseudo-assignment statement  may not be used conditionally.  CALLFL
may not be used as a variable elsewhere in the abbreviated code.

Note that if the $ERROR record consists  of  only one  of  these  four statements:
#+begin_src f90
   Y=F+ERR(1)
   Y=F*(1+ERR(1))
   Y=F+F*ERR(1)
   Y=F*EXP(ERR(1))
#+end_src
NM-TRAN will automatically limit calls to ERROR  to  once-per-problem
(unless  the Simulation  Step  is being implemented, in which case.
calls are made with every event record).  In effect, this amounts to
yet another  way to  control  when it is that calls may occur to the
ERROR routine, but one which may not be explicitly specified in $ERROR
via  the  use  of CALLFL.

With  the  last  three  models above (proportional and exponential), NM-TRAN will also request PREDPP to output the message:
#+begin_src
  ERROR IN LOG Y IS MODELED
#+end_src
This does not mean that a model is fit to Log Y data.

A calling protocol phrase may be used
within parentheses instead of a pseudo-assignment statement CALLFL.
For example
#+begin_src perl
 $PK (ONCE PER INDIVIDUAL RECORD)
 $ERROR (ONCE PER INDIVIDUAL RECORD)
 $AESINITIAL (ONCE PER INDIVIDUAL RECORD)
#+end_src
A calling protocol phrase can be used instead of  the  CALLFL
pseudo-statement  in  $PK,  $ERROR,  and  $AESINITIAL abbreviated
codes.  The phrase must be enclosed in parentheses.  Either upper  or
lower  case may  be used.  In an abbreviated code, the line of code
containing the phrase must precede all the other abbreviated code
(except for  verbatim  code  or  other  pseudo-assignment statements),
and it may be the same line that marks the beginning of the code, as
in the above  usage examples.   Pseudo-statements  defining COMRES may
be coded within the same parentheses, separated by a semicolon ";".
No  abbreviated  code may follow ")" on the same line as the ")".

- Phrases equivalent to CALLFL=-2 for the $PK record:

  #+begin_src perl
  (NON-EVENT)
  (ADDITIONAL OR LAGGED)
  #+end_src

  NONMEM will output the following messages:

  #+begin_src
  PK SUBROUTINE CALLED WITH EVERY EVENT RECORD
  PK SUBROUTINE CALLED AT NONEVENT (ADDITIONAL AND LAGGED) DOSE TIMES
  or
  PK SUBROUTINE CALLED AT NONEVENT (ADDITIONAL AND LAGGED) DOSE
  TIMES AND AT MODEL TIMES
  #+end_src

- Phrases  equivalent to CALLFL=-1 for $PK, $ERROR and $AESINITIAL records (the default):

  #+begin_src perl
  (EVERY EVENT)
  (EVERY)
  #+end_src

  NONMEM will output the following messages:

  #+begin_src
  PK SUBROUTINE CALLED WITH EVERY EVENT RECORD
  PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL OR LAGGED) DOSE TIMES

  ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD

  ADVAN9 CALLED WITH EVERY EVENT RECORD.
  ADVAN15 CALLED WITH EVERY EVENT RECORD.
  #+end_src

- Phrases equivalent to CALLFL=0 for the $PK record:

  #+begin_src perl
  (NEW TIME)
  (NEW EVENT TIME)
  #+end_src

  NONMEM will output the following messages:

  #+begin_src
  PK SUBROUTINE CALLED ONLY WITH NEW INDIVIDUAL OR NEW TIME
  PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL OR LAGGED) DOSE TIMES.
  #+end_src

- Phrases equivalent to CALLFL=0 for the $ERROR record:

  #+begin_src perl
  (OBSERVATION EVENT)
  (OBS)
  (OBSERVATION ONLY)
  (OBS ONLY)
  #+end_src

  NONMEM will output the following messages:

  #+begin_src
  DURING SIMULATION, ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD
  OTHERWISE, ERROR SUBROUTINE CALLED ONLY WITH OBSERVATION EVENTS
  #+end_src

- Phrases  equivalent  to  CALLFL=1 for the $PK, $ERROR and $AESINITIAL:

  #+begin_src perl
  (ONCE PER INDIVIDUAL RECORD)
  (ONCE/IND.REC.)
  #+end_src

  NONMEM will output the following messages:

  #+begin_src
  PK SUBROUTINE CALLED ONCE PER INDIVIDUAL RECORD
  PK SUBROUTINE NOT CALLED AT NONEVENT (ADDITIONAL OR LAGGED) DOSE TIMES

  DURING SIMULATION, ERROR SUBROUTINE CALLED WITH EVERY EVENT RECORD
  OTHERWISE, ERROR SUBROUTINE CALLED ONCE PER INDIVIDUAL RECORD

  ADVAN9 CALLED ONCE PER INDIVIDUAL RECORD.
  ADVAN15 CALLED ONCE PER INDIVIDUAL RECORD.
  #+end_src

** Verbatim code
:PROPERTIES:
:CUSTOM_ID: verbatim
:END:
USAGE:
#+begin_src perl
"      verbatim line
#+end_src

Verbatim  code is Fortran code within a block of abbreviated code that
is to be copied by NM-TRAN to the generated Fortran subroutine.  It is
not  itself regarded as abbreviated code.  Such code is marked by
having the character " as  the  first  non-blank  character.   The  "
is dropped  and  the  characters to the right are copied as-is to
columns 1-72 of the generated subroutine.  Lines of verbatim code can
include any  Fortran  statements: comment, declaration (e.g., INTEGER,
COMMON, USE), I/O, CALL, assignment, continuation, DO,  GOTO,  etc.).

NM-TRAN makes some modifications to verbatim code:

- Placement: the verbatim code is adjusted as necessary to conform to
  FORTRAN column  conventions.  Alphabetic text that follows the
  initial ", or that follows a statement number, is  moved  to  column
  7,  as required by FORTRAN.

- Comment lines: If  the  character  that  immediately follows the
  initial " is !, this conforms to the FORTRAN 90 syntax for  comment
  lines.   The line is copied unchanged.  If the character that
  immediately follows the initial " is C or c or " or *, this conforms
  to the FORTRAN  77 syntax for comment lines.  The line is copied
  unchanged, but C or c or " or * is replaced by !.

- Continuation lines: Fortran 77 continuation lines (non-blank in
  position 6)  are  not permitted  with  NONMEM  7.   Instead,  the
  line to be continued should end with character &.  Example:
  #+begin_src f90
     "      X=A &
     "      +D/E
  #+end_src

- Replacement Rule: in $PK, $ERROR, $DES, $AES, $INFN, and $PRED, in a
  line of abbreviated  code  labels  of items in the data record are
  replaced by direct references to the data record  itself  (either
  DATREC  or EVTREC,  as  appropriate).   Thus,  for  example, if such
  a label occurs as the left-hand side of  an  assignment  statement,
  then without this rule, when the statement is executed, the value of
  a local variable having the label is  modified,  whereas  with  the
  rule, an item in the data record is modified.

The  character  @,  immediately  before  a  label,  can  be used as an
"escape" to prevent the label from being replaced.  If the character @
immediately  follows the initial ", none of the labels occuring in the
line are replaced.

Labels occurring in common statements or as subroutine  arguments  are never replaced.

Tab  characters (and other characters that are smaller than blank in
the computer's collating sequence, such as carriage return ^M) are
permitted  in  verbatim  code.  With NONMEM 7, the last non-blank
character on the line is replaced by a space  if  it  is  a low-value
character.  This permits DOS-type line endings ^M.

By  default, all verbatim code goes in the main section of code and is
called MAIN verbatim code.  (The main section follows declarations and
initial  executable  code  inserted by NM-TRAN.)  Within the main
section, verbatim and abbreviated code may be freely mixed.  Each line
of verbatim  code is positioned in the generated code after all code
generated from the preceding line of  abbreviated  code.   The  user
may explicitly specify a different location as follows.

- FIRST verbatim code:
      Verbatim  lines  which  must  be positioned immediately after the
      declarations which are part of the normal subroutine header,  and
      prior  to  the FIRST executable statement of the subroutine, must
      precede the first line of abbreviated code and  must  start  with
      the line "FIRST.

- MAIN verbatim code:
      FIRST  verbatim  code is normally terminated by the first line of
      abbreviated code.  If there is both FIRST and MAIN verbatim code,
      and/or  the main section is to start with verbatim code, the line
      "MAIN may be used to separate the FIRST and MAIN verbatim code.

- LAST verbatim code:
      Verbatim lines which are to immediately precede the RETURN statement  from  the generated subroutine must follow the last line of
      abbreviated code and must be preceded by the line "LAST.

      Example:
      #+begin_src perl
       $ERROR
       Y=F*(1+ERR(1))
       "LAST
       " PRINT *,HH(1,1)
      #+end_src

      This displays values after they have been  assigned,  immediately
      prior to the return.

If  any  lines  of verbatim code are present in a block of abbreviated
code, NM-TRAN generates USE statements  appropriate  to  the  kind  of
abbreviated code and allows variables undefined in abbreviated code to
be used as right-hand quantities in abbreviated code.

[fn:1] Format specification numbers 991 and 992 are used in generated
code  to  avoid conflict with statement numbers arising from DO WHILE
statements.  The one digit versions are perhaps easier to remember.

[fn:2] No  integer format specification is provided because constants
are stored as floating point variables in generated and library
routines.

[fn:3] With NONMEM VI 2.0, reserved function names are FUNCA  through
FUNCC. reserved names for vectors are VECTRA through VECTRC; With
NONMEM 7.3, reserved function names are FUNCA through FUNCI; With
NONMEM  7.4,  reserved  function  names are FUNCA through FUNCZ.
Reserved names for vectors are VECTRA through VECTRZ. Extended
reserved names are also recognized. These are FUNCxy and FUNCxyz,
where each of x, y, z  stands  for  an  alphabetic character  A-Z,
e.g.,  FUNCAB  or FUNCABC.  Similar extended reserved names for
vectors are also recognized: e.g, VECTRAB or VECTRABC. If the
abbreviated code uses one of these extended  reserved  function names,
but the user does not supply the code via $SUBR OTHER, the NONMEM
executable cannot be created, and there will be an  error  message
from the Fortran compiler such as:
#+begin_src
Undefined Symbols
_funcaaa_
#+end_src

[fn:4] In NONMEM v7+ a constant may be up to 30 characters
(The length is specified by constant SCO in SIZES). Previous versions limit constants to 12
characters.

** Reserved and other functions
With verbatim code advanced users can also access many internal NONMEM
variables.  For example variable ~ITER_REPORT~ that contains the present
iteration number as in the output may be used within the $PK, $ERROR,
or $PRED code. To access these variables in certain block one needs to place the
corresponding MODULE definitions in an include file with name that
begins with "NONMEM_RESERVED" (case insensitive) at the beginning of
the control record block. NONMEM provides file ~util/nonmem_reserved_general~
that has many such variables, including ITER_REPORT, in the form of
verbatim code:
#+begin_src f90
"C ITER_REPORT: Iteration number that is reported to output
"C (can be negative, if during a burn period).
"C BAYES_EXTRA, BAYES_EXTRA_REQUEST, used in example 8
" USE NMBAYES_REAL, ONLY: OBJI
" USE NMBAYES_INT, ONLY: ITER_REPORT,BAYES_EXTRA_REQUEST,BAYES_EXTRA
" USE PNM_CONFIG, ONLY: PNM_NODE_NUMBER
“ USE NM_INTERFACE, ONLY: TFI,TFD
#+end_src
For example, to use ~nonmem_reserved_general~ in $PK, place the file
in the present run directory, and do (examples/example8):
#+begin_src perl
$PK
include nonmem_reserved_general
BAYES_EXTRA_REQUEST=1
MU_1=THETA(1)
MU_2=THETA(2)
MU_3=THETA(3)
MU_4=THETA(4)
CL=DEXP(MU_1+ETA(1))
V1=DEXP(MU_2+ETA(2))
Q=DEXP(MU_3+ETA(3))
V2=DEXP(MU_4+ETA(4))
S1=V1
IF(BAYES_EXTRA==1 .AND. ITER_REPORT>=0 .AND. TIME==0.0) THEN
WRITE(50,*) ITER_REPORT,ID,CL,V1,Q,V2
ENDIF
#+end_src

The ~nonmem_reserved_general~ file also contains function
declarations, such as TFI and TFD, which are convenient functions to
easily convert an integer to text (“text from integer” TFI) or double
precision value to text (“text from double” TFD).  They can be used to
to have compiler can catch a misuse of that function’s arguments. If
you wish to define your own function, and have the information about
its proper use of arguments be conveyed upon its execution, so the
compiler may detect errors, then one method is to package the
definition of the function in a USE module. For example,
~myfuncmodule.f90~ below defines the functions ~mymin~ and ~mymax~.
#+begin_src f90
  MODULE MYFUNCS
  contains
  function mymin(a,b,c,d,e)
  integer mymin
  integer a,b,c,d,e
  mymin=min(a,b,c,d,e)
  end function
  function mymax(a,b,c,d,e)
  integer mymax
  integer a,b,c,d,e
  mymax=max(a,b,c,d,e)
  end function
  END MODULE MYFUNCS
#+end_src
One can create file ~nonmem_reserved_myfunc~ to declare:
#+begin_src f90
" USE myfuncs, only: mymin,mymax
#+end_src
and use it in control stream files:
#+begin_src perl
$PROB  THEOPHYLLINE   POPULATION DATA
$INPUT      ID DOSE=AMT TIME CP=DV WT
$DATA       THEOPP

$SUBROUTINES  ADVAN2 OTHER=myfuncmodule.f90

$PK
;THETA(1)=MEAN ABSORPTION RATE CONSTANT (1/HR)
;THETA(2)=MEAN ELIMINATION RATE CONSTANT (1/HR)
;THETA(3)=SLOPE OF CLEARANCE VS WEIGHT RELATIONSHIP (LITERS/HR/KG)
;SCALING PARAMETER=VOLUME/WT SINCE DOSE IS WEIGHT-ADJUSTED
include "nonmem_reserved_myfunc"
   CALLFL=1
   KA=THETA(1)+ETA(1)
   K=THETA(2)+ETA(2)
   CL=THETA(3)*WT+ETA(3)
   SC=CL/K/WT
I=mymin(1,2,3,4,5.0)
print *,'I ',I

$THETA  (.1,3,5) (.008,.08,.5) (.004,.04,.9)
$OMEGA BLOCK(3)  6 .005 .0002 .3 .006 .4

$ERROR
   Y=F+EPS(1)

$SIGMA  .4
#+end_src
Then compiler will flag errors on mistaken argument use.

** =EXIT=
:PROPERTIES:
:CUSTOM_ID: exit
:END:

EXIT statement has three forms:
   #+begin_src f90
     EXIT
     EXIT n
     EXIT n k
   #+end_src
   n  is  called  the  "PRED error return code"; (also called the "PRED
   exit code.")  It must be 1 or 2.  Default is 1.
   k is the user error code.  It may be omitted; if present, it must be
   integer-valued  in the range 0-999.  With NONMEM 7.5, it may also be
   in the range 1000-9999  when  issued  during  the  Simulation  Step.
   Default is 0.

   With  all  versions  of  NONMEM, the value of k is part of the error
   message in ETEXT, which is reported in the NONMEM output report  and
   in  file  PRDERR.   With NONMEM 7.5 and later, k tells NONMEM how to
   handle EXIT statements during the Simulation Step.

   (See [[file:/docs/user-guide/advanced/abbr_block/#simulation-block][Simulation block]]).

   (See [[file:/docs/reference-manual/api/variables/#pred-exit][PRED EXIT code]]).

The EXIT statement causes an immediate exit from the routine and, if
PREDPP  is being used, a subsequent immediate exit from PREDPP, with a
return to NONMEM.  It is typically used  in  an  IF  statement  to
avoid  further  computation  of  the  users  code when the values of
theta/eta's set by NONMEM are inappropriate  or  would  lead  to  an
arithmetic  exception.   If such an exit occurs during a Covariance,
Table or Scatterplot Step, or  during  computation  of  the  initial
value  of  the  objective  function, NONMEM will abort.  If the exit
occurs during an Estimation  or  Initial  Estimates  Step,  NONMEM's
action depends on the error return code value:

  - n=1. Suppose  first  that  a  search  for  eta is not underway.
    Then a search for theta is underway, and when a search  is
    underway  for THETA. If the NOABORT option
    is used then NONMEM will try to continue using different values for
    THETA. If THETA recovery also fails, NONMEM will aborts. Without the
    NOABORT option, NONMEM will simply abort.
    Similarly, if a search for ETA is underway.  NONMEM  will  try  to continue  using  different
    values for ETA. If this ETA recovery fails,
    and a search for  THETA  is  not also underway, NONMEM will abort.
    Otherwise, the above procedure regarding THETA-recovery applies.
    See also [[file:/docs/reference-manual/api/subroutines/#error-recovery][Error recovery]].

  - n=2. NONMEM aborts immediately.

If NONMEM aborts, and k>0, a user message such as the  following  is
   printed in the output:
   "PK SUBROUTINE: USER ERROR CODE = k"
   This  message  is  intended  to help the user distinguish which EXIT
   statement caused NONMEM to abort when more than one  EXIT  statement
   is present in the abbreviated code.

** =WRITE= and =PRINT=
Example:
#+begin_src f90
   WRITE (50,*) 99,ID,CL,THETA(1),ETA(1)

   IF (ICALL.EQ.3) THEN
     WRITE (55,2) BIAS
   ENDIF
#+end_src

Certain  forms of Fortran WRITE, PRINT, OPEN, CLOSE, and REWIND
statements may be used anywhere in $PRED, $INFN, $PK, $ERROR,  $DES,
$AES, $AESINITIAL blocks.

#+begin_src f90
   PRINT list ...
   PRINT *,list ...
   WRITE (unit,format) list ...
   WRITE (*,format) list ...
   WRITE (unit,*) list ...
   WRITE (*,*) list ...
   OPEN(unit)
   OPEN(unit,FILE=filename)
   CLOSE(unit)
   REWIND(unit)
#+end_src
Single or double quotes around the filename are optional.  However,
if the filename contains commas, semicolons, or parentheses, then it
must be  surrounded  by  single  quotes ' or double quotes ".
Filename may also contain equal signs if it is enclosed in quotes.

If the file is opened by NM-TRAN, filename may contain embedded spaces
if  it  is  enclosed in quotes, and may contain at most 80 characters.
If the file is opened by NONMEM, filename  may  not  contain  embedded
spaces, and may contain at most 71 characters.

  - unit 6, n or *
    + "6" indicates the unit connected to the NONMEM output file.
    + "n" indicates the number of an alternative unit (40<n<2000).
    + "*"  indicates  a FORTRAN system-dependent output (with most systems, this is equivalent to using unit 6, but see  the  FORTRAN documentation) With OPEN, CLOSE and REWIND, the unit may not be 6 or *.

  - format *, 1, 2, 991, or 992  [fn:1] [fn:2]
    + "*" indicates list-directed  output.  (FORTRAN  library
      routines will select a format appropriate for the current
      run-time value of the quantity when displayed.)
    + 1 or 991 requests the built-in format specification: 991  FORMAT (35F14.4)
    + 2 or 992 requests the built-in format specification: 992  FORMAT (35E15.7)

  - list. A  list  of one or more right-hand quantities, i.e.,
    variables or constants that may appear on the right in abbreviated
    code.   May not  include expressions or names of abbreviated
    functions.  When subscripts are appropriate,  these  must  be
    integer  constants, declared  integer  variables,  or expressions
    involving such constants and variables.

    With a PRINT statement, a list may also  include  character
    constants.   A  character  constant is delimited by single or
    double quotes (' or ").  As with any Fortran character constant, a
    pair of  adjacent  delimiters  within the constant represents a
    single character.  E.g.,
    #+begin_src f90
    PRINT *,'A isn''t B'
    #+end_src
    will output
    #+begin_src
    A isn't B
    #+end_src

    In  an  [[file:/docs/user-guide/advanced/abbr_block/#initialization-finalization-block][Initialization or Finalization block]], a list may include
    elements of the OMEGA and SIGMA arrays.  In a finalization block,
    a  list  may  include  elements  of  the  standard  error  arrays
    (SETHET,SETHETR,SEOMEG and SESIGM).

    Any array whose elements may be listed individually in a WRITE or
    PRINT  statement  may also be written in its entirety, by listing
    it without any subscripts.  Specifically, one or more of the
    following may be included in a list:

  #+begin_src f90
        THETA THETAFR SETHET  SETHETR
         THSIMP ETA  THSIMPR
        OMEGA(BLOCK) OMEGA(DIAG) SEOMEG(BLOCK) SEOMEG(DIAG)
        OMSIMP(BLOCK) OMSIMP(DIAG)
        SIGMA(BLOCK) SIGMA(DIAG) SESIGM(BLOCK) SESIGM(DIAG)
        SGSIMP(BLOCK) SGSIMP(DIAG)
        IIDX CNTID IIDX,CNTID
  #+end_src

  Note that IIDX and CNTID are arrays in a module; (See [[file:/docs/reference-manual/api/variables/#ofv-indi][Objective Function Value Individual]]). When  "IIDX"  or "CNTID" is listed, then
  only that array is written.  When "IIDX,CNTID" is specified, then
  pairs  of  values  are written, one pair per line, one pair for each
  individual record.

  The  option  BLOCK  requests  that the entire array be written in
  full symmetric form.  The option  DIAG  requests  that  only  the
  diagonal  elements  be written.  DIAG may also be coded DIAGONAL.
  Arrays of possibly different sizes (e.g., OMEGA  and  SIGMA)  may
  not  be  listed together in the same WRITE statement.  If a WRITE
  statement requests that an entire array be written, then the only
  other  items  that  may  be  listed  with the statement are other
  entire arrays.

  When entire arrays are written, the format specification with a
  WRITE statement  must  be  *.   With  either  a WRITE or PRINT
  statement, an appropriate format is created by the NONMEM system.
  With  these  for mats, elements of the standard error arrays that do
  not exist have the value 1E10 and are printed as 0.1000000E+11.
  (Such elements appear in NONMEM  output  as dots (.........).)  If
  the covariance step fails or is not requested, all elements of the
  standard error arrays are 0  and are printed as 0.0000000E+00. For
  example, to write the omega matrix and its standard errors in
  symmetric form code the following.  (Only as many elements will  be
  written as are appropriate for the dimension of omega in the
  problem.)

  #+begin_src f90
       IF (ICALL.EQ.3) WRITE (99,*) OMEGA(BLOCK),SEOMEG(BLOCK)
  #+end_src

 A  list  may  also  include  a vector element or the entire vector (by listing the vector without a subscript).

 The OPEN, CLOSE, and REWIND statements are part of  the  FORTRAN
 language.  For  details  (i.e.,  the  relationship  of  external
 files to units), see the Language Reference Manual and the Users
 Guide for your compiler.

** =PASS=
#+begin_src f90
CALL PASS(MODE)
#+end_src
may be used only in $PRED
[[file:/docs/user-guide/advanced/abbr_block/#initialization-finalization-block][Initialization-Finalization blocks]], and in $INFN records.  If present,
MODE becomes a reserved variable with type INTEGER, and may not  be
used outside the block(s).

** =SUPP=
#+begin_src f90
CALL SUPP(ie,ic)
#+end_src
=ie= and =ic= are of integer values 0 or 1.  Value 1 of =ie= / =ic=  suppresses  output  from  the
Estimation/Covariance step.  A value 0 does not suppress the output
from the step.  May be used only in $PRED  initialization-finalization
blocks, and in $INFN records.  The =ie= / =ic= value remains in effect
until changed by a call to SUPP.

** =RANDOM=
#+begin_src f90
CALL RANDOM(n,R)
#+end_src
=n=: integer 1-10.  It is the number of the random source. =R=: a
random number from this source.  May be used only in Simulation and
Expectation  blocks.  If present, R becomes a reserved variable with
type REAL, and may not be used outside the block(s).

** =SIMETA=, =SIMEPS=
#+begin_src f90
CALL SIMETA(ETA)

CALL SIMEPS(EPS)
#+end_src
May  only  be  used  in  Simulation
blocks.   Note  that  NM-TRAN  itself provides the minimum necessary
call to SIMETA/SIMEPS.  This statement is used in abbreviated code only  to
obtain  a different value of ETA/EPS, e.g., so that the ETA distribution
may be truncated:
#+begin_src f90
  DO WHILE (ETA(1).GT.5)
     CALL SIMETA(ETA)
  ENDDO
#+end_src

** =RETURN=
#+begin_src f90
   RETURN
#+end_src
may  be  used in all special blocks.  RETURN statements must be used
with caution because they by-pass certain normal  final  actions  of
the routine.

** =PRED_IGNORE_DATA= block
Another  kind  of special block is the pred_ignore_data block, which
may be part of $PRED,$PK, or $INFN blocks.   It  uses  the  reserved
variables  PRED_IGNORE_DATA_TEST  and  PRED_IGNORE_DATA.  By setting
values of PRED_IGNORE_DATA=1 for certain  data  records,  it  causes
these records to be dropped from the NONMEM data set.  Ordinary
Fortran syntax is used in such blocks.

(See [[file:/docs/user-guide/advanced/abbr_block/#pred_ignore_data_block][PRED_IGNORE_DATA]] block)


** =PROTECT=
Since NONMEM  7.4,  a  series of routines are available that protect
against domain violations, divide by zero, and  floating  point
overflows.   Each  of  these routines start with the letter P,
followed by the name of the mathematical operation they are to
perform.  For example,  PLOG is the protective code routine that
performs the LOG operation.  In addition, there are first derivative
(such as  PLOGD1),  and second  derivative (such as PLOGD2) companion
routines available which NMTRAN uses for computing analytical
derivatives. The source  code  of these routines are available in
..\source\PROTECT.f90.  If you wish to modify their behavior, then
copy PROTECT.f90 to your run directory  as (say)  myprotect.f90,
modify it, then refer to this modified code with $SUBROUTINES
OTHER=myprotect.f90 (The OTHER option is  not  needed  if the P
functions are coded explicitly or implicitly via $ABBR PROTECT.)

The following protective code routines are available. For  all
routines, if X=not a number, X is converted to machine precision
value, which is about 1.0E-15,  before performing an operation on it.
If  X>INFNTY (where INFNTY is approximately 1.0E+154), then X is
converted to INFNTY before an operation is performed on it.

- PLOG(x):  returns LOG of x.  If x<SMALLZ, where SMALLZ is
  approximately 2.8E-103, then LOG(SMALLZ) is returned.


- PLOG10(x):   returns  LOG10  of  x.  If x<SMALLZ, where SMALLZ is
  approximately 2.8E-103, then LOG10(SMALLZ) is returned.


- PSQRT(x): returns SQRT of x.  If x=0.0d+00, then 0 is returned.


- PEXP(x): returns EXP  of  x.   If  x>40.0,  then  PEXP(100.0)  is
  returned (avoids overflow).


- PDZ(x):  returns  1/x  .   Protects  against  divide by zero.  If
  abs(x)<SMALLZ, then 1/SMALLZ is returned.


- PZR(x): returns x.  protects  against  zero.   If  abs(x)<SMALLZ,
  then SMALLZ is returned.


- PNP(x):  returns x.  Protects against non-positive.  If X<SMALLZ,
  then SMALLZ is returned.


- PHE(x): returns x. Protects against  high  exponent.   If  X>100,
  then 100 is returned. Thus PEXP(x)=EXP(PHE(x)).


- PNG(x):  returns  x.   Protects against negative.  If X<0.0, then
  0.0 is returned.


- PTAN(x): returns tan(x). Protects against returning  infinity  on
  inputs near pi/2.


- PATAN(x): returns atan(x). Protects against large intputs.


- PACOS(x),  PASIN(x):  returns acos(x), asin(x), respectively.
  If |X| is between 1.0 and 1+10**(-08), then x is submitted as  1  or
  -1.  So, "dirty ones" are cleaned up, but values clearly beyond 1
  are allowed to trip up the function, so the user is aware of  the
  logical error in the code, and fix the issue.


Instead of replacing various operations with protected code operations by hand, you can ask NMTRAN to automatically convert your code to protected code with the following statement:

#+begin_src perl
$ABBR PROTECT
#+end_src

NMTRAN will automatically replace all LOG (or DLOG) with PLOG, EXP (or
DEXP) with PEXP, SQRT (or DSQRT) with PSQRT, / operations with *PDZ(),
and B**E operations with PEXP(E*PLOG(B)), and so on.

Note  that  the any P function name that is used explicitly or
implicitly via $ABBR PROTECT may not be used  for  a  user-defined
variable name.
