---
title: "Output and files"
author: ["Yi Zhang"]
draft: false
bookCollapseSection: false
weight: 14
---
{{< katex >}}{{< /katex >}}

* Output files and quantities
** NM-TRAN output files
:PROPERTIES:
:CUSTOM_ID: nmtran_output
:END:

NM-TRAN  produces  several  output  files,  some of which are input
files to NONMEM itself.

| File name | Relevant portion of NM-TRAN inputs                         | How file is used              |
|---------+-------------------------------------------+-------------------------------|
| FCON    | All                                       | NONMEM (control stream)       |
|---------+-------------------------------------------+-------------------------------|
| FDATA   | Data file, $DATA, $INPUT                  | NONMEM (data file)            |
|---------+-------------------------------------------+-------------------------------|
| FSTREAM | Filenames from $DATA,$MSFI, $MSFO, $TABLE | NONMEM (file control stream)  |
|---------+-------------------------------------------+-------------------------------|
| FSUBS   | Abbreviated code                          | Generated FORTRAN subroutines |
|---------+-------------------------------------------+-------------------------------|
| FREPORT | $SUBROUTINES                              | Input  to  whatever generates the commands that create  the NONMEM  executable. See also $SUBROUTINES.
|---------+-------------------------------------------+-------------------------------|
| FORIG   | Abbreviated code, $ABBR                   | When $ABBR REPLACE  is  used,this file contains the original abbreviated code.         |
|---------+-------------------------------------------+-------------------------------|
| FREPL   | Abbreviated code, $ABBR                   | When $ABBR REPLACE  is  used, this  file contains the postreplacement abbreviated code.|
|---------+-------------------------------------------+-------------------------------|
| FWORK   | Data file                                 | NM-TRAN (work file)           |
|---------+-------------------------------------------+-------------------------------|
| FWARN   | All                                       | Warning   and   informational messages.                     |
|---------+-------------------------------------------+-------------------------------|
| FSIZES  | Abbreviated code, $THETA, $OMEGA,  $SIGMA,$SIZES, SIZES.f90                        | Dynamic  array sizes for NONMEM. The file is for user consumption only.  =SUBROUTINE FSIZESR= in FSUBS is  what  is  actually  used during the NONMEM run. |
|---------+-------------------------------------------+-------------------------------|
| prsizes | Abbreviated code, $THETA,  $OMEGA, $SIGMA, $SIZES, SIZES.f90                       | Static array sizes for PREDPP |

With NONMEM 7, files FSUBS2 and FSUBS_MU are used by  NMTRAN  as  work files during the creation of FSUBS.

 REFERENCES: Guide Introduction_7


** NONMEM control stream
:PROPERTIES:
:CUSTOM_ID: nm_control_stream
:END:

Instructions to NONMEM,  the collection of which is called the //NONMEM// control
stream. They are different from //NM-TRAN// control records.

An NM-TRAN run creates NONMEM control stream in file FCON.
Alternatively user can create the FCON file directly.

Each  NONMEM  control  record  begins  with a 3 or 4-character preface
("record label").  They are listed  below  in
the same order in which they must appear in the NONMEM control stream.

 | Record type   | Prefix | Corresponding NM-TRAN record |
 |---------------+--------+------------------------------|
 | FILE          | FILE   | none                         |
 | SUPER PROBLEM | SUPR   | $SUPER                       |
 | PROBLEM       | PROB   | $PROBLEM                     |
 | DEFAULT       | DFLT   | $DEFAULT                     |

 Data set specification records
 | Record type   | Prefix | Corresponding NM-TRAN record |
 |---------------+--------+------------------------------|
 | DATA          | DATA   | $DATA                        |
 | ITEM          | ITEM   | $INPUT                       |
 | INDEX         | INDX   | $INDEX                       |
 | LABEL         | LABL   | $INPUT,$TABLE,$SCATTER       |
 | EXTRA EVID    | XVID   | $INPUT                       |
 | FORMAT        | FORM   | $DATA                        |

 Model specification records
 | Record type | Prefix | Corresponding NM-TRAN record |
 |-------------+--------+------------------------------|
 | FIND        | FIND   | $MSFI                        |
 | VERSION     | MSFV   | $MSFI                        |
 | STRUCTURE   | STRC   | $THETA, $OMEGA, $SIGMA       |
 | LEVEL       | OLEV   | $LEVEL                       |

 Initial estimate records
| Record type      | Prefix | Corresponding NM-TRAN record |
|------------------+--------+------------------------------|
| THETA CONSTRAINT | THCN   | $THETA                       |
| THETA            | THTA   | $THETA                       |
| LOWER BOUND      | LOWR   | $THETA                       |
| UPPER BOUND      | UPPR   | $THETA                       |
| DIAGONAL         | DIAG   | $OMEGA, $SIGMA               |
| BLOCK SET        | BLST   | $OMEGA, $SIGMA               |
| ETA VALUES       | ETA    | $ETAS                        |
| PHI VALUES       | PHI    | $PHIS                        |
| CHAIN            | CHN    | $CHAIN                       |
| CHAIN FILE       | CFIL   | $CHAIN                       |
| CHAIN DELIMITER  | CDLM   | $CHAIN                       |
| CHAIN Order      | ORDR   | $CHAIN                       |
| CHAIN PARAFILE   | CHFL   | $CHAIN (not used)            |
| OMEGA VALUES     | ANNL   | $ANNEAL                      |

 Task specification records
| Record type            | Prefix | Corresponding NM-TRAN record |
|------------------------+--------+------------------------------|
| SIMULATION             | SIML   | $SIMULATION                  |
| RANDOM SOURCE          | SORC   | $SIMULATION                  |
| SIMULATION PARAFILE    | SFIL   | $SIMULATION                  |
| ESTIMATION             | ESTM   | $ESTIMATION                  |
| ESTIMATION             | BEST   | $ESTIMATION                  |
| ESTIMATION PARAFILE    | BFIL   | $ESTIMATION                  |
| ESTIMATION PARAFILE    | PFIL   | $ESTIMATION                  |
| ESTIMATION FPARAFILE   | FFIL   | $ESTIMATION                  |
| ZERO                   | ZERO   | $ESTIMATION                  |
| OMIT                   | OMIT   | $OMIT                        |
| ESTIMATION GRID        | GRID   | $ESTIMATION                  |
| NONPARAMETRIC          | NONP   | $NONPARAMETRIC               |
| COVARIANCE             | COVR   | $COVARIANCE                  |
| COVARIANCE             | COVT   | $COVARIANCE                  |
| COVARIANCE PARAFILE    | CPAR   | $COVARIANCE                  |
| COVARIANCE SIRPARAFILE | SPAR   | $COVARIANCE                  |
| TABLE                  | TABL   | $TABLE                       |
| TABLE PARAFILE         | PPAR   | $TABLE                       |
| SCATTERPLOT            | SCAT   | $SCATTERPLOT                 |

 Output specification records
| Record type                  | Prefix | Corresponding NM-TRAN record |
|------------------------------+--------+------------------------------|
| ESTIMATION DELIMITER         | BDLM   | $ESTIMATION                  |
| ESTIMATION MUM               | BMUM   | $ESTIMATION                  |
| ESTIMATION GRD               | BGRD   | $ESTIMATION                  |
| ESTIMATION ORDER             | ORDR   | $ESTIMATION                  |
| LFORMAT                      | FRML   | $TABLE                       |
| RFORMAT                      | FRMR   | $TABLE                       |
| ADDITIONAL DIAGNOSTIC LABELS | LBW1   | $TABLE,$SCATTER              |
| SYMBOLIC LABELS              | LTHT   | $ABBR REPLACE                |
| SYMBOLIC LABELS              | LETA   | $ABBR REPLACE                |
| SYMBOLIC LABELS              | LEPS   | $ABBR REPLACE                |

For details of FCON control record, see Guide V, Appendix 4.
and Guide I, section B.2.


** NONMEM file control records
 Names of optional files to be opened by NONMEM is stored in a file
 specified on the FILE record of the NONMEM Control Stream. NM-TRAN
 creates uses "FSTREAM" for this file.

 Each NONMEM File Control Record  begins  with  a  4-character  preface
 (record label) which identifies the record.

 | Record type                       |Prefix   |Corresponding NM-TRAN record |
 |-----------------------------------|---------|-----------------------------|
 | DATA                              |DATA     |$DATA ...                    |
 | MODEL SPECIFICATION FILE INPUT    |MSFI     |$MSFI ...                    |
 | MODEL SPECIFICATION FILE OUTPUT   |MSFO     |$ESTIMATION MSFO=...         |
 | TABLE                             |TABL     |$TABLE FILE=...              |
 | Problem delimiter                 |* * * *  |none                         |

 Multiple  TABLE  records  may  be present for a given problem, one for
 each table to be written to a new table file.

 REFERENCES: Guide I, section B.3

** NONMEM output files
 NONMEM produces several output files.

 First  is  the NONMEM report file.  The name of this file is
 specified by the user on the nmfe command.  Help entries  describe
 the  various sections of the report.

 (See DATA_SET,DATA_RECORDS,DATA_ITEMS).

 (See INITIAL_ESTIMATE,MONITORING_OF_SEARCH).

 (See MINIMUM_VALUE_OF_OBJ._FUNCTION,FINAL_PARAMETER_ESTIMATE).

 (See ETABAR,STANDARD_ERROR_OF_ESTIMATE).

 (See SHRINKAGE).

 (See CORRELATION_MATRIX_OF_ESTIMATE,COVARIANCE_MATRIX_OF_ESTIMATE).

 With  NONMEM  7,  tag labels are present in the report file to allow
 a third-party program to find the  appropriate  positions  in  the
 file without  having  to  search  for  specific words in the text.
 (a more efficient way of extracting numerical results  from  the
 analysis  is from  the  raw  and  additional output files (see
 below)).

 |Tag labels   | Comment|
 |-------------+--------|
 |#PARA (NM72) | This tag identifies the parallelization file and number of  nodes used, if parallel estimation is performed.|
 |#TBLN (NM72) | This  tag  specifies that following it, on the same line, will be found an integer that refers to the  number  of  this  estimation method.  This number is also the table number listed in the title to tables in the various output files  (raw  output  file,  .cov, .cor, etc).  The table number is incremented for each $EST statement, across all problems in the control stream file.|
 |#METH        | This tag specifies that following it, on the same line,  will  be found  a  text that describes the method, for example First Order Conditional Estimation Method with Interaction.|
 |#TERM        | This tag  indicates  that  beginning  on  the  next  lines,  text describes the termination status of the analysis.|
 |#TERE        | This  tag  indicates the end of the lines describing the termina- tion status of the analysis.  Thus, a software program may trans- fer all lines between #TERM: and #TERE: to a summary file.|
 |#OBJT        | Indicates  that  following  it,  on  the  same  line, is the text describing the objective  function,  such  as  Minimal  Value  Of Objective Function.|
 |#OBJV        | Indicates  that  following it, on the same line, is the objective function value.|
 |#OBJS        | Indicates that following it, on the same line, is  the  objective function standard deviation (MCMC Bayesian analysis only).|
 |#OBJN (NM73) | Indicates that following it, on the same line, is the nonparamet- ric objective function value.|
 |#CPUT (NM73) | Total CPU time.  It is an accurate representation of the computer usage, whether single or parallel process.  The same problem when run singly or in parallel will report a similar cpu  time.   This is  in  contrast with elapsed time, which is improved with parallelization.|

** Raw output file
 With  NONMEM 7, a NONMEM run produces several additional output
 files. These provide a more efficient way  of  way  of  extracting
 numerical results  from  the  analysis  than  by  obtaining them from
 the NONMEM report file.

 Names of the files start with "root", where root is the root name
 (not including  extension)  of the NM-TRAN control stream file given
 at the nmfe7 command line, or root="nmbayes" if the control stream
 file  name is  not passed as an argument to the NONMEM executable.
 E.g., in this example the root is myexample.
  #+begin_src sh
 nmfe7 myexample.ctl myexample.res
 #+end_src
 The raw output file ("root.ext") will be named myexample.ext

 A different name for this file may be specified using  the
 FILE=filename  option of the $ESTIMATION record.  This filename is
 used for all subsequent problems, until a new FILE=filename option is
 coded.   The raw output file is only generated if the $ESTIMATION
 record is present and accumulates information from each Estimation
 step.

 The first two lines of each file is the same.  First is a header  line that begins with the word TABLE, such as:

 #+begin_src txt
 TABLE NO.     n:
 #+end_src

 These  tables  are  not  related  to  the  ones produced by the
 $TABLE record.  The value of n is incremented each time the
 Estimation  Step is  implemented,  i.e.,  once per $ESTIM record,
 when MAXEVAL is not 0 and $EST is not omitted.  The $EST records may
 be in the same problem, or  in  subsequent  problems.  If $COV is
 present in a problem without $EST (e.g., when $MSFI is used), then n
 is also incremented.

 Next on the header line is the analysis text (same  as  given  on
 the #METH: line in the report file), e.g., "First Order".

 In  the  raw  output  file,  the analysis text is followed by the goal function text (same as given on the #OBJT: line in the  report  file), e.g.,
 #+begin_src txt
 Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION
 #+end_src
 At the end of the header line is:
 #+begin_src txt
 Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0
           Superproblem2=0 Iteration2=0
 #+end_src

 The  values  of Problem, Subproblem, Superproblem1, Iteration1,
Superproblem2, Iteration2 are the same values as would be found in the
following variables in modules during the run:
#+begin_src txt
IPROB IREP S1NUM S1IT  S2NUM S2IT
#+end_src
 (See Problem_Iteration_Counters).

 The second line of the raw output file contains the column headers for the table, all on one line.

 Options NOTITLE and NOLABEL and FORMAT of the $ESTIMATION  record  can be  used  to  supress the first and/or second lines, and to modify the format of the values in the table.  They apply to raw  and  additional output  files,  but only for the current Estimation Step.  The options must be re-specified with each $EST record.

 Values of the Parameters and of the  objective function are printed to the raw output file every PRINT iterations.  The default order is: ITERATION  THETA,  SIGMA,  OMEGA, OBJ (Objective function).  Values of Sigma and Omega  are in the original parameterization, as in the  file INTER.   The  option  ORDER  of  the $ESTIMATION record may be used to change the order of THETA, SIGMA, and OMEGA.
 (See order_option).

 The iteration number, which is the first value in every line, is
 typically  positive,  but  also may be negative under the following
 conditions:

      - The burn-in iterations of the MCMC Bayesian analysis are given
        negative values, starting at -NBURN, the number of burn-in
        iterations requested by the user.   These  are  followed  by
        positive iterations of the stationary phase.

      - The stochastic iterations of the SAEM analysis are given
        negative values.  These are followed by positive  iterations
        of  the accumulation phase.

      - Iteration  -1000000000  (negative one billion) identifies the
        line that contains the final result (thetas, omegas, and
        sigmas, and  objective  function)  of the particular analysis.
        These are the value in the NONMEM  output  file  that  are
        labelled  FINAL PARAMETER ESTIMATE.  The order is theta,
        sigma, omega.

      - Iteration  -1000000001  identifies the line that contains the
        standard errors of the final population  parameters.   These
        are the  value  in  the NONMEM output file that are labelled
        STANDARD ERROR OF ESTIMATE.  The order is theta, sigma, omega.
        This  line is  present  if  the  Covariance  Step  is
        successful,  or  with METHOD=BAYES.

      - Iteration -1000000002 identifies the line  that  contains  the
        eigenvalues  of  the  correlation  matrix of the variances of
        the final parameters.

      - Iteration -1000000003 identifies the line  that  contains
        thet condition  number  , lowest, highest, Eigenvalues of the
        correlation matrix of the variances of the final parameters.

      - Iteration -1000000004 identifies the line  that  contains  the
        OMEGA and SIGMA elements in standard deviation/correlation
        format.

      - Iteration  -1000000005  identifies the line that contains the
        standard errors to the OMEGA and SIGMA elements in standard
        deviation/correlation format.

      - Iteration -1000000006 identifies the line that indicates 1 if parameter was fixed in estimation, 0 otherwise.

      - Iteration -1000000007 lists termination status  (first  item) followed by termination codes.
        In nm73, termination status catalogs the error status. For
        traditional analyses, an error number is listed. If negative,
        the analysis was user-interrupted. For EM/Bayes analysis, error numbers map as follows:
           + 0,4: optimization was completed
           + 1,5: optimization not completed (ran out of iterations)
           + 2,6: optimization was not tested for convergence
           + 3,7: optimization was not tested  for  convergence  and  was user interrupted
           + 8,12:  objective  function  is  infinite  or  all individual objective fuctions are zero. problem ended
           + 16,20: All individual objective fuctions are  zero.  problem ended
           + 4,5,6,7,12,20: reduced stochastic/stationary portion was not completed prior to user interrupt

      - Iteration -1000000008 lists the  partial  derivative  of  the likelihood  (-1/2OFV)  with  respect to each estimated parameter. This may be useful for using tests like the  Lagrange  multiplier test.

      See the description of root.xml in Guide INTRODUCTION TO NONMEM 7 for versions 7.4 and higher.

A file simliar to the raw output file is root.cnv.  This file contains convergence information for the Monte Carlo/EM methods, if CTYPE>0:

      - Iteration  -2000000000  identifies the line that contains the
        mean of last CITER values (mean objective  function  is  that
        of second to last CITER values)

      - Iteration  -2000000001  identifies the line that contains the
        standard deviation of last CITER values (for objective
        function, STD of second to last CITER values)


      - Iteration  -2000000002  identifies the line that contains the
        linear regression p-value of last CITER values against
        iteration number.  (for objective function, p-value of second
        to last CITER values)


      - Iteration -2000000003 identifies the line  that  contains  the
        Alpha used to assess statistical significance (p-value<alpha)

      Please note the following: The Sigma values are in their Cholesky
      format, as this is the form in which convergence of these  values
      are  tested.  The Alpha are those based on ones actually used for
      convergence test of that parameter, or which would have been used
      on that parameter if CTYPE were of proper type.  The alpha may be
      bonferoni corrected because of multiple comparisons, depending on
      number  of parameters that were tested or would have been tested.
      Objective function alphas are not bonferoni corrected.

      For importance sampling and  iterative  two  stage,  the  average
      objective  function listed in root.cnv could be used as an alter-
      native to the  final  objective  function  for  likelihood  ratio
      tests.

REFERENCES: Guide Introduction_7

** Additional output files
  - root.ext
      Always.  (See above "raw output file").

  - root.phi
      Always.   Individual phi parameters (phi(i)=mu(i)+eta(i), for ith
      parameter), and their variances phc(,).  For  parameters  not  MU
      referenced  phi(i)=eta(i).  When  a classical method is performed
      (FOCE, Laplace), then mode of posterior eta(i) are  printed  out,
      along  with  their Fisher information (first order expected value
      for FOCE, second order for Laplace)  assessed  variances  etc(,).
      For ITS, these parameters are the modes of the posterior density,
      with first-order approximated expected variances (or second order
      variances  if  $EST METHOD=ITS LAPLCE is used).  For IMP, IMPMAP,
      SAEM methods, they are the Monte Carlo evaluated conditional mean
      parameters  and  variances  of the parameters under the posterior
      density.  For MCMC Bayesian, they are random  single  samples  of
      phi(),  as of the last position. Their variances are zero.  Individual objective function values (obji) are also produced.  As of
      NONMEM 7.4, if $EST PHITYPE=1 is specified, then conditional mean
      etas are reported in the phi table. regardless  of  the  analysis
      method.

  - root.iph (NM75)
      As of nm75, samples of phi/eta are collected at each BAYES iteration, and summarized to provide conditional mean phi and phc() in
      the  root.phi table, as described above. By default, the individual phi values from each iteration are not  stored.  However,  if
      you set
      $EST ... BAYES_PHI_STORE=1
      then  phi and eta values from each BAYES iteration will be stored
      in root.iph. For non-mixture problems, only records of SUBP=0 are
      recorded,  as  there are no sub-population divisions. For mixture
      problems, the SUBP=0 records contain the composite phis and  etas
      (the  average  of these across all non-negative iterations are in
      the root.phi table), and the SUBP>0 records contain the phis  and
      etas  appropriate  to  each  sub-population  SUBP (the average of
      these across all non- negative iterations are in the root.phm table).  The  root.iph file can become quite large, so it should be
      used only on the final analysis.

  - root.phm (NM72)
      Individual phi/eta/obji parameters per sub-population.  This file
      is  only  produced  in  $MIXTURE  problems.  As of nm75, for MCMC
      Baysian analysis, the items listed in this table consist  of  the
      average  values  among  all  the iterations during the stationary
      distribution phase. Before nm75, the values consisted  of  values
      from the last MCMC iteration.

  - root.shk (NM72)
      This  file presents composite eta shrinkage and epsilon shrinkage
      information, the same as given in the NONMEM report file  between
      the  #TERM:  and #TERE: tags, but in rows/column format, and with
      adjustable formatting.
      (See shrinkage).

  - root.shm (NM73)
      This file is a shrinkage map describing which etas were  included
      or excluded in the eta shrinkage assessment.  (See shrinkage).

  - root.grd (NM72)
      Gradient values for classical NONMEM methods.  Always.

  - root.xml (NM72)
      An  XML markup version of the contents of the NONMEM report file.
      The rules by which it is constructed are given in output.xsd  and
      output.dtd.

  - root.cov
      Full  variance-covariance  error  matrix  of  thetas, sigmas, and
      omegas.  Same as "COVARIANCE MATRIX OF ESTIMATE"  in  the  NONMEM
      report  except  that  it  is full (NONMEM displays only the lower
      triangle), elements that are fixed or not estimated are displayed
      as  0  (NONMEM  displays  them  as .....), and, when the data are
      individual, sigma is displayed as  0  (NONMEM  does  not  display
      sigma  at  all.)   Only  generated  if  the $COVARIANCE record is
      present.
      (See covariance matrix of estimate).
      (See Covariance_Output_files).
      (See order_option).

  - root.clt (NM74)
      The lower-triangular portion of the  variance-covariance  of  the
      parameter  estimates  reported  in root.cov. This is provided for
      easier pasting of the information as theta priors  for  a  subsequent  analysis.   Only  generated  if  the $COVARIANCE record is
      present.

  - root.cor
      Full correlation matrix of thetas, sigmas, and omegas.   Same  as
      "CORRELATION   MATRIX  OF  ESTIMATE",  except  as  described  for
      root.cov.
      (See correlation matrix of estimate).

  - root.coi
      Full inverse covariance matrix (Fischer information  matrix)  for
      thetas,  sigmas,  and omegas.  Same as "INVERSE COVARIANCE MATRIX
      OF ESTIMATE" except as described for root.cov.

  - root.cnv (NM72)
      Convergence  information  for  the  Monte  Carlo/EM  methods,  if
      CTYPE>0.
      (See raw_output_file).

  - root.smt (NM72)
      Contains the S matrix, if  $COV step failed.

  - root.rmt (NM72)
      Contains the R matrix, if  $COV step failed.

  - root.imp (NM73)
      Produced if the user selects importance sampling with option IACCEPT=0.0.  Contains the final IACCEPT and DF values  that  NONMEM
      selected for each subject.

  - root.npd (NM73)
      For  NONPARAMETRIC method.  Each row contains information about a
      support point.

  - root.npe (NM73)
      For NONPARAMETRIC method.  The expected value etas  and  expected
      value  eta  covariances (ETC) are listed for each problem or subproblem.

  - root.npi (NM73)
      For  NONPARAMETRIC  method.   The  individual  probabilities  are
      listed.  Each row contains information about a support point.

  - root.npl (NM74)
      For  NONPARAMETRIC  method.  The individual data likelihoods (not
      including the parameter density) are listed in this file.

  - root.fgh (NM73)
      This file is produced  if  the  user  selects  $EST  NUMDER=1  or
      NUMDER=3.   The  file lists the numerically evaluated derivatives
      of Y with respect to eta, where

      F=Y (the prediction)
      G(I,1)=partial Y with respect to eta(i))
      G(I,J+1)=Second derivatives of Y with respect to eta(i),eta(j)
      H(I,1)=partial Y with respect to eps(i)
      H(i,j+1)=partial Y with respect to eps(i),eta(j)

      The values are those used in the Estimation Step.   Values  of  F
      are  computed  by PRED with eta=0 if METHOD=0 is used;  otherwise
      they are computed with non-zero etas: the Conditional (CPE) etas,
      empirical  bayes  estimates  (EBE), mode a posteriori (MAP) estimates) or conditional mean  etas,  depending  on  the  Estimation
      Method.   Values  of  G are computed by NONMEM via finite differences using these values of F and eta.  Values of H are  computed
      by  NONMEM  with  the  same values of F and eta if INTERACTION is
      specified; otherwise, they are computed with eta=0.

  - root.agh (NM73)
      This file is produced  if  the  user  selects  $EST  NUMDER=2  or
      NUMDER=3.   The file lists the analytically evaluated derivatives
      of Y with respect to eta.  The format and order is  the  same  as
      file  root.fgh.  The values are those returned by subroutine PRED
      in arguments F, G, and H.  These are 0 if not computed  by  PRED.
      (E.g.  second  derivatves  are  not  computed analytically with a
      method other than  LAPLACIAN.)   Values  in  root.agh  correspond
      exactly  to  those  in  root.fgh.  That is, values of F and G are
      from calls to PRED with eta=0 or with non-zero etas, as described
      above.   Values  of H are from calls to PRED with the same values
      of eta if INTERACTION is  specified;  otherwise,  they  are  from
      calls to PRED with eta=0, regardless of the Estimation method.

  - root.vpd (NM74)
      This file is produced if the $TABLE file option VARCALC=1 or VARCALC=2 is used.  It is the full variances- covariances among  all
      user-defined  and  PREDPP  parameters.   The FORMAT used for this
      file is that defined in the $EST record.

  - root.ets (NM74)
      As of NM74, one can obtain random samples of individual etas, and
      uses  these  for  covariate  and  model diagnostics.  $EST option
      ETASAMPLES=1 causes individual ISAMPLE  random  eta  samples  per
      subject,  to  be written to  root.ets, where root is the root name
      of the control stream file.
      See "Stochastic  Approximation  Expectation  Maximization  (SAEM)
      Method" in Guide Introduction_7.

  - root.bfm (NM75)
      When  OFVTYPE=8  during  optimal  design  ($DESIGN OFVTYPE=8) the
      progress of average  individual  conditional  variances  (average
      empirical  Bayes  conditional variance) are shown in the root.bfm
      file (where root is name of control stream file), and  the  final
      one on the -1000000000 line, during an optimization. The RAW file
      (by default named root.ext) which shows only  the  starting,  and
      final  values of the standard errors of population parameters, as
      extra information.

  - root.cpu (NM73)
      The cpu time in seconds is reported in this file.  It is an accurate representation of the computer usage, whether single or parallel process.  The same problem when run singly or  in  parallel
      will report a similar cpu time.  This is in contrast with elapsed
      time, which is improved with parallelization.

 With NONMEM 7.3 and higher, the $THETAI and  $THETAR  records  may  be
 used  to transform initial and final estimates of THETA, respectively.
 This will affect values in the .ext, .cov, etc. files
 (See $thetai, $thetar)

REFERENCES: Guide Introduction_7


** Output quantities
*** PRED-defined items
PRED-defined items, including PK-defined and ERROR-defined items can
be displayed in tables and scatterplots. They  are computed many times
during a NONMEM run, with various values of THETA and ETA.  It is
important to know which values  are  used in the computation of the
items as displayed.

Consider this fragment of an NM-TRAN control stream:
#+begin_src perl
   $PK
   CL=THETA(1)*EXP(ETA(1))
   $TABLE CL ETA(1)
#+end_src
ETA(1) and the PRED-defined item CL that are displayed depend on task specification records.

 | Task specification records        | THETA   | Displayed values     |                      |
 |-----------------------------------+---------+----------------------+----------------------|
 |                                   |         | ETA(1)               | CL                   |
 |-----------------------------------+---------+----------------------+----------------------|
 | None                              | initial | 0                    | typical              |
 |-----------------------------------+---------+----------------------+----------------------|
 | $EST (or $MSFI) METH=0            | final   | 0                    | typical              |
 |-----------------------------------+---------+----------------------+----------------------|
 | $EST (or $MSFI) METH=1 or POSTHOC | final   | conditional  (CPE)   | conditional(CPE)     |
 |-----------------------------------+---------+----------------------+----------------------|
 | $SIMULATION                       | initial | 0                    | typical              |
 |-----------------------------------+---------+----------------------+----------------------|
 | $SIMULATION  ... ONLYSIM          | initial | simulated [fn:1]      | simulated            |
 |-----------------------------------+---------+----------------------+----------------------|
 | $NONPARAMETRIC ETAS               | final   | nonparametric (CNPE) | nonparametric (CNPE) |
 |-----------------------------------+---------+----------------------+----------------------|

- Displayed etas are the simulated etas  if  the  simulated  etas  are
  stored  in  common  NMPRD7. This is the case when NM-TRAN is used.
  If they are not stored in NMPRD7, displayed etas are all 0.


- Displayed values of PRED, RES, and WRES are always computed with
  typical values of parameters, except as noted below.


- Displayed  values  of  DV  are  simulated  values  when $SIMULATION
  is present.

- With NONMEM 7, Additional types of PRED, RES, and WRES values  may
  be requested  than  the  usual  set  available in NONMEM VI.  They
  may be specified at any $TABLE command or  $SCATTER  command,  as
  one  would request  PRED, RES, or WRES items.  Such items are
  supplied internally by NONMEM, and in the case of L2 data, more
  accurately.  An example of their use is in Example #4a, below.

- Every NONMEM output report contains the line:
  #+begin_src txt
  THE FOLLOWING LABELS ARE EQUIVALENT
  Subsequent  lines  show the relationship of such items for the current
  Estimation method.
  (See $table, $scatter).
  (See PRED,RES,WRES).
  See INTRODUCTION TO NONMEM 7, $TABLE: Additional Statistical  Diagnostics, Associated Parameters, and Output Format
  #+end_src

- Suppose that marginal items appear.  If this item is 1 or 2 on a
  given record, the values of PRED  and  any  PRED-defined  displayed
  item  D (assuming  D  is  not  in the SAVE region (See comsav)
  associated with this record) are determined as follows:

  + If the Simulation Step is implemented, and ONLYSIMULATION is
    specified,  the  PRED  item  is the simulation expectation of F,
    over the simulated values of eta for all the  individuals  in  the
    data  set (including those individuals with no observation
    records), and the D item is the simulation expectation of the
    variable D.

  + If conditional estimates are obtained (e.g.  with  the  use  of
    the POSTHOC  option),  the  PRED item is the posterior expectation
    of F, over the conditional estimates of eta for  all  individuals
    in  the data set (that have some observation records), and the D
    item is the posterior expectation of the variable D.

  + Otherwise, the PRED and D items are the same as with a marginal
    item of 0 (see description above).

- Suppose  that  the  raw-data  items  appear.   If this is 1 on a
  given record, the values of the DV, RES, and any PRED-defined
  displayed item D  (assuming D is in the SAVE region (See comsav)
  associated with this record) are determined as follows: the data
  record serves as a template record.  The DV item  appearing in  a
  table or scatterplot is the raw-data-average of the values of DV in
  observation records matching the  template  record.   The  RES item
  is  the  difference between the PRED item and this average.  A
  PRED-defined item D is the average of the values of D obtained  with
  observation records matching the template.

(See mrg, raw, template).

- Example 1: output typical and conditional values using different variables.
  #+begin_src perl
   $PK
    ...
   TVCL=THETA(1)
   CL=TVCL*EXP(ETA(1))
   $ESTIM  ... POSTHOC ...
   $TABLE TVCL CL
  #+end_src
  TVCL is a typical value by definition. CL is a conditional value.

- Example 2: output typical and conditional values of the same variables.
  #+begin_src perl
   $PK
    ...
   CL=THETA(1)*EXP(ETA(1))
   IF (COMACT.EQ.1) TVCL=CL
   $ESTIM  ... POSTHOC ...
   $TABLE TVCL CL
  #+end_src
  TVCL  is  a  SAVE  variable  because it is defined in a copying
  block. During the copying pass with COMACT=1, it is set to the
  typical  value of CL, because when COMACT=1, etas are 0.  Were the
  values of TVCL not stored in the SAVE region, then during the
  copying pass to obtain values for tables and with COMACT=2, TVCL
  would retain its value set with the previous data record. The first
  column of the table is labelled TVCL and contains the  typical value
  of CL, and the second column contains the conditional value.

- Example 3:  output  typical and conditional values of the
  prediction, and the individual residual and weighted residual
  values.
  #+begin_src perl
   $ERROR
   IPRED=F
   IRES=DV-IPRED
   IWRES=IRES/IPRED
   Y=F+EPS(1)
   $ESTIM  ... POSTHOC ...
   $TABLE IPRED IRES IWRES
  #+end_src
  The IPRED column contains the conditional value of F ("individual
  prediction").   (F is not a left-hand quantity and cannot be
  specified in a $TABLE or $SCATTERPLOT record.)  The PRED column
  contains the  typical  value.   The IRES column contains the
  "individual residual".  The IWRES column contains a value which is
  proportional to (but not  equal to) the "individual weighted
  residual".

  If  predicted  values  of  F may be zero, then division by zero can
  be avoided by code such as the following.
  #+begin_src perl
   $ERROR
   IPRED=F
   IRES=DV-IPRED
   DEL=0
   IF (IPRED.EQ.0) DEL=1
   IWRES=(1-DEL)*IRES/(IPRED+DEL)
   Y=F+EPS(1)
  #+end_src

- Example 4: output intra-individual weighted residual. Assume
  constant CV intraindividual error model, to output weighted
  intra-individual residual that is used during Estimation when the
  FOCE method without interaction is used.
  #+begin_src perl
   $ERROR
   Y=F+F*EPS(1)
   IPRED=F
   IF (COMACT.EQ.1) FT=F
   IF (FT.NE.0) WR=(DV-IPRED)/FT/SQRT(SIGMA(1,1))
   IF (IPRED.NE.0) WR2=(DV-IPRED)/IPRED/SQRT(SIGMA(1,1))
   $ESTIM METHOD=COND
   $TABLE FT IPRED WR WR2
  #+end_src
  IPRED is the conditional estimate of F.
  FT is a SAVE variable because it is defined in a copying block.
  During  the copying pass with COMACT=1, it is set to the typical
  value of F, because when COMACT=1, etas are 0.   Were  the  values
  of  FT  not stored in the SAVE region, then during the copying pass
  to obtain values for tables and with COMACT=2, FT would retain its
  value  set  with the previous data record.

  WR  is  the weighted intraindividual residual with no eta-eps
  interaction.  It is defined in a conditional assignment since it is
  possible that  the typical value of F is zero with some
  non-observation record. (With previous versions of the help guide
  the SIGMA term  was  omitted and the WR was proportional to the
  weighted intraindividual residual.) It is a no-interaction residual
  because  the  denominator  term,  the residual   standard
  deviation  FT*SQRT(SIGMA(1,1)),  represents  the epsilon error, and
  uses the predicted value (FT) evaluated with eta=0, that is, eta
  does not interact with the epsilon error.  WR2 is the conditional
  intra-individual  weighted residual with eta-eps interac- tion.  It
  is an eta-eps interaction residual because  the  denominator term,
  the  residual standard deviation IPRED*SQRT(SIGMA(1,1)), represents
  the epsilon error, and uses the predicted value  (IPRED)  evaluated
  with  a  non-zero  eta,  that is, eta interacts with the epsilon
  error.

  With NONMEM 7, alternatively one can use reserved  residual
  variables CIWRES(=WR)  and CIWRESI(=WR2):
  #+begin_src perl
   $ERROR
   Y=F+F*EPS(1)
   $ESTIM METHOD=COND
   $TABLE IPRD CIPRED CIWRES CIWRESI
  #+end_src
- Example 5: output simulated values:
  #+begin_src perl
   $PK
    ...
   CL=THETA(1)*EXP(ETA(1))
    ...
   $SIMULATION (seed) ONLYSIM
   $TABLE ETA(1) CL
  #+end_src
  ETA(1) and CL are simulated values.

- Example 6: output simulated and estimated values:
  #+begin_src perl
   $INPUT  .... CLSM E1SM ...
   $PK
    ...
   CL=THETA(1)*EXP(ETA(1))
   IF (ICALL.EQ.4) THEN
       CLSM=CL
       E1SM=ETA(1)
   ENDIF
   $SIMULATION (seed)
   $ESTIM
   $TABLE CLSM E1SM CL ETA(1)
  #+end_src
  Modification of the data record during the simulation pass is the
  only way to save the simulated values in the absence of ONLYSIM.
  Column  1 and  2  of the table are the simulated values.  Column 3
  and 4 are the typical values.

- Example 7: output conditional values of a variable in  each  of  two  mixture subpopulations.
  #+begin_src perl
   $PK
      ...
   IF (MIXNUM.EQ.1) CL=  ...
   IF (MIXNUM.EQ.2) CL=  ...
   IF (COMACT.EQ.2) THEN
     IF (MIXNUM.EQ.1) CL1=CL
     IF (MIXNUM.EQ.2) CL2=CL
   ENDIF
   $ESTIM  ... POSTHOC ...
   $TABLE CL1 CL2
  #+end_src
  CL1  (and  CL2)  is a SAVE variable because it is defined in a
  copying block.  Were the values for CL1 not stored in the SAVE
  region,  during the  copying  pass  to obtain values for tables and
  with MIXNUM=2, CL1 would retain its value set with the previous data
  record.


- Example 8: output conditional values of a variable in the
  subpopulation into which the individual is classified.
  #+begin_src perl
   $PK
      ...
   IF (MIXNUM.EQ.1) CL=  ...
   IF (MIXNUM.EQ.2) CL=  ...
   IF (COMACT.EQ.2.AND.MIXNUM.EQ.MIXEST) CLE=CL
   $ESTIM  ... POSTHOC ...
   $TABLE CLE
  #+end_src
  CLE is a SAVE variable because it is defined in a copying block.
  Were the values for CLE not stored in the SAVE region, during  the
  copying pass  to  obtain  values  for tables and with MIXNUM>MIXEST,
  CLE would retain its value set with the previous data record.

REFERENCES: Guide IV, section III.B.7 , IV.E.2

REFERENCES: Guide VI, section III.J , IV.E

REFERENCES: Guide Introduction_7

*** Data set
Summary of data used in the analysis is listed, e.g.

#+begin_src txt
 DATA SET LOCATED ON UNIT NO.:    2
 THIS UNIT TO BE REWOUND:        NO
 NO. OF DATA RECS IN DATA SET:  394
 NO. OF DATA ITEMS IN DATA SET:   8
 ID DATA ITEM IS DATA ITEM NO.:   1
 DEP VARIABLE IS DATA ITEM NO.:   4
#+end_src
In FORTRAN terms, the summary shows file I/O unit,  the REWIND
(necessary only with multiple runs using the data).

(See data record, data item).

REFERENCES: Guide IV, section III.B.2

*** Monitoring of search
NONMEM  output  includes  a report of the history of the search
undertaken in the Estimation Step for parameter estimates.  This
report  is called  the  intermediate  output from the Estimation Step,
because it consists of summaries of the progress of the search, from
iteration to iteration, and because it may be viewed as the search
progresses, provided the NONMEM output file may be viewed as the
search  progresses. This report can also be viewed in a special
(unbuffered) file.

The  search  is  for  parameter  values that minimize the value of the
OBJECTIVE FUNCTION  (See minimum value of objective function).  It
entails the following steps.
1. The  search  is  carried out in a different parameter space.  The
   parameters are transformed to unconstrained parameters (UCP).  In
   the  transformation  process a scaling occurs so that the initial
   estimate of each of the UCP is 0.1.  (NONMEM Users Guide  I
   Sections  C.3.5.1 "ESTIMATION" and G.3 "Messages from the
   Estimation Step" refer to the UCP as "scaled transformed
   parameters" or STP. NONMEM  Users Guide II Section F "Rescaling"
   refers to the UCP as "rescaled canonical parameters" or RCP.)

2. At the  current parameter estimate the GRADIENT vector (the
   vector  of  first  partial  derivatives of the objective function
   with respect to the UCP) is  computed.   An  approximate  Hessian
   matrix  (See hessian)  is  also  computed.  An ITERATION SUMMARY,
   including the current parameter estimate and the gradient vector,
   may placed into the intermediate output.

   With  NONMEM  7,  the  parameter  estimates are also displayed in
   their natural (unscaled) space. These  lines  are  identified  as
   NPARAMETR  and precede the PARAMETER lines, which display the UCP
   values.  Note that when OMEGA (or SIGMA)  have  block  structure,
   the  values  in  NPARAMETR  are listed in upper triangular order,
   whereas elsewhere in NONMEM output they are  displayed  in  lower
   triangular  order.   For  example, suppose the NONMEM output displays a 3x3 OMEGA matrix as

   #+begin_src txt
      OMEGA(1,1)
      OMEGA(2,1) OMEGA(2,2)
      OMEGA(3,1) OMEGA(3,2) OMEGA(3,3)
   #+end_src

   It will be listed in NPARAMTR in row-major order:
   #+begin_src txt
      OMEGA(1,1) OMEGA(2,1) OMEGA(3,1) OMEGA(2,2) OMEGA(3,2) OMEGA(3,3)
   #+end_src
   Note that $ESTIMATION's ORDER option does not affect the order.

3. Using  the  gradient  vector  and  Hessian matrix, a direction in
   parameter space, emananting from the current parameter  estimate,
   is  computed, and a search is undertaken along this direction for
   an approximate minimum point.  When this point is  found,  NONMEM
   returns  to step 2.  (An ITERATION consists of the computation of
   the direction, the search along the direction, and  the
   computation of the gradient vector and Hessian matrix at the
   approximate minimum point.)

4. Iteration stops when one of the following conditions holds:

   - A successful (local) minimum point has been found.

   - The maximum number of FUNCTION EVALUATIONS allowed  by  the  user (MAXEVALS option of $ESTIM) is exceeded.

   - It was not possible to successfully locate a minimum point due to ROUNDING ERRORS.

   Here is an example of intermediate output from the Estimation Step:

   #+begin_src txt
    MONITORING OF SEARCH:
     ITERATION NO.:    0    OBJECTIVE VALUE:   110.244034784025  NO. OF FUNC. EVALS.:   6
     CUMULATIVE NO. OF FUNC. EVALS.:        6
     NPARAMETR:  3.0000E+00  8.0000E-02  4.0000E-02  6.0000E+00  5.0000E-03
     3.0000E-01  2.0000E-04  6.0000E-03  4.0000E-01  4.0008E-01
     PARAMETER:  1.0000E-01  1.0000E-01  1.0000E-01  1.0000E-01  1.0000E-01
     1.0000E-01  1.0000E-01  1.0000E-01  1.0000E-01  1.0000E-01
     GRADIENT:   1.4640E+01 -1.6691E+01  5.6460E+01 -9.4129E+00 -1.1699E+01
     1.0623E+01 -6.3485E-01 -4.7803E+01 -9.6457E+00  5.2414E+00

     ITERATION NO.:    5    OBJECTIVE VALUE:   105.453694506861  NO. OF FUNC. EVALS.:   7
    CUMULATIVE NO. OF FUNC. EVALS.:       45
     NPARAMETR:  2.8166E+00  8.0433E-02  3.8563E-02  6.6123E+00  9.7862E-03
    -3.9509E-02  2.3438E-04  8.1375E-03  4.9657E-01  4.0355E-01
     PARAMETER: -5.3055E-02  1.0703E-01  5.7598E-02  1.4858E-01  1.8644E-01
    -1.2545E-02  1.5794E-01  1.3452E-01  3.7714E-02  1.0431E-01
     GRADIENT:   3.5103E-01 -1.3214E+01  2.8003E+01  1.1115E+00  1.9193E+00
    -5.3252E+00  7.1533E-02 -2.2091E+01 -1.4424E+00  8.2329E+00

     ITERATION NO.:   10    OBJECTIVE VALUE:   104.747695563098  NO. OF FUNC. EVALS.:   7
     CUMULATIVE NO. OF FUNC. EVALS.:       80
     NPARAMETR:  2.7362E+00  7.6935E-02  3.5982E-02  5.7362E+00  1.0840E-03
    -2.9208E-01  2.3701E-04  9.4013E-03  5.1805E-01  3.8858E-01
     PARAMETER: -1.1928E-01  4.9234E-02 -2.3022E-02  7.7517E-02  2.2174E-02
    -9.9574E-02  1.9498E-01  1.4956E-01 -1.7173E-01  8.5414E-02
     GRADIENT:  -1.3933E+00 -7.4632E+00  9.3144E+00  1.0280E+00  9.6395E-01
    -3.1313E+00  1.0212E+00 -5.3784E+00 -2.0828E+00 -9.1477E-01

     ITERATION NO.:   15    OBJECTIVE VALUE:   104.561086502423  NO. OF FUNC. EVALS.:   7
     CUMULATIVE NO. OF FUNC. EVALS.:      116
     NPARAMETR:  2.7735E+00  7.8097E-02  3.6292E-02  5.5466E+00  5.1735E-03
    -1.2911E-01  2.3941E-04  9.0947E-03  5.1461E-01  3.8760E-01
     PARAMETER: -8.8567E-02  6.8686E-02 -1.2994E-02  6.0711E-02  1.0762E-01
    -4.4762E-02  1.9028E-01  1.4643E-01 -8.4016E-02  8.4157E-02
     GRADIENT:   7.7937E-03  5.7189E-03  3.0426E-02 -5.1648E-03 -1.2939E-02
     1.4490E-02  7.4602E-04 -2.5227E-02 -3.1443E-03  1.5799E-02

    ITERATION NO.:   19    OBJECTIVE VALUE:   104.561067398632  NO. OF FUNC. EVALS.:   0
     CUMULATIVE NO. OF FUNC. EVALS.:      149
     NPARAMETR:  2.7739E+00  7.8129E-02  3.6307E-02  5.5498E+00  5.2393E-03
    -1.2767E-01  2.3985E-04  9.1064E-03  5.1521E-01  3.8742E-01
     PARAMETER: -8.8304E-02  6.9219E-02 -1.2510E-02  6.0998E-02  1.0895E-01
    -4.4249E-02  1.9095E-01  1.4652E-01 -8.3269E-02  8.4127E-02
     GRADIENT:   1.2144E-04 -1.4883E-04 -6.6257E-06 -7.5745E-05 -1.6157E-05
     1.1307E-04  6.4128E-05  1.1193E-04 -1.7655E-05  4.2676E-05
   #+end_src
   Note that the values of the PARAMETERs are the values of the  UCP,
   so that at the 0th iteration, all the PARAMETERs have the value
   0.1.

   The  first  parameter  (and gradient) elements correspond to the
   THETA elements which are not fixed.  The remaining  elements
   correspond  to the  OMEGA and SIGMA elements which are not fixed,
   but not in a simple 1-1 manner unless OMEGA and SIGMA are
   constrained to be diagonal.

   $ESTIMATION's PRINT option determines how often iteration
   summaries  are printed: not at all (with PRINT=0);  only for the
   0th and last iterations (with PRINT=9999); for the 0th iteration,
   for every  10th  iteration  thereafter,  and  for the last
   iteration (with PRINT=10, as illustrated above).

   If a model specification file is output, then the estimates  may
   also be  seen  in  the original parameterization for those
   iterations whose summaries appear in intermediate output.  These
   estimates may be found in  file INTER in the same order and format
   as elsewhere in the NONMEM output.  With NONMEM 7, INTER exists
   after the run is finished.

   When the Estimation Step terminates, it reports its outcome:
   #+begin_src txt
    MINIMIZATION SUCCESSFUL
    NO. OF FUNCTION EVALUATIONS USED:      149
    NO. OF SIG. DIGITS IN FINAL EST.:  4.7
   #+end_src
   Each  UCP  element of the mimimum point is determined to a number
   of significant digits.  The number of significant digits reported
   is  the number  of  significant  digits  in the
   least-well-determined element. The report "MINIMIZATION SUCCESSFUL"
   is issued when this number is  no less than the number of
   significant digits requested using the SIGDIGITS option of the
   $ESTIMATION record.  Note  that  this  report  alone does not
   assure that a global (or even a local) minimum point has been
   located; what appears to be a minimum point may  be  a  saddle
   point. Nor, if a minimum point has been located, does the report
   alone assure that the objective function is not "flat" in a region
   of  the  point. For such assurances, one also needs to implement
   the Covariance Step.

REFERENCES: Guide I, section C.3.5.1

REFERENCES: Guide V, section 10.4.1

*** Initial estimate
Initial  estimates  of  parameters  are  required by NONMEM.  They are
used, for example, to compute the initial value of the objective
function  (before NONMEM begins its search for final estimates).  The
user may provide initial estimates.  Alternatively,  he  may  request
that NONMEM provide initial estimates.

NONMEM  may  also use the final estimates from a previous run as
initial estimates, by means of a Model Specification File. The outputs
will be different in that case (See model specification file).

NONMEM output reflects initial estimates provided by the user on  its
problem summary page, such as
#+begin_src txt
      INITIAL ESTIMATE OF THETA:
      LOWER BOUND    INITIAL EST    UPPER BOUND
      0.0000E+00     0.1500E+03     0.1000E+07
      0.0000E+00     0.0000E+00     0.0000E+00
      0.1000E+00     0.3000E+00     0.1000E+02
      -0.1000E+07    -0.1000E-01    0.1000E+07
      INITIAL ESTIMATE OF OMEGA:
      0.2500E+00
      0.0000E+00   0.2500E+00
      INITIAL ESTIMATE OF SIGMA:
      0.2500E+00
#+end_src
indicating:
- The  initial  estimate of THETA(1) is 150, and the parameter is
  constrained to be greater than zero (no upper bound).
- THETA(1) is fixed at zero.
- The initial estimate of THETA(3) is .3, and the parameter is
  constrained to lie between .1 and 10.
- The initial estimate of theta(4) is -.01, and the parameter is
  unconstrained.
- OMEGA is 2x2 and constrained to be  diagonal (signified  by the  0
  value of the initial estimate of omega(2,1); the initial estimates
  of omega(1,1) and omega(2,2) are .25.
- SIGMA is 1x1 (a scalar), with initial estimate .25.

Not specifying the initial estimate of an element of THETA prompts
NONMEM to provide the initial estimate, as in this example:

#+begin_src txt
       INITIAL ESTIMATE OF THETA:
       LOWER BOUND    INITIAL EST    UPPER BOUND
       0.1000E+00                    0.1000E+02
#+end_src
Similar for OMEGA  and SIGMA  elements.

In those cases, NONMEM search for initial estimates and output them
along with user-specified ones under  the  heading  "INITIAL PARAMETER
ESTIMATE". This output is omitted if all initial parameter estimates
are provided by the user.

#+begin_src txt
	********************  INITIAL PARAMETER ESTIMATE   ***
	THETA - VECTOR OF FIXED EFFECTS PARAMETERS  **********
                   TH 1      TH 2      TH 3
		1.50E+00  1.02E-01  2.90E+01
	OMEGA - COV MATRIX FOR RANDOM EFFECTS - ETAS  ********
                   ETA1
	ETA1    1.50E+00
#+end_src

(See final parameter estimate).

REFERENCES:  Guide  IV,  section  III.B.9  , III.B.10 , III.B.11

*** Hessian  matrix
The second derivative matrix of the objective function with respect to
the parameters of the model are utilized in NONMEM.

- Estimation Step: a crude numerical approximation to the Hessian is
  maintained during the minimization search.  The following message in
  the intermediate output refers to this matrix:

  #+begin_src txt
      RESET HESSIAN
  #+end_src
  Internally, the search starts with the Hessian set to the identity
  matrix. The Hessian is updated after each iteration, using a rank  1
  update  procedure.  When  there  is no longer a sensible direction
  to take, but convergence has not  been  achieved,  this may be due
  to inadequacy of the updated Hessian. Then the Hessian is reset to a
  certain positive semi-definite diagonal matrix, and a  new direction
  computed from this matrix (and the gradient vector) is tried.

  The message indicates why  an  unusually  large
  number of function evaluations were used for the iteration (extra
  ones were needed to compute the new Hessian and  perform  a  line
  search  along  the  new  direction) and why an unusually long CPU
  time was needed for the  iteration  (if  intermediate  output  is
  being  monitored). It suggests difficulties in searching, and
  possible modeling error.

- Covariance Step: a good numerical approximation to the Hessian is
  computed at  the final parameter estimates. It is referred to as the
  R matrix.


- Obtaining Conditional Estimates: in  this case, the Hessian matrix
  is the second derivative matrix of the conditional objective
  function.  The following error messages refer to this matrix:
  #+begin_src txt
      HESSIAN OF OBJ. FUNCT. FOR COMPUTING CONDITIONAL ESTIMATE IS
      NON POSITIVE DEFINITE

      NUMERICAL HESSIAN OF OBJ. FUNC. ...
  #+end_src

REFERENCES: Guide IV, section III.B.15

REFERENCES: Guide V, section 12.4.6

REFERENCES: Guide VII, section II.A

*** Covariance matrix of estimate
parameter estimators follow multivariate  normal distribution
asymptotically,  with  variance-covariance  matrix that can be
estimated from the data.  They are computed and reported by NONMEM in
a Covariance Step. The matrix describes the variability under the
assumed model  of  the  parameter  estimates.  It is /not/ SIGMA (the
covariance matrix for the second level random effects) or OMEGA (the
covariance matrix  for the first level random effects).


An example  of  the  NONMEM  output  giving the estimate of the variance-covariance matrix.

#+begin_src txt
 **************** COVARIANCE MATRIX OF ESTIMATE  ********************
             TH 1      TH 2      OM11      OM12      OM22      SG11
  TH 1        1.02E+00
  TH 2       -7.34E-03  6.50E-04
  OM11        1.50E+01 -2.88E-01  2.78E+02
  OM12       ......... ......... ......... .........
  OM22        3.73E-04 -3.33E-05  1.47E-02 .........  1.72E-06
  SG11       -7.79E-02  1.26E-03 -1.45E+00 ......... -5.59E-05  2.55E-02
#+end_src
The matrix is symmetric and is given in lower triangular form.  Here
the 2x2 OMEGA matrix is constrained to be diagonal, therefore entries
related to OM12 are not available omitted. (a compressed  form is used
when the dimension exceeds 75x75. One can also requested this format
manually. See $covariance).

The estimated variance-covariance matrix is computed as
\(R^{-1}SR^{-1}\). Here \(R\) is the Hessian matrix of the objective
function, , and \(S\) the summation of  the  cross-product  gradient
vectors of the individual-based objective functions. Both
are evaluated at the parameter estimates.   The individual-based objective
functions are the separate terms contributed by each individual's data
to the  overall  objective  function,  and  the cross-product
gradient  vectors  are summed across the individuals in the data set.

The Inverse Covariance Matrix \(T=RS^{-1}R\),  is  also  output. A
pseudo-inverse of \(S\) is  used when \(S\) is (near) singular. One
can potentially use this Inverse Covariance Matrix to estimate a joint
confidence region for the complete set of population parameters.

- An error message stating that the R matrix is not positive
  semidefinite suggests that the  parameter  estimation did not  reach
  a  local minimum and warrants further investigation. In this case,
  no covarance matrix (or its inverse) will be output.

- An error message stating that \(R\) is positive semidefinite  but
  singular suggests that the objective function minimum reached is not
  unique, probably due to overparametrization. In this case, no
  covarance matrix (or its inverse) will be output.

- An error message stating that \(S\) is singular suggests
  overparameterization. This still allows estimating and ouptut of the
  covariance matrix when \(R\) is positive semidefnite and
  nonsingular.

- When \(R\) is singular but positive semidefinite, matrix \(T\) is
  output. In this case \(T\) is not the inverse  covariance  matrix,
  but still can be used to  develop  a joint confidence region for the
  complete set of population parameters.

- Alternatively, $COVAR's MATRIX option allows the variance-covariance matrix to be calculated as
  \(2R^{-1}\) or \(4S^{-1}\). They are asymptotically equivalent to
  \(R^{-1}SR^{-1}\) under the assumption that the objective function is additively proportional to
  \(LL\), the log likelihood of the data.

- The  Covariance   Step   will   not   be executed when the requested
  number of significant digits is greater than the reported number of
  significant digits in the final  parameter  estimate (See sig
  digits). When the model specification file is used as input the
  Covariance  Step  can be run without the  Estimation step
  (MAXEVAL=0). In that case one should ensure the requested number of
  significant digits is less than the reported number  of significant
  digits from the previous run.

 (See standard error, correlation matrix of estimate).

 REFERENCES: Guide I, section C.3.5.2

 REFERENCES: Guide II, section D.2.5

 REFERENCES: Guide V, section 5.4 , 13.3

*** Correlation matrix of estimate
The  correlation  matrix is the variance-covariance matrix in
correlation form.  If  the  correlation between  two  parameters  is
large (e.g., >.95), then one may conclude that a considerable portion
of the uncertainty in  each  parameter  is due  to unidentifiability.
The problem can be alleviated with additional data or using  a
simpler model with fewer parameters.


Ouutput example:
#+begin_src txt
 **************** CORRELATION MATRIX OF ESTIMATE ********************
             TH 1      TH 2      OM11      OM12      OM22      SG11
  TH 1        1.01E+00
  TH 2       -2.85E-01  2.55E-02
  OM11        8.87E-01 -6.77E-01  1.67E+01
  OM12       ......... ......... ......... .........
  OM22        2.81E-01 -9.96E-01  6.72E-01 .........  1.31E-03
  SG11       -4.83E-01  3.10E-01 -5.44E-01 ......... -2.67E-01  1.60E-01
#+end_src
The matrix is symmetric and is given in lower triangular form.  Here
the 2x2 OMEGA matrix is constrained to be diagonal, therefore entries
related to OM12 are not available omitted. (a compressed  form is used
when the dimension exceeds 75x75. One can also requested this format
manually. See $covariance).

With  NONMEM  7.2  and  higher, the diagonal elements are the standard
error (the square root of the diagonal elements of the covariance
matrix. Earlier versions they were 1.0.

REFERENCES: Guide I, section C.3.5.2

REFERENCES: Guide V, section 5.4


*** ETABAR
ETABAR (\(\bar{\eta}\)) is output when a conditional population estimation  method  is used.
#+begin_src txt
  ETABAR IS THE ARITHMETIC MEAN OF THE ETA-ESTIMATES,
  AND THE P-VALUE IS GIVEN FOR THE NULL HYPOTHESIS THAT THE TRUE MEAN IS 0.

  ETABAR:        -3.5224E-02 -7.1437E-05  2.5095E-03
  SE:             3.4060E-01  3.1223E-03  1.9001E-01
  N:                      12          12          12

  P VAL.:         9.1763E-01  9.8175E-01  9.8946E-01
#+end_src
The  ith  number  listed  after "ETABAR" is the sample average (across
individuals) of the conditional estimates of the ith eta, and the  ith
number  listed  after  "SE"  is  the  standard error for this average.
Under the assumed model, the population average of the the conditional
estimates  is approximately zero.  If the model is well-specified, the
sample average should be near 0. (but see below for a mixture  model).
The  P-value helps one assess whether the sample average is "far"
from 0.  A value under 0.05, for example, indicates such an average
(notice the value 0.32E-02).

With  a  mixture  model, the ith eta is understood to have a different
distribution for each subpopulation of the mixture.  Accordingly,
different  instances of the above output will appear, one for each of
the different subpopulations.  Using a standard Bayesian-type
computation, each  individual is classified into one of the
subpopulations, and the conditional estimate of the ith eta under the
model for this  subpopulation is used in the sample average for that
subpopulation.  If under the mth submodel, the ith eta does not
influence  the  data  from  any individual,  but it does influence the
data from some individual under some other submodel, then the sample
average for the ith eta  for  the mth  submodel  will  be 0.  If the
ith eta does not influence the data from any individual under any
model, then the sample average  for  the ith  eta for the mth submodel
will usually be 0, but it will not be if (i) the ith eta is correlated
with an eta that influences  some  individual's  data  under  the  mth
submodel, and (ii) that individual is classified to be in the mth
subpopulation.


The population average of the conditional estimates is  only
approximately  zero  because a conditional estimate is a (Bayesian)
posterior mode, and not a posterior expectation.  However with a
mixture  model, with  the  estimate for a given individual, the
posterior distribution is that for the subpopulation into which the
individual is classified, and due to possible missclassification the
expectation of the estimate may be even "further from" zero than with
a  nonmixture  model.   For this  reason  too,  the  centered FOCE
method may not work well with a mixture model.


With a mixture model, or with a nonmixture model, one may implement  a
second  Estimation  Step  (in a subsequent problem), and then a second
ETABAR estimate (EB2) can be obtained, with  which  the  first  ETABAR
estimate  (EB1)  can be compared.  If the data-analytic model is
wellspecified, the two estimates should represent nearly  the  same
quantity.   Using  an option on the $ESTIMATION record, the second
P-value assesses the magnitude of the difference between EB1 and EB2,
and a Pvalue  under  0.05  would  suggest that the data-analytic model
is not well-specifed.  To obtain EB2, a data set is simulated under
the  fitted  model, and EB2 is obtained using this data set.  Both EB1
and EB2 are (univariate) measures of central tendency of the
distribution  of interindividual  "residuals", i.e. the distribution
of the conditional estimates of the etas.  In both cases the
residuals  are  defined  in terms  of  the  data-analytic model.  But
for EB1, the distribution is governed by the true (unknown) model, and
for EB2, the distribution is governed by the fitted  model.  If the
two models are "close", EB1 and EB2 will be close.  The conditional
estimates of  the  etas  from  the simulated  data  should be based on
the population parameter estimates from these data.  It may cost
considerable CPU  time  to  obtain  this second  set of parameter
estimates, and so it may not always be feasible to compute EB2.


One proceeds by constructing a problem specification that
1. includes the same $INPUT record as was used with a previous  problem wherein EB1 was obtained;
2. includes  an  $MSFI  record specifying a model specification file from that previous problem, so that in particular, EB1 is available;
3. includes a $SIMULATION record with the option TRUE=FINAL, so  that a  data  set will be simulated using the final parameter estimate from that previous problem;
4. includes a $ESTIMATION record with  the  option  ETABARCHECK  (and
   either the option METHOD=COND or METHOD=HYBRID).

A  data  set  will  be  simulated, and EB2 will be obtained.  With the
 ETABARCHECK option, the P-value for the  difference  EB2-EB1  will  be
 computed.   Otherwise,  if  the  model  is  a nonmixture model, EB1 is
 ignored, and the P-value will be simply that for EB2, and if the model
 is a mixture model, no P-value will be output (only the standard error
 for EB2 will be  output).   The  numbers  of  data  and/or  individual
 records in the simulated data set may differ from those for the previous problem; so if desired, this data set can be much larger than  the
 real data set.

REFERENCES: Guide VII Section II.A, III.D

REFERENCES: Guide VII, section II.A , III.D
*** Final estimate
NONMEM output always include FINAL PARAMETER ESTIMATE. When the
Estimation Step was not run, then output  are  the initial parameter
estimates specified for the problem.

These estimates of parameters are used by NONMEM to compute the objective  function  value printed on the page with under "MINIMUM VALUE OF OBJECTIVE FUNCTION" and predicted  values  for  Tables  and Scatterplots.

#+begin_src txt
  ********************  FINAL PARAMETER ESTIMATE   ***************
  THETA - VECTOR OF FIXED EFFECTS PARAMETERS   *********

          TH 1      TH 2      TH 3
          1.94E+00  1.02E-01  3.20E+01

  OMEGA - COV MATRIX FOR RANDOM EFFECTS - ETAS  ********

             ETA1
  ETA1     8.99E-01

  OMEGA - CORR MATRIX FOR RANDOM EFFECTS - ETAS  *******

             ETA1
  ETA1     9.48E-01
#+end_src
The  example above is from a run involving single-subject data, so there is no SIGMA matrix.

With NONMEM 7.2 and higher, the correlation matrix is included.  It is
computed  from  the  covariance  matrix, whether or not the Estimation
step is not run.

(See initial parameter estimate).

With NONMEM 7.3 and higher, the $THETAR record may be used  to  transform  final  estimates of THETA before they are reported in the NONMEM
output.

(See $thetar).

REFERENCES: Guide V, section 10.5


*** Value of the objective function
The  NONMEM  OBJECTIVE  FUNCTION  is  a goodness of fit statistic; the
lower the value, the better the fit.  Negative values are possible and
have   no   special  significance.   Under  certain  assumptions,  the
(default) objective function value is minus twice the log likelihood.

A page with the title MINIMUM VALUE OF OBJECTIVE FUNCTION is  printed
as part of every NONMEM output, as in this example.

#+begin_src txt
 ******       MINIMUM VALUE OF OBJECTIVE FUNCTION        ***********
 *****************         11.570     ******************************
#+end_src

If the Estimation Step was run, then the value printed is the value of
the objective function with the final parameter estimates. Otherwise,
the value printed is the value of the objective function using the
initial parameter  estimates specified for the problem.


Differences in the objective function of fits  of  the  same  data  to
hierarchical  models can often be used to test approximately the
plausibility of the smaller (fewer free parameters) model  by
referencing the  difference  to  a chi-square distribution with
degrees of freedom equal to the difference in the number of free model
parameters between models (hypothesis tests).

NM-TRAN may generate the following warning message:

#+begin_src txt
 (WARNING   68) THE INTEGER FUNCTION IS BEING USED OUTSIDE OF A SIMULATION
  BLOCK. IF THE INTEGER VALUE AFFECTS THE VALUE OF THE OBJECTIVE  FUNCTION,
  THEN AN ERROR WILL PROBABLY OCCUR.
#+end_src
In  general, any code that affects the value of the prediction F (with
$PRED) or Y (with $ERROR), or their eta and eps partials, affects  the
value  of the objective function.  Such code must be continuous, e.g.,
must not use functions such as INT or MOD, and must not involve
conditional statements that introduce discontinuities.  The following
examples use Model Event Time parameters (MTIME) to avoid
discontinuities in differential equations:

Model Time examples
 Examples Using MTIME to Model Periodic Discontinuities in $DES
 Enterhepatic circulation examples

(See mtime, model time examples).

 (See Circadian Example: Examples Using MTIME to Model Periodic Discontinuities in $DES)
 (See Enterhepatic circulation examples).

REFERENCES: Guide I, section C.3.5.1

REFERENCES: Guide V, section 5.5


*** Inferential statistics
Confidence intervals for parameters, testing hypotheses about
parameters, and building models all need reasonable ranges for
parameter values. These ranges can be found if we can estimate the
distribution of the parameter estimates based on asymptotic theory,
used in NONMEM's extended least-squares method. The parameter
estimates follow a multivariate normal distribution, and their
variance and covariance can be estimated from the data.

NONMEM provides this variance-covariance matrix for the estimates. The
square roots of the diagonal elements of this matrix are the estimated
standard errors for each parameter. The off-diagonal elements can be
converted into correlation coefficients, which are shown in the
correlation matrix of the parameter estimates. Additionally, the
inverse of the covariance matrix and the eigenvalues of the
correlation matrix are also available for use.

*** PRED, RES, WRES
NONMEM output usually include special items: prediction, residual, and
weighted residual, which are generated by NONMEM.  The default  labels
for these items are PRED, RES, and WRES, respectively. Synonyms may be
specified on the $TABLE record for one or more of these labels.   With
the  NOAPPEND  option on this record, the three items are not included
in a table unless explicity listed on the $TABLE record.  With the use
of the user-routine SPTWO, the values of the RES and WRES items can be
defined differently from the values described below. (See sptwo).

These items may also be displayed in scatterplots. See $SCATTERPLOT.

- PRED Prediction items are the predictions computed by the PRED
  subroutine.  For population data, prediction items are  always
  population  predictions,  i.e.,  they are computed at the mean value
  of eta (0).

- RES  The residual is defined as DV - PRED; that is, the observed value minus the prediction item.

- WRES The weighted residuals for an individual are formed by
  transforming the individual's residuals so that under the model,
  assuming the  true  values of the parameters are given by the
  estimates of those parameters, all weighted residuals have mean 0,
  unit  variance  and  are  uncorrelated.  For population data, the
  "weights" are computed at eta = 0.

For odd-type data, the prediction items are likelihoods  (for
population  data, using the estimated values of the parameters, and
computed at ETA = 0).  These may not be of much interest.   The  RES
and  WRES items are 0.


With  a  mixture  model, each individual is classified into one of the
subpopulations of the mixture according to a computation based on  the
individual's  data  and  on the final parameter estimates.  For a data
record from the  individual  record,  the  prediction,  residual,  and
weighted  residual items in the corresponding row of a table (or point
on a scatterplot) are based on the submodel defining the subpopulation
into which the individual is classified.


If  the  Marginal  data item (MRG_) is 1 or 2 for a given data record,
then PRED is an expected prediction, rather than the prediction at the
mean  value  of eta.  When the Raw-data data item (RAW_) is 1, then DV
is a raw-data average and RES is the difference between the PRED  item
and this average.

(See displayed PRED-defined items).


REFERENCES: Guide I, section C.3.5.3 , C.3.5.4

REFERENCES: Guide IV, section III.B.16 , III.B.17

REFERENCES:  Guide V, section 9.5 , 10.7 , 11.4.4.2

*** Shrinkage
Shrinkage are output between #TERM and #TERE entries.

- With NONMEM 7.3, these are
  #+begin_src txt
      ETAshrink
      EBVshrink
      EPSshrink
  #+end_src
  For details, see the NONMEM 7 guide.
- With NONMEM 7.4, these are
  #+begin_src txt
      ETAshrinkSD (ETAshrink in NM73)
      ETAshrinkVR
      EBVshrinkSD (EBVshrink in NM73)
      EBVshrinkVR
      EPSshrinkSD (EPSshrink in NM73)
      EPSshrinkVR
  #+end_src
  For details, see the NONMEM 7.4 guide

- NONMEM v7.3+ provides option ETASTYPE=1 in $EST to average shrinkage
  information only among individuals with non-zero derivative of their
  data likelihood with respect to ETA, and will not include subjects
  with a non-influential ETAs that have zero derivative.

- One may  request include/exclude ETA output using ETASXI(i). (See
  ETASXI). Shrinkage map for included/exlucded ETAs is documented in root.shm.

- Shrinkage  data  are  reported in file root.shk.

REFERENCES: Guide Introduction_7


** Model specification file (MSF)
A Model Specification File (MSF) is an output file from NONMEM that
stores Estimation and Covariance-step results, including initial,
intermediate, and final parameter estimates and search information. It
is requested in the estimation control record and can be used in later
runs to resume a failed search, or as input for further estimation,
simulation, covariance, table, scatterplot, or finalization steps,
with final estimates in the MSF serving as initial values if desired.
When an MSF is written and iteration summaries are requested, NONMEM
also writes the corresponding parameter estimates to the INTER file.

MSF files are used to avoid repeating estimation work already done in
a previous NONMEM run. If a run crashes after the Estimation Step but
an MSF was written, a later run can read that MSF and resume the
parameter search from the last successfully saved iteration.

With  NM-TRAN, specification that an existing Model Specification File
is to be input is done by placing the file's name on the $MSFI record.

With NONMEM 7.3, when MSF or MSFO option is used to  specify  an  MSFO file in the $EST record e.g.,
 #+begin_src perl
 $EST ... MSFO=msfroot.msf
 #+end_src
 then  in addition to the main MSF file msfroot.msf, an extra file msfroot_ETAS.msf will also be produced, and provide  additional  information  when  a  $MSFI record is used in a subsequent problem or control stream.  File msfroot_ETAS.msf contains individual etas and phis  gen- erated  during  estimation  (except FO method, which does not generate non-zero etas during estimation, and not POSTHOC evaluated etas.)  The use  of  an  extension  in the file name, e.g., .msf, is optional.  If file _ETAS does not exist, NONMEM issues a warning, e.g.,

 #+begin_src txt
 WARNING: EXTRA MSF FILE COULD NOT BE OPENED: c5msf2x_ETAS
 #+end_src

If  the  Covariance  Step  is  also  implemented,  extra  files   msfroot_RMAT.msf and msfroot_SMAT.msf containing intermediate information on the R matrix and S matrix will also be produced.  These files  provide  information  when  a  $MSFI  record along with a $COV ... RESUME record is used in a subsequent problem or control stream.  There is no warning if files _SMAT and/or _RMAT are missing.

For an example see the fragment of the control stream for the first run below.  The Estimation Step is run for a limited  num- ber of evaluations of the objective function (200).

#+begin_src perl
 $THETA  (.1,3,5) (.008,.08,.5) (.004,.04,.9)
 $OMEGA BLOCK(3)  6 .005 .0002 .3 .006 .4
 $SIGMA  .4
 $EST     MAXEVAL=200  PRINT=5 MSFO=msf1
#+end_src
 After  review  of  the  first  run's  output, it is decided to let the search continue.  The continuation will start from the iteration  during which the 200th objective function evaluation occurred in the previous search.  A fragment of the control stream  for  the  second  run follows.   $THETA,  $OMEGA,  and  $SIGMA  need  not,  and  may not, be present.  The Estimation Step is allowed to  run  to  completion,  and standard  errors  and  a  table are requested.  A new MSF is obtained, which will allow additional tables and  scatterplots  to  be  obtained later.

 #+begin_src perl
 $MSFI msf1
 $EST PRINT=5 MSFO=msf2
 $COV
 $TABLE ID TIME
 #+end_src

 REFERENCES: Guide I, section B.3

 REFERENCES: Guide IV, section III.B.12

** Error messages
This  is  not  a  complete list.  It includes only commonly seen error messages.

*** Errors in the control stream
#+begin_src txt
 FILE RECORD MISSING
#+end_src
There is something wrong with the NONMEM control file.   Probably it
is  an  NM-TRAN control file (starting with $PROBLEM), rather than the
FCON file produced by NM-TRAN.

#+begin_src txt
 TOT. NO. OF OBSERVATIONS IN INDIVIDUAL REC NO.    1 (IN INDIVIDUAL REC
 ORDERING) EXCEEDS  50
  SEE INSTALLATION GUIDE
#+end_src
There are too many observation records in some individual record. To
increase the limit beyond 50, NONMEM must be recompiled. See Guide
III, Section 2.7.

#+begin_src txt
 INITIAL ESTIMATE OF OMEGA HAS A NONZERO BLOCK WHICH IS NUMERICALLY NOT
 POSITIVE DEFINITE
#+end_src
Possible cause: initial estimates of the variance and  covariance
terms in a block of OMEGA are not appropriate.  Try other initial
estimates.  (Hint: it helps of the covariance estimates are small
relative to the variance estimates.)

#+begin_src txt
 USER  CCONTR ROUTINE NOT USED, BUT THERE ARE NO EPSILONS, AND ETAS ARE
 TO BE ESTIMATED
#+end_src
This can happen when POSTHOC etas are requested, but the data are
single-subject  data.   The  user  may  have included the POSTHOC
option in error.

#+begin_src txt
 UNABLE TO OBTAIN A SATISFACTORY INITIAL ESTIMATE  OF  VARIANCE-COVARI-
 ANCE COMPONENTS
 BLOCKS IN BLOCK SET 2 OF OMEGA ARE NUMERICALLY NOT POSITIVE DEFINITE
#+end_src
This  message  is from the Initial Estimates Step.  It identifies
certain parameters whose initial estimates could not be obtained.

*** Error in NONMEM tasks

#+begin_src txt
 NUMBER OF CALLS TO SIMETA EXCEEDS NO. OF DATA RECORDS  FOR  INDIVIDUAL
 1 (IN INDIVIDUAL RECORD ORDERING)
#+end_src
During  the  Simulation  Step,  an  excessive  number of calls to
SIMETA have occurred.   It  may  be  that  the  users's  PRED  is
attempting  to  obtain ETA from a truncated distribution but, due to
some error, is rejecting all or virtually all values.  (Possibly, the
NEW option was omitted from the random source.)

Some  messages  are preceded by lines such as the following that
identify the NONMEM routine that has detected the error:

#+begin_src txt
 PROGRAM TERMINATED BY OBJ
 PROGRAM TERMINATED BY OBJ, ERROR IN CELS
 PROGRAM TERMINATED BY OBJ, ERROR IN ELS
 PROGRAM TERMINATED BY PRRES, ERROR IN ELS
 PROGRAM TERMINATED BY FNLETA
#+end_src
  - OBJ computes the objective function;
  - ELS computes Extended Least-Squares contribution to the objective function from the data from a single individual ("L1") record.
  - CELS  computes  the conditional contribution to the ELS objective function;
  - PRRES prints final results.
  - FNLETA computes subject-specific (posthoc) eta values.

#+begin_src txt
WITH INDIVIDUAL    1 (IN INDIVIDUAL RECORD ORDERING)
#+end_src
A line such as this identifies the record.

Here are some commonly seen error messages.
#+begin_src txt
 INTRAINDIVIDUAL VARIANCE OF DATA FROM OBS RECORD  1 ESTIMATED TO BE 0
 VAR-COV OF DATA FROM INDIVIDUAL RECORD ESTIMATED TO BE  SINGULAR
#+end_src
A possible cause is the use of a  proportional   intra-individual
      error  model  while  some predicted  values  for  actual observa-
      tions are zero or close to zero.  (For example, if the first dose
      is  an  infusion  and  there is  a  "base- line"  observation  at
      the start of the infusion, the predicted level will be zero.)

#+begin_src
 MINIMIZATION TERMINATED DUE TO PROXIMITY OF NEXT ITERATION EST.  TO  A
 VALUE AT WHICH THE OBJ. FUNC. IS INFINITE
#+end_src
NONMEM THETA-recovery has failed.

#+begin_src
 OCCURS DURING SEARCH FOR ETA AT A NONZERO VALUE OF ETA
#+end_src
An  error  occurred  while NONMEM was obtaining conditional estimates of ETA.

*** Errors in PREDPP
As of NONMEM 7, A differential equation solver  has  been  introduced,
called  LSODA, and is accessed using ADVAN=13 or ADVAN13.  The code to
the differential equation solver is  found  in  source\LSODA.f90.   On
occasion,  coded  errors  will be displayed if the algorithm is having
trouble integrating  the  equations.   These  errors  may  usually  be
ignored,  unless the error shows up frequently, and ultimately results
in failure for the problem to complete.   Typically the remedy  is  to
increase  or decrease TOL, but for those who desire to understand what
the error codes mean, there are well documented comments on  these  at
the beginning of LSODA.f90.  They are printed here for convenience:
#+begin_src txt
  STATE=An index used for input and output to specify the the state of the calculation.

  On input,the values of istate are as follows.
  1  Means this is the first call for the problem (initializations will be done).
     See note below.
  2  Means this is not the first call,and the calculation is to continue
     normally, with no change in any input parameters except possibly TOUT
     and ITASK. (If ITOL,RTOL,and/or ATOL are changed between calls with
     ISTATE=2,the new values will be used but not tested for legality.)
  3  Means this is not the first call,and the calculation is to continue
     normally,but with a change in input parameters other than TOUT and ITASK.
     changes are allowed in NEQ,ITOL,RTOL,ATOL,IOPT,LRW,LIW,JT,ML,MU and any
     optional inputs except H0,MXORDN,AND MXORDS.
     (see IWORK description for ML and MU.)
  Note: A preliminary call with TOUT=T is not counted as a first call here,as
  no initialization or checking of input is done. (Such a call is sometimes
  useful for the purpose of outputting the initial conditions.) Thus the first
  call for which TOUT /= T requires ISTATE=1 on input.

  On output,istate has the following values and meanings.
   1  Means nothing was done; TOUT=T and ISTATE=1 on input.
   2  Means the integration was performed successfully.
  -1  Means an excessive amount of work (more than MXSTEP steps) was done on
      this call,before completing the requested task,but the integration was
      otherwise successful as far as T. (MXSTEP is an optional input and is
      normally 500.) TO continue,the user may simply reset ISTATE to a value > 1
      and call again (the excess work step counter will be reset to 0).
      In addition,the user may increase MXSTEP to avoid this error return
      (see below on optional inputs).
  -2  Means too much accuracy was requested for the precision of the machine
      being used. This was detected before completing the requested task,but
      the integration was successful as far as T. To continue,the tolerance
      parameters must be reset,and ISTATE must be set to 3. The optional output
      TOLSF may be used for this purpose. (Note: If this condition is detected
      before taking any steps,then an illegal input return (ISTATE=-3) occurs
      instead.)
  -3  Means illegal input was detected,before taking any integration steps.
      See written message for details.
      Note: If the solver detects an infinite loop of calls to the solver with
      illegal input,it will cause the run to stop.
  -4  Means there were repeated error test failures on one attempted step,before
      completing the requested task,but the integration was successful as far as T.
      The problem may have a singularity,or the input may be inappropriate.
  -5  Means there were repeated convergence test failures on one attempted step,
      before completing the requested task,but the integration was successful as
      far as T. This may be caused by an inaccurate jacobian matrix, if one is
      being used.
  -6  Means EWT(I) became zero for some I during the integration. Pure relative
      error control (ATOL(I)=0.0) was requested on a variable which has now
      vanished. The integration was successful as far as T.
  -7  Means the length of RWORK and/or IWORK was too small to proceed,but the
      integration was successful as far as T. This happens when DLSODA chooses
      to switch methods but LRW and/or LIw is too small for the new method.

  Note: Since the normal output value of ISTATE is 2, it does not need to be
  reset for normal continuation. Also,since a negative input value of ISTATE
  will be regarded as illegal, a negative output value requires the user to
  change it, and possibly other inputs,before calling the solver again.
#+end_src


[fn:1] Displayed etas are the simulated etas if the simulated etas are
stored in common NMPRD7. This is the case when NM-TRAN is used. If
they are not stored in NMPRD7, displayed etas are all 0.
