#+title: Reserved variables

* Reserved variables
The following names are reserved in all abbreviated code:
   #+begin_src f90
     GETETA
     SIMETA
     SIMEPS
     COMSAV
     NWIND
     ETEXT
     IERPRD
     IERPRDU
     MSEC
     MFIRST
     NETEXT
     ETA1, ETA2, ...ETA9
     ETA10, ETA11, ...ETA99
     Annnnn !! nnnnn is numeric 00000-99999, and nnnn is numeric 0000 -9999
     ! Similarly
     Bnnnnn,Cnnnnn,Dnnnnn,Ennnnn,Fnnnnn,Pnnnnn,Qnnnnn,MCnnnn,MEnnnn,MGnnnn,MTnnnn
   #+end_src
Names of modules and of variables in the modules are also reserved. [fn:6]
Below  is  a list of blocks of abbreviated code and the modules and
variables that may be used.  Second is a list of  modules,  the
variables  in  the  modules,  and  the blocks of abbreviated code in
which these variables may be used.

#+begin_src f90
  ! $AES
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  PKERR_REAL: MTIME
  PRMOD_INT:  ICALL,IDEFD,IDEFA
  PRMOD_INT:  MTDIFF
  PROCM_INT:  ISFINL
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NVNT
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: EVTREC
  PROCM_REAL: THETA
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  MIXP

  ! $DES
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  PKERR_REAL: MTIME
  PRMOD_INT:  ICALL,IDEFD,IDEFA
  PRMOD_INT:  MTDIFF
  PROCM_INT:  ISFINL
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NVNT
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: EVTREC
  PROCM_REAL: THETA
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  MIXP

  ! $ERROR
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_REAL:  CTLO
  NMPR_REAL:  CTUP
  NMPR_REAL:  YLO,YUP
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PKERR_REAL: MTIME
  PRMOD_INT:  MTDIFF
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NEWIND
  PROCM_REAL: A
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  TEMPLT

  ! $INFN
  CMNM1_INT:  NIND_7
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NWIND
  NMPRD_INT:  PRED_IGNORE_DATA,PRED_IGNORE_DATA_TEST
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPRD_REAL: PASSRC
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_INT:   SKIP_
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PRMOD_INT:  I_SS,ISSMOD
  ROCM_INT:   IERE,IERC
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  CNTID
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OBJECT
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR
  ROCM_REAL:  THETAF,OMEGAF,SIGMAF,THETAFR
  ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_
  ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_,
  ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_
  ROCM_REAL:  NPDE_,ECWRES_

  ! $MIX
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  TEMPLT
  ROCM_REAL:  THETA,DATA

  ! $PK
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  PKERR_REAL: MTIME
  PRMOD_INT:  I_SS,ISSMOD
  PRMOD_INT:  MTDIFF
  PRMOD_REAL: A_0
  PROCM_INT:  A_0FLG
  PROCM_INT:  MNOW,MPAST,MNEXT
  PROCM_INT:  NEWIND
  PROCM_REAL: A
  PROCM_REAL: DOSREC
  PROCM_REAL: DOSTIM
  PROCM_REAL: TSTATE
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y

  ! $PRED
  CMNM1_INT:  NIND_7
  NMPRD_INT:  COMACT,COMSAV
  NMPRD_INT:  I_REC
  NMPRD_INT:  MSEC,MFIRST,IFIRSTEM
  NMPRD_INT:  NEWL2
  NMPRD_INT:  NPROB,IPROB
  NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM
  NMPRD_INT:  NTHES_,NETAS_,NEPSS_
  NMPRD_INT:  MDVRES
  NMPRD_INT:  NPDE_MODE
  NMPRD_INT:  ETASXI
  NMPRD_INT:  NOFIRSTDERCODE
  NMPRD_INT:  PRED_IGNORE_DATA,PRED_IGNORE_DATA_TEST
  NMPRD_REAL: CORRL2
  NMPRD_REAL: ETA,EPS
  NMPR_INT:   F_FLAG
  NMPR_INT:   RPTI,RPTO,RPTON,PRDFL
  NMPR_INT:   SKIP_
  NMPR_REAL:  CTLO
  NMPR_REAL:  CTUP
  NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR
  NMPR_REAL:  YLO,YUP
  ROCM_INT:   IERE,IERC
  ROCM_INT:   LIREC
  ROCM_INT:   MIXNUM,MIXEST
  ROCM_INT:   NINDR,INDR1,INDR2
  ROCM_INT:   NIREC,NDREC
  ROCM_INT:   NREP,IREP
  ROCM_REAL:  CNTID
  ROCM_REAL:  CDEN_,DEN_
  ROCM_REAL:  IIDX
  ROCM_REAL:  MIXP
  ROCM_REAL:  OBJECT
  ROCM_REAL:  OMEGA
  ROCM_REAL:  PR_CT
  ROCM_REAL:  PR_Y
  ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR
  ROCM_REAL:  TEMPLT
  ROCM_REAL:  THETAF,OMEGAF,SIGMAF,THETAFR
  ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_
  ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_,
  ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_
  ROCM_REAL:  NPDE_,ECWRES_
#+end_src

Another view of the above list is through the Fortran modules

#+begin_src f90
!MODULES:   !VARIABLES                                 ! NONMEM CONTROL RECORD BLOCKS
CMNM1_INT:  NIND_7                                     ! $ERROR $PK $PRED $INFN
NMPRD_INT:  COMACT,COMSAV                              ! $DES $AES $ERROR $PK $PRED
NMPRD_INT:  I_REC                                      ! $PRED
NMPRD_INT:  MSEC,MFIRST,IFIRSTEM                       ! $DES $ERROR $PK $PRED
NMPRD_INT:  NEWL2                                      ! $ERROR $PRED $INFN
NMPRD_INT:  NPROB,IPROB                                ! $DES $AES $ERROR $MIX $PK $PRED $INFN
NMPRD_INT:  NTHES_,NETAS_,NEPSS_                       ! $DES $AES $ERROR $MIX $PK $PRED
NMPRD_INT:  NWIND                                      ! $INFN
NMPRD_INT:  S1IT,S1NIT,S1NUM,S2IT,S2NIT,S2NUM          ! $DES $AES $ERROR $MIX $PK $PRED $INFN
NMPRD_REAL: CORRL2                                     ! $ERROR $PK $PRED $INFN
NMPRD_REAL: ETA,EPS                                    ! $ERROR $PK $PRED $INFN
NMPRD_REAL: PASSRC                                     ! $INFN
NMPR_INT:   F_FLAG                                     ! $ERROR $PRED $INFN
NMPR_INT:   RPTI,RPTO,RPTON,PRDFL                      ! $DES $AES $ERROR $PK $PRED $INFN
NMPR_INT:   SKIP_                                      ! $PRED $INFN
NMPR_REAL:  CTLO                                       ! $ERROR $PRED $ERROR $PRED
NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR               ! $PK $PRED $INFN
NMPR_REAL:  YLO,YUP                                    ! $ERROR $PRED
NMPR_REAL:  THSIMP,OMSIMP,SGSIMP,THSIMPR               ! $ERROR
PKERR_REAL: MTIME                                      ! $DES $AES $ERROR $PK
PRMOD_INT:  ICALL,IDEFD,IDEFA                          ! $DES $AES
PRMOD_INT:  I_SS,ISSMOD                                ! $PK $INFN
PRMOD_INT:  MTDIFF                                     ! $DES $AES $ERROR $PK
PRMOD_REAL: A_0                                        ! $PK
PROCM_INT:  A_0FLG                                     ! $PK
PROCM_INT:  ISFINL                                     ! $DES $AES
PROCM_INT:  MNOW,MPAST,MNEXT                           ! $DES $AES $ERROR $PK
PROCM_INT:  NEWIND                                     ! $ERROR $PK
PROCM_INT:  NVNT                                       ! $DES $AES
PROCM_REAL: A                                          ! $ERROR $PK
PROCM_REAL: DOSREC                                     ! $DES $AES $PK
PROCM_REAL: DOSTIM                                     ! $DES $AES $PK
PROCM_REAL: EVTREC                                     ! $DES $AES
PROCM_REAL: THETA                                      ! $DES $AES
PROCM_REAL: TSTATE                                     ! $PK
ROCM_INT:   IERE,IERC                                  ! $PRED $INFN
ROCM_INT:   LIREC                                      ! $ERROR $PK $PRED $INFN
ROCM_INT:   MIXNUM,MIXEST                              ! $DES $AES $ERROR $PK $PRED $INFN
ROCM_INT:   NINDR,INDR1,INDR2                          ! $ERROR $MIX $PK $PRED $INFN
ROCM_INT:   NIREC,NDREC                                ! $DES $AES $ERROR $MIX $PK $PRED $INFN
ROCM_INT:   NREP,IREP                                  ! $DES $AES $ERROR $MIX $PK $PRED $INFN
ROCM_REAL:  CDEN_,DEN_                                 ! $ERROR $PK $PRED $INFN
ROCM_REAL:  CNTID                                      ! $ERROR $PK $PRED $INFN
ROCM_REAL:  CPREDI_,CRESI_,CWRESI_,EPRED_,ERES_,EWRES_ ! $PRED $INFN
ROCM_REAL:  CPRED_,CRES_,CWRES_,PREDI_,RESI_,WRESI_    ! $PRED $INFN
ROCM_REAL:  IIDX                                       ! $ERROR $PK $PRED $INFN
ROCM_REAL:  MIXP                                       ! $DES $AES $ERROR $PK $PRED $INFN
ROCM_REAL:  NPDE_,ECWRES_                              ! $PRED $INFN
ROCM_REAL:  OBJECT                                     ! $PRED $INFN
ROCM_REAL:  OMEGA                                      ! $ERROR $PK $PRED
ROCM_REAL:  PRED_,RES_,WRES_,NPRED_,NRES_,NWRES_       ! $PRED $INFN
ROCM_REAL:  PR_CT                                      ! $ERROR $PK $PRED $INFN
ROCM_REAL:  PR_Y                                       ! $ERROR $PK $PRED $INFN
ROCM_REAL:  SETHET,SEOMEG,SESIGM,SETHETR               ! $PRED $INFN
ROCM_REAL:  TEMPLT                                     ! $ERROR $MIX $PRED
ROCM_REAL:  THETA,DATA                                 ! $MIX $PRED $INFN
#+end_src


** Model event times
Model event times are additional PK parameters defined in the PK
routine or $PK block, related to the model event time feature of PREDPP.  A model event time is not associated with any
compartment, but, like an absorption lag time, defines a  time  to
which the system is advanced.  When the time is reached, indicator
variables are set and a call to PK is made.  At this call (and/or
subsequent  to this  call)  PK or DES or AES or ERROR can use the
indicator variables to change some aspect of the system, e.g., a term
in  a  differential equation,  or  the rate of an infusion.  This
feature may be used with any ADVAN routine.  Model times  are
independent  of  non-event  dose times.   The following are reserved
variables when used in abbreviated code.

*** MTIME
MTIME(i) is the i-th model event time.  The maximum  number  of  model  event
times is given by constant PCT in file SIZES (See sizes).

MTIME(i)  may be less than, equal to, or greater than MTIME(i+1). Any
MTIME(i) may be negative or have the value 0 (in  which  case
MPAST(i)=1  always  and  MNEXT(i)=0  always;  see  below).  If PK
defines MTIME(i) and MTIME(i+2) but not MTIME(i+1), then this has the
same  effect  as  defining  MTIME(i+1)=0.   PK  may redefine MTIME(i).
An ETA may be used in the definition of MTIME(i).

Example:
#+begin_src php
  MTIME(1)=THETA(1)
#+end_src

- Fortran usage and definition
  #+begin_src f90
  ! USAGE:
  USE PKERR_REAL, ONLY :: MTIME

  ! GLOBAL DECLARATION:
  USE SIZES, ONLY: PCT,DPSIZE
  REAL(KIND=DPSIZE) :: MTIME(PCT)
  #+end_src

  Model time parameters MTIME are stored in MTIME if they are defined in
 $PK abbreviated code or if verbatim code  is  present  in  $PK.   This
 makes  them  also  available to the ERROR routine.  However, their eta
 derivatives (if any) are not included.  Hence the ERROR routine should
 not  use model time parameters in such a way as to influence the value
 of Y if those parameters have eta derivatives.

  A user-written PK routine need not define these variables unless  per-
 haps the model time parameter values are used in the ERROR routine.

 (See model time examples).

*** MTDIFF
The value of MTDIFF is 0 when PK is called.  If PK sets MTDIFF to
      a value other than 0, e.g., MTDIFF=1, then PREDPP will understand
      that with that call to PK, the values  of  one  or  more  of  the
      MTIME(i)  have  possibly  been reset.  It is not necessary to set
      MTDIFF at a call to PK with the first record of an individual  or
      with a reset record.
- Fortran usage and definition
  #+begin_src f90
    ! USAGE:
      USE PRMOD_INT, ONLY: MTDIFF

    ! GLOBAL DECLARATION:
      INTEGER(KIND=ISIZE) :: MTDIFF
  #+end_src

 MTDIFF is of interest when model time parameters MTIME are used.

 The  value  of  MTDIFF is 0 when PK is called.  If PK sets MTDIFF to a
 value other than 0, e.g., MTDIFF=1, then PREDPP will  understand  that
 with  that  call to PK, the values of one or more of the MTIME(i) have
 possibly been reset.

 It is not necessary to set MTDIFF at a  call  to  PK  with  the  first
 record  of an individual or with a reset record.  At such calls, it is
 assumed that all MTIME(i) are being set  (if  only  to  their  default
 value of 0).

 Suppose PK has defined a value MTIME(i).  PREDPP calls PK prior to the
 advance to MTIME(i).  PK may change MTIME(i) at this  call.   However,
 the  new  value  of  MTIME(i) is ignored till after the advance.  Only
 then is the new value of MTIME(i) effective.

 MTDIFF=0 (the default) can save considerable run time when  there  are
 many  model  time parameters.  Note that the results are unpredictable
 if the times are in fact changed when MTDIFF=0.

 (See model time examples).

*** MNOW, MPAST, MNEXT
Read-only indicator variables, not to be set by PK.

 - MNOW: MNOW=i if MNEXT(i)=1 for some i.  MNOW=0 otherwise.

 - MNEXT: MNEXT(i)=1 during the advance from the previous time to MTIME(i).
      Otherwise, MNEXT(i)=0.  The previous time may be an event time, a
      non-event time, or a model event time.

 - MPAST: MPAST(i)=0 until the call to PK subsequent to the one  for  which
      MNEXT(i)=1.  At that call MPAST(i)=1. It then retains this value,
      unless MTIME(i) is redefined, in which case MPAST will be  appropriately redefined as another step function.
 - Fortran usage and definition
   #+begin_src f90
   ! USAGE:
     USE ROCM_INT, ONLY: MNOW=>MTNOW,MPAST=>MTPAST,MNEXT=>MTNEXT

   ! GLOBAL DECLARATION:
     USE SIZES, ONLY: PCT
     INTEGER(KIND=ISIZE) :: MTNOW,MTPAST(PCT),MTNEXT(PCT)
   #+end_src

 (See Circadian Example: Examples Using MTIME to Model Periodic Discon-
 tinuities in $DES)

 REFERENCES: Guide VI, section III.F.9


[fn:6] With NONMEM 7.2 and higher, either upper or lower case may be
used. Variables in modules whose names start ROCM or PROCM may be used
only on the right. Variables  in  modules  whose  names start NMPR or
PRDPK may always be used on the right and may sometimes be used on the
left. Names of modules are reserved and may not be  used  in  any
block  of abbreviated code.
