---
title: "User guide"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
weight: 10
---

* Preface
:PROPERTIES:
:UNNUMBERED: t
:END:

This is the online user’s guide for NONMEM. It provides fundamentals
of nonlinear mixed-effects model, basic model building using NONMEM,
and NONMEM example models for population PK analysis. This guide is
part of NONMEM documentation that is largely derived from existing
NONMEM Guides (particularly Guide V, Guide VI, Guide VIII, and INTRODUCTION to NONMEM 7) and aims
to be mostly comprehensive; where additional detail is required, it
explicitly refers back to the guides.

The other components of NONMEM documentation are
NONMEM Reference Manual and NONMEM Cookbook.

We recommend working through this guide, and refer to the NONMEM
Reference Manual when necessary to clarify programming issues.

** Copyright and trademark
:PROPERTIES:
:UNNUMBERED: t
:END:

- Copyright by the Regents of the University of California 1994, 2009.

- Copyright by ICON plc 2011, 2012, 2013,2015,2017,2020,2024.

All rights reserved.

The NONMEM name and logo are registered trademarks of the Regents of the University of California.
