---
title: "Introduction"
author: "Yi Zhang"
draft: false
bookCollapseSection: false
weight: 12
---
{{< katex >}}{{< /katex >}}

* Introduction
NONMEM stands for "Nonlinear Mixed Effects Model." Written in Fortran
90/95, NONMEM fits general nonlinear regression-type models to data.
The data are typically collected from clinical studies of pharmaceutic
agents, involving the administration of a drug to individuals and the
subsequent observation of drug levels (most often in the blood
plasma). Proper modeling of these data involves accounting for both
inter- and intra-subject effects (random effects), as well as measured
concomitant effects (fixed effects). This mixed effect modeling
approach, and the nonlinear nature of the biochemical and
physiological process involved, is the bedrock of NONMEM. Such
modeling is especially useful when there are only a few
pharmacokinetic measurements from each individual sampled in the
population, or when the data collection design varies considerably
between these individuals. However, NONMEM is a general program which
can be used to fit models to a wide variety of data.

NONMEM performs model fitting using a variety of approaches, based on the Maximum
likelihood Estimation as well as Bayesian inference frameworks.


*** Data records
With NONMEM each observation (i.e. each value of the dependent variable of
the regression model) is placed on a separate data record
("observation record"). The value placed on the record is called the
dependent variable (DV) data item. In addition,
NONMEM supports nonobservation data records, with each record containing a
Missing Dependent Variable (MDV. MDV=1 indicates the record is not
an observation record, or, "missing").

NONMEM is mainly concerned with time ordered events:  dose events,
observation events, and other events such as the beginning of a urine
collection and a measured change in kidney function. It expects that
there will be different data records associated with each of the
different events, and that these data records are time ordered. Data
records are also organized into /individual records/.

In the case of population data an individual record is a group of /contiguous/
data records all associated with the same individual and having the same
identification (ID) data item.  In this case the time ordering of data
records refers to the time ordering of data records
/within/ an individual record.  In the case of data from a single
subject individual records do not correspond on a one-to-one basis to either
animal or human subjects,
an individual record is simply any group of
contiguous data records
containing only one observation record and having the same ID data item.
(Although, the presence of a multivariate observation means the
individual record containing it has several observation records, each
containing one element of the observation.)

A typical NONMEM data set looks like this:
#+begin_src r
 ID      TIME    C1      C2  ...  CN      DV     MDV
  1       1.     .5      10        5              1
  1       3.              9       10              1
  1       6.              6              4.1      0
  1       7.              7       10              1
  1      10.              7              5.3      0
  2       2.     .9       8        8              1
  2       2.5             6                       1
  2       6.              7                       1
  2       7.              8              6.4      0
#+end_src
It contains two individuals' records, with the following data items.
- ID: subject identification;
- TIME: time data;
- C1, C2, ..., CN: concomitant variable data items such as covariates.
- DV: dependent value;
- MDV: missing dependent value;

Note that some data items are left blank.  In a NONMEM data set blanks
are null values and will be read by the program as zeros, and
displayed as such in tables and scatterplots.

We discuss event record in detail in Chapter 3.

** Example
Below is a simple NONMEM model.
#+begin_src php
$PROBLEM PHENOBARB ; simple example
$INPUT   ID TIME AMT DV
$DATA    PHENO
$SUBROUTINE ADVAN1
$PK
   TVCL=THETA(1)
   CL=TVCL+ETA(1)
   TVVD=THETA(2)
   V=TVVD+ETA(2)
   K=CL/V
   S1=V
$ERROR
   Y=F+ERR(1)
$THETA  (0,.0047) (0,.99)
$OMEGA  .0000055, .04
$SIGMA  25
$ESTIMATION  PRINT=5
$TABLE     ID TIME AMT
$COVARIANCE
#+end_src

Let us go through the above /control stream/ input.
- NONMEM input uses /control records/. Each control record is
  indicated by a reserved name beginning with "$" symbol. Control
  record $PROB on line 1 gives the NONMEM problem a name. Additionally
  NONMEM uses ";" to indicate comment, thus it ignores everything after ";" on
  line 1.
- Line 2 says that the data file column 1-4 contain subject ID,
  observation time (TIME), dosing amount (AMT), and dependent value (DV), respectively.
- Line 3 says the data is contained in file "PHENO".
- Line 4 says we use a built-in one-compartment model called =ADVAN1=.
  Later in this document you will see that this specifies the one-compartment model
  without first-order absorption.
- Line 5-11: the $PK record specifies the parameters of the =ADVAN1=
  model. In this case, there is only one parameter: the elimination
  rate constatnt =K=. It is shown that =K= is calulated from Clearance =CL= and
  Volume of Distribution =V=. Some reserved NONMEM parameters (=THETA=
  and =ETA=) are used to obtain =CL= and =V=. There is also a scale
  parameter =S1= based on =V=.
- Line 12-13 says that we /assume/ the observation =Y= is
  one-compartment model prediction =F= plus an error term =ERR(1)=.
- Line 14-16 give initial "guess" of the reserved parameters =THETA=,
  =OMEGA=, and =SIGMA=.
- Line 17-19 ask NONMEM to fit the model (ESTIMATE the model
  parameters), print some variables in a TABLE, and calculate the
  COVARANCE of the estimation.

As we go through this guide we will provide details of each record and
symbol in the above model.

** Notations
In this document we use the following notations to describe functions,
arguments, and options.
- Any or all arguments in =[ ]= are optional, e.g. =[foo bar]=, and
  equivalently =[foo] [bar]=,  means =foo= and =bar= are both optional.
- Options delimited by =|= cannot be used together, e.g. =option=a|b=
  means one must choose to specify =option=a= or =option=b=.
- =...= indicates reaptable arguments, e.g. =filename ...= means one can
  supply multiple files, and =[label|value]...= means =label1 value2 value3 label4= is allowed.
- A keyword with "(NONMEM version)" appended indicates the
  record/option as introduced in that version. For example "$DEFAULT
  (NM74)" means the record was introduced in NONMEM v7.4.
- Starting in v7.2 NONMEM  is no longer case-sensitive to reserved
  keywords, reserved variables, or user-defined variables.

[fn:1] Since NONMEM is mainly in Fortran, we frequently employ Fortran
terms in this document. A Fortran "subroutine" is approximately equivalent to
"procedure" or "function" in other programming languages. This docment
often use "subroutine" and "routine" interchangably. A Fortran
"function" is similar to a "subroutine", but with explicit outputs (returns).
[fn:2] ADVAN stands for "ADVANCE" because it is the task of each ADVAN
routine to advance the state vector of compartment amounts (and
partial derivatives of the compartment amounts with respect to random
variables, when appropriate) from each point in time to the next.
