#+title: 1. Introduction
{{< katex >}}{{< /katex >}}

** NONMEM
NONMEM stands for "Nonlinear Mixed Effects Model." Written in Fortran
90/95, NONMEM fits general nonlinear regression-type models to data.
The data are typically collected from clinical studies of pharmaceutic
agents, involving the administration of a drug to individuals and the
subsequent observation of drug levels (most often in the blood
plasma). Proper modeling of these data involves accounting for both
inter- and intra-subject effects (random effects), as well as measured
concomitant effects (fixed effects). This mixed effect modeling
approach, and the nonlinear nature of the biochemical and
physiological process involved, is the bedrock of NONMEM. Such
modeling is especially useful when there are only a few
pharmacokinetic measurements from each individual sampled in the
population, or when the data collection design varies considerably
between these individuals. However, NONMEM is a general program which
can be used to fit models to a wide variety of data.

NONMEM performs model fitting using a variety of approaches, from the Maximum
likelihood Estimation and Bayesian inference frameworks.

*** PREDPP
NONMEM requires user specify the statistical structure and the
nonlinear dynamics of a model.
general, a subroutine [fn:1] called PRED (stands for "PREDiction"), is
required from the user to specifying the likelihood structure based on
data and model parameters. However, the PRED can be very complicated
(especially when ordinary differential equations are involved) and writing it could be demanding for
scientists. A library of PRED routines called PREDPP (stands for PRED
Population Pharmacokinetics) has been created for the population
pharmacokinetics analysis. As one will see, it is trivial to apply
PREDPP to single subject data.

PREDPP contains a number of basic kinetic models that The user make
selection by choosing one or more subroutines from the library. For
example: if the user is interested in a one compartment linear model,
he chooses subroutine from a list of PREDPP Library subroutines:
ADVAN1, ADVAN2, ADVAN3, etc. [fn:2]

We discuss PREDPP in Chapter 5.

*** Data records
With NONMEM each observation (i.e. each value of the dependent variable of
the regression model) is placed on a separate data record
("observation record"). The value placed on the record is called the
dependent variable (DV) data item. In addition,
NONMEM supports nonobservation data records, with each record containing a
Missing Dependent Variable (MDV. MDV=1 indicates the record is not
an observation record, or, "missing").

PREDPP is concerned with time ordered events:  dose events,
observation events, and other events such as the beginning of a urine
collection and a measured change in kidney function. It expects that
there will be different data records associated with each of the
different events, and that these data records are time ordered. Data
records are also organized into /individual records/.

In the case of population data an individual record is a group of /contiguous/
data records all associated with the same individual and having the same
identification (ID) data item.  In this case the time ordering of data
records expected by PREDPP refers to the time ordering of data records
/within/ an individual record.  In the case of data from a single
subject individual records do not correspond on a one-to-one basis to either
animal or human subjects,
an individual record is simply any group of
contiguous data records
containing only one observation record and having the same ID data item.
(Although, the presence of a multivariate observation means the
individual record containing it has several observation records, each
containing one element of the observation.)
In this case the time ordering of data records
expected by PREDPP refers to
the time ordering of data records across all records.

A typical NONMEM data set for PREDPP looks like this:
#+begin_src txt
 ID      TIME    C1      C2  ...  CN      DV     MDV
  1       1.     .5      10        5              1
  1       3.              9       10              1
  1       6.              6              4.1      0
  1       7.              7       10              1
  1      10.              7              5.3      0
  2       2.     .9       8        8              1
  2       2.5             6                       1
  2       6.              7                       1
  2       7.              8              6.4      0
#+end_src
It contains two individuals' records, with the following data items.
- ID: subject identification;
- TIME: time data;
- C1, C2, ..., CN: concomitant variable data items such as covariates.
- DV: dependent value;
- MDV: missing dependent value;

Note that some data items are left blank.  In a NONMEM data set blanks
are null values and will be read by the program as zeros, and
displayed as such in tables and scatterplots.

We discuss event record in detail in section 3.

*** NM-TRAN
NM-TRAN stands for "NONMEM Translator".
It is a separate "stand-alone" program that preprocess input control
stream and data, so that they can be used by NONMEM for model fitting.
In NONMEM applications almost all model specification is done through
NM-TRAN, including all the examples in this documentation.

We discuss details of NM-TRAN in chapter 2.

** Examples

*** Population PK model

** Overview of a NONMEM run
Each NONMEM problem's run consists of a sequence of steps.
1. NONMEM  loads information from a model specification file, if $MSFI
   is present NONMEM makes a single call to  PRED  (with  ICALL=0),
   at  the beginning  of  the  run, to allow PRED to undertake run
   initialization (INITL).

2. NONMEM makes a single call to PRED (with ICALL=1), at the beginning
   of every  problem,  to  allow  PRED  to  undertake problem
   initialization (INITL).

3. SIMULATION STEP: NONMEM inputs initial fixed effects parameters
   from  file  specified  by  $CHAIN, if record is present NONMEM
   performs simulation (with ICALL=4) (if $SIMULATION present).

4. INITIAL ESTIMATE STEP (with ICALL=2): NONMEM obtains initial
   estimates for theta, omega, sigma (if  the control stream does not
   provide all initial estimates).

5. ESTIMATION STEP (with ICALL=2): NONMEM inputs initial etas from
   file specified by $ETAS/$PHIS, if record is present NONMEM searches
   for parameter values that mini- mize the objective function (if
   $ESTIMATION present).  With  NON- MEM 7, multiple Estimation Steps
   can be implemented in  a  single problem.   A  sequence  of  two
   or  more  Estimation Steps  will result in the sequential execution
   of each.

6. COVARIANCE STEP (with ICALL=2) NONMEM obtains a variance-covariance
   matrix of the estimator  and related  information  such  as
   standard  errors  (if $COVARIANCE present).

7. FINALIZATION STEP (with ICALL=2,5,6) NONMEM obtains the following as needed:
  - Classification into subpopulations (if a  MIXTURE  model  is used)(FNLMOD).
  - Posthoc estimates of ETA.
  - Nonparametric  step  (NONPAR,  with ICALL=2): NONMEM obtains
    either marginal cumulatives or  conditional  (nonparametric)
  - Estimates of ETAs for $NONPARAMETRIC.
  - PRED-defined values from NMPRD4 (NP4F) (for tables and scatterplots).

8. NONMEM computes WRES and other diagnostics if they are to be
   displayed in tables or scatters. (PRRES)

9. NONMEM makes a single call to PRED (with ICALL=3), at the end of
   every problem (and subproblem), to allow PRED to undertake problem
   finalization.

10. TABLE STEP: NONMEM constructs tables (if $TABLE present).

11. SCATTERPLOT STEP: NONMEM constructs scatterplots (if $SCATTERPLOT present).

REFERENCES: Guide I, section A.4 , G

[fn:1] Since NONMEM is mainly in Fortran, we frequently employ Fortran
terms in this document. A Fortran "subroutine" is approximately equivalent to
"procedure" or "function" in other programming languages. This docment
often use "subroutine" and "routine" interchangably. A Fortran
"function" is similar to a "subroutine", but with explicit outputs (returns).
[fn:2] ADVAN stands for "ADVANCE" because it is the task of each ADVAN
routine to advance the state vector of compartment amounts (and
partial derivatives of the compartment amounts with respect to random
variables, when appropriate) from each point in time to the next.
