#+title: 4. Model fitting
{{< katex >}}{{< /katex >}}

* Model fitting
All fitting methods aim to adjust model parameters so that model
predictions match the observed data in an 'optimal' way. This set of
"optimal" parameter values is called the parameter estimates. We use
\(\hat{\theta}\), \(\hat{\Omega}\), and \(\hat{\Sigma}\) to denote
estimates to the correspoding NONMEM parameters. Different methods
define “optimal” in different ways. For example, NONMEM's classical
methods such as FO use a least-squares type criterion, the exact form
of which depends on the chosen error model.

In such a method for population model, NONMEM fits an approximate
model, linearized with respect to the random effects for each
individual. The total objective function (likelihood function) is the
weighted sum of individual contributions. The approximate model
is unbiased in predicted individual mean responses.
These predictions are obtained setting \(\hat{\eta}=0\) and
\(\epsilon=0\). In other words, the prediction is for the mean
reponses of individuals with same fixed effects. In addition, one can
also use \(\hat{\theta}\), \(\hat{\Omega}\), and \(\hat{\Sigma}\) to
calculate the covariance matrix (hence the standard error) of individual predictions.
