$PROBLEM WARFARIN
$INPUT ID TIME AMT RATE EVID MDV DV TSTRAT   TMIN   TMAX   REPZ
$DATA warfarinz2.csv ignore=@ 
$SUBROUTINES ADVAN2 TRANS2
$ABBR DECLARE T(NO), INTEGER I, DOWHILE J
$PK
MU_1=LOG(THETA(1))
MU_2=LOG(THETA(2))
MU_3=LOG(THETA(3))
CL=THETA(1)*EXP(ETA(1))
V=THETA(2)*EXP(ETA(2))
KA=THETA(3)*EXP(ETA(3))
S2=V
F1=1.0
$ERROR
 IPRED=A(2)/V
 MEASURE=DV
; MEASURE=LOG(DV) ; Alternative measure
 IF(NEWIND.NE.2) I=0
 IF (NEWL2 ==1 .AND. MDV==0) THEN
    I=I+1
    T(I)=MEASURE
    CORRL2(I,1)=1.0
    J=1
    DO WHILE (J<I)
    DVAL1=MEASURE
    DVAL2=T(J)
; 0.999 needed to make sure correlation between two different data 
; points is less than 1, even if they are of identical value
    CORRL2(J,1)=0.999*EXP(-THETA(4)* &
SQRT( (DVAL1-DVAL2)*(DVAL1-DVAL2)/(DVAL1*DVAL1+DVAL2*DVAL2)   ) )
; Alternative correlation algorithm
;    CORRL2(J,1)=0.999*EXP(-THETA(4)*ABS((DVAL1-DVAL2))/(ABS(DVAL1)+ABS(DVAL2)) ) 
    J=J+1
    ENDDO
 ENDIF
Y=IPRED*(1.0+EPS(1)) + EPS(2)
$THETA
0.15 ;[CL]
8.0  ;[V]
1.0  ;[KA]
(1.0 FIXED) ; [COR]  
$OMEGA (0.07 ) (0.02 ) (0.6 )
$SIGMA (0.01 ) (0.001 FIXED)
$DESIGN GROUPSIZE=100 FIMDIAG=1 APPROX=FOI
         MAXEVAL=99999 PRINT=200 SIGL=9 DESEL=TIME DESELSTRAT=TSTRAT DESELMIN=TMIN DESELMAX=TMAX
$EST GRD=TS(4) 
$TABLE ID TIME AMT EVID MDV DV IPRED NOPRINT NOAPPEND FILE=warfarin_fobc5.tab
